### PR TITLE
[PUBDEV-3410] [PUBDEV-3426] Improvements to estimators

### PR DESCRIPTION
**Pull request by st-pasha**
* Raise error if the user is passing unknown parameters to an *Estimator() constructor;
* Typecheck all passed parameters when set via setters and when passed in the constructor;
* Move documentation for each parameter to the parameter itself (rather than all of them being defined in the class' preamble);
* Convert all enum values to the Python style (i.e. snake_case instead of UPPER_CASE or CamelCase). This change should be fully backward-compatible.
* Some of the parameters required special treatment -- fix types for those.

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/206)

### CODE REVIEW

**Comment by arnocandel** [comment]
> Move documentation for each parameter to the parameter itself (rather than all of them being defined in the class' preamble);

Is this going to make documentation harder? how do python users look at the arguments?

**Comment by ledell** [comment]
Regarding [this commit](https://github.com/h2oai/h2o-3/pull/206/commits/46b0c6593daf839f52f018e4678e5ff051e0260f): What does it mean for `initial_weights` and `initial_biases` to be a list of H2OFrames?  Shouldn't it just be a single-column H2OFrame with number of rows == number of rows in the training set?

**Comment by ledell** [comment]
There is only [one JIRA ticket](https://0xdata.atlassian.net/browse/PUBDEV-3410) for these 13 commits, and that JIRA ticket pertains to only one of the commits.  Please add JIRA tickets to document these changes so that these changes will be added to our "Recent changes" documentation and so that we have a better record of all these changes.  You can group the related commits together into single JIRA tickets.

**Comment by arnocandel** [comment]
No, initial weights and biases are per-layer pre-trained model coefficients, from TensorFlow or something similar.  That is a bunch of matrices (Frames) and vectors (1-column Frames).

**Comment by arnocandel** [comment]
I would like to see the list of arguments in the class preamble, as before.

**Comment by st-pasha** [comment]
@arnocandel 
There is a lot of reasons to put documentation with the parameters themselves:
* Leaving parameters undocumented raises warnings from pydocstyle, and we strive to achieve warning-free code;
* It gives a user the ability to query information about each parameter individually: for example, saying `help(model.class_sampling_factors)` will bring information about just that parameter;
* Annotating types of each parameter gives ability for tools such as PyCharm and MyPy to statically check the code and find inconsistencies in usage;
* Python's built-in `help(*Estimator)` function will list all help for all the parameters almost exactly as before. Same goes for Sphinx-generated documentation

**Comment by st-pasha** [comment]
@ledell I've added another ticket https://0xdata.atlassian.net/browse/PUBDEV-3426
There are many commits because it was hard to get all the special cases right from the first time, so I had to test and discover them in Jenkins.

**Pull request merged**
