### PR TITLE
PUBDEV-4267: Change default nthreads to -1 in R API h2o.init()

### PR DESCRIPTION
**Pull request by navdeep-G**
* This PR will set `nthreads` in `h2o.init()` to `-1` by default and set `nthreads` in `h2o.init()` to `-2` for R examples to comply with CRAN.

### CODE REVIEW

**Comment by navdeep-G** [comment]
According to the our documentation: ` -2 means use the CRAN default of 2 CPUs`.

And we will switch. See my change to `logging.R`. My understanding is that this `h2o.init()` will set up the cluster for example runs in R CMD CHECK

**Comment by ledell** [comment]
@mmalohlava I have the same question, why do we use -2 when we can just use 2?  @tomkraljevic do you know the history of the -2 value?

**Comment by navdeep-G** [comment]
@ledell @mmalohlava I have updated it to `2` for examples

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Pull request merged**
