### PR TITLE
[PUBDEV-8397] Make the parquet parser handle dates

### PR DESCRIPTION
**Pull request by krasinski**

### CODE REVIEW

**Review by neemah2o — COMMENTED** [review]
As far as I understand, this looks good to me.

**Comment by krasinski** [comment]
@michalkurka I rebased that branch onto rel-zizler

**Comment by michalkurka** [comment]
@krasinski thanks,

the test failed again today (Nov 24):

```
Error
File not found: smalldata/parser/parquet/parquet-file-with-date-column.snappy.parquet
Stacktrace
java.lang.AssertionError: File not found: smalldata/parser/parquet/parquet-file-with-date-column.snappy.parquet
	at water.parser.parquet.ParseTestParquet.testShouldCorrectlyParseDates[0]()
```

I checked on the machine where the test ran and found it there:

```
jenkins@mr-0xk1:/home/0xdiag/smalldata$ ls parser/parquet/parquet-file-with-date-column.snappy.parquet
parser/parquet/parquet-file-with-date-column.snappy.parquet
```

strange - I will look into it more

**Review by michalkurka — APPROVED** [review]
Thank you, great work @krasinski

**Pull request merged**
