### PR TITLE
[BUILD] Force enable extension

### PR DESCRIPTION
**Pull request by mmalohlava**
This change enables system option to force toggle (on/off) a specific extension.

For example, to enable XGBoost REST API on the system which does not
support XGBoost:

```
JAVA_TOOL_OPTIONS="-Dsys.ai.h2o.ext.rest.toggle.XGBoost=true" java -jar build/h2o.jar
```

### CODE REVIEW

**Comment by michalkurka** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Pull request merged**
