### PR TITLE
[WIP] Remove a beta feature

### PR DESCRIPTION
**Pull request by michalkurka**
This branch should not actually be merged to a target branch.

### CODE REVIEW

**Comment by michalkurka** [comment]
@h2o-ops please test!

**Comment by michalkurka** [comment]
@h2o-ops please test!

**Comment by angela0xdata** [comment]
@h2o-ops please test!

**Comment by michalkurka** [comment]
@h2o-ops please test!

**Comment by michalkurka** [comment]
Tests passed except for PR_runit_small_client_mode (r_suite.runit_p-value_synthetic.R) - this is not a true failure.

**Comment by abal5** [comment]
@h2o-ops please test!

**Pull request closed without merging**
