### PR TITLE
[PUBDEV-4375] Enable different PCA implementations

### PR DESCRIPTION
**Pull request by terrytangyuan**
This is a continuation of the efforts in https://github.com/h2oai/h2o-3/pull/1025. In addition:

- Exposed the `pca_implementation` parameter in R and Python bindings to select different implementations
- Added tests to make sure every implementation works and gives the correct result

Note that:

- testdir_algos/pca/runit_pubdev_3502_pca_hangs_large_NOPASS.R still hangs for randomized method. I spent some time but couldn't resolve it. The feedback loop is also very long and it would be great if other people can jump in and help.
- I left `PCAImplementation` to be `Enum` since at this point I don't see a huge potential that users would want to add their own implementation given that H2O users are mostly high-level "users" instead of developers. It's also more consistent with the current setup of `PCAMethod`. As @michalkurka pointed out, it would be better if the factory could discover the implementations dynamically (eg. using Java SPI) but it's a little trickier to make the R/Python bindings work similarly. We should probably leave that as future work/discussion for now.  

@michalkurka @mmalohlava @wendycwong Could you review this?

### CODE REVIEW

**Comment by terrytangyuan** [comment]
I saw "MR Jenkins B4 - Build finished" but Github is showing this check unsuccessful. Is there anything I missed?

**Comment by michalkurka** [comment]
@terrytangyuan Right now we are in a transition phase and we have two sets of Jenkins jobs:
- old manually defined jobs (MR Jenkins B4)
- new jobs defined in Jenkinsfiles (continuous-integration/jenkins/pr-head)

We are moving away from the old jobs. All functionality should now be in new jobs as well but we keep the old ones here for reference (this is only temporary). For the PR the old jobs failed to start but the new jobs finished successfully.

You can restart the tests by adding a comment "please test" and send it to "h2o-ops" (see my next comment)

**Comment by michalkurka** [comment]
@h2o-ops please test

**Comment by terrytangyuan** [comment]
@michalkurka I added more descriptions to the new parameter and renamed it to be `pca_impl` (discussed with folks in #api-updates). Could you take another look? Thanks!

**Comment by terrytangyuan** [comment]
@h2o-ops please test

**Comment by wendycwong** [comment]
@h2o-ops please test

**Comment by terrytangyuan** [comment]
It seems like master is failing. Does this PR look good for merge?

**Comment by michalkurka** [comment]
@terrytangyuan We need to wait after 3.18 release (next week).

**Comment by michalkurka** [comment]
Rebased on top latest master

**Comment by michalkurka** [comment]
LGTM, lets wait for green tests

**Pull request merged**
