### PR TITLE
PUBDEV-5993 - updated Retrofit and okHttp dependecies

### PR DESCRIPTION
**Pull request by Sloug**

### CODE REVIEW

**Comment by michalkurka** [comment]
Mr. Jenkins, please test!

**Comment by michal-raska** [comment]
Mr. Jenkins, please test!

**Comment by michalkurka** [comment]
Mr. Jenkins, please test!

**Comment by honzasterba** [comment]
created https://github.com/h2oai/h2o-3/pull/3369 to re-test and merge this

**Pull request closed without merging**
