### PR TITLE
PUBDEV-4745 Adds support for Cloudera 5.10

### PR DESCRIPTION
**Pull request by michalkurka**

### CODE REVIEW

**Comment by abal5** [comment]
I will checkout this branch and add the missing parts listed here:

https://github.com/h2oai/h2o-3/blob/master/README.md#BuildingHadoop

**Comment by michalkurka** [comment]
@abal5 thank Anmol, I only did steps 1 & 2 in this PR

**Comment by michalkurka** [comment]
@h2o-ops please test!

**Comment by michalkurka** [comment]
@h2o-ops please test!

**Pull request merged**
