### PR TITLE
fixing (some) warnings in Frame.java

### PR DESCRIPTION
**Pull request by st-pasha**
Fix Frame class constructor so that it accepts Key<Frame> parameter instead of an arbitrary Key. Also addressed some of the warnings in Frame.java

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/196)

### CODE REVIEW

**Comment by arnocandel** [comment]
I'm not a huge fan of all the cosmetic refactoring, would prefer to keep commits to h2o-core small, such that we preserve the git history.

**Comment by st-pasha** [comment]
So should I discard it then?

**Comment by arnocandel** [comment]
Nah, it's fine, but I'd try to keep the white-space-only changes to a minimum, to keep the history.

**Comment by mmalohlava** [comment]
@st-pasha what is motivation for this change? I like it, however, i need to test it on Scala side (mainly SW), since Scala is much more strict in this context.

**Comment by st-pasha** [comment]
@mmalohlava The motivation was this: I needed to fix Frame.java so that it could output 0-row frames into csvs correctly. And while making this change I noticed that there are lots of warnings in Frame.java related to incorrect use of generics; so I decided to fix those as well. However since it was a much bigger change than the actual csv-writing fix (which is now already merged), I made it into a separate PR.

**Pull request merged**
