### PR TITLE
Update Python test requirements to current Twine

### PR DESCRIPTION
**Pull request by brainwane**
I'm one of the maintainers of [Twine](https://libraries.io/pypi/twine). We've just released 1.10.0 and I would appreciate if you could upgrade your Python tests requirement. Thanks.

### CODE REVIEW

**Comment by brainwane** [comment]
I'm sorry - I read `CONTRIBUTING.md` but I'm in a bit of a rush and don't have time to make an account on your JIRA system and file a ticket at the moment.

**Comment by michal-raska** [comment]
@brainwane Hello, thanks for the information!. I will update the version in a few days.

**Comment by brainwane** [comment]
Thank you!

While looking at your Twine usage, I saw that [you ignore 503 errors when uploading to PyPI](https://github.com/h2oai/h2o-3/blob/master/scripts/jenkins/jenkinsfiles/Jenkinsfile-Release#L437), as referenced in #2040. How often do you see those errors? The new pypi.org does not frequently return 503s, I hope.

**Comment by michal-raska** [comment]
@brainwane the errors stopped showing a few weeks ago so it's been fixed probably 🙂. Before that, we got 503 for each upload.

**Comment by brainwane** [comment]
Thanks for letting me know, @michal-raska! If you start seeing problems like that again, I encourage you to file them at https://github.com/pypa/warehouse/issues .

**Comment by michal-raska** [comment]
@brainwane fixed in #2183 and #2193, thanks again!

**Pull request closed without merging**
