### PR TITLE
PUBDEV-6196: expose include_algos parameter to AutoML Py+R clients

### PR DESCRIPTION
**Pull request by seb-h2o**
https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-6196

this is a client-only feature

### CODE REVIEW

**Comment by angela0xdata** [comment]
@seb-h2o can you add R and Python tests for this?

**Comment by seb-h2o** [comment]
@angela0xdata what kind of tests are you thinking about? I already added Py+R UT, cf. changes in `runit_automl_args.R` and `pyunit_automl_args.py`

**Comment by angela0xdata** [comment]
@seb-h2o oh, sorry. I didn't see those in here. (How the heck did I miss those =/)

**Comment by ledell** [comment]
@seb-h2o Will this throw a client-side error if the user sets both args?  Thx.

**Comment by seb-h2o** [comment]
@ledell yes, it will, there are even tests checking this behaviour ;)

**Comment by ledell** [comment]
@seb-h2o Can you make the changes (add the new param) to automl.rst?

**Comment by seb-h2o** [comment]
@ledell, I just added support for `include_algos` on backend, so it's now available through Java API or REST API but... still not in Flow, as automl doesn't have any API discovery in Flow, contrary to other algos.
However, I'm not even sure we should have it in Flow at all: 
1. the `exclude_algos` field is implemented as checkboxes, so adding another field with the same options will just make the form more cumbersome: we don't offer than many algorithms, so it's easy to click a couple more times to get include logic.
I think an `include_algos` could make sense if it were implemented like tags in Jira for example (cf. https://selectize.github.io/selectize.js/#content) but with basic checkboxes, I don't see any benefit.
2. if we had both, the recommended UI behaviour would be to hide one as soon as we start making a selection in the other to avoid exceptions: not usually difficult, if it were not for Flow...

**Comment by ledell** [comment]
@seb-h2o I totally agree with you -- I think we should only have the `exclude_algos` option in Flow.  Having both is confusing.

**Pull request merged**
