### PR TITLE
[PUBDEV-5044] Fix Jaro-Winkler Dependency

### PR DESCRIPTION
**Pull request by jakubhava**

### CODE REVIEW

**Comment by michalkurka** [comment]
What do you think about releasing h2o-version of the dependency instead of using a copy of the class? Both approaches have advantages and disadvantages. The advantage of having a custom release is that it is more trackable imho

**Comment by jakubhava** [comment]
We were discussing this with @mmalohlava. I don't have that strong opinion on either both approaches.

This approach seems a bit cleaner as we don't have to re-release. Buy your argument works as well for the second approach.

**Comment by mmalohlava** [comment]
So ideas:
  (1) bundle code directly 
  (2) bundle full modified Duke jar file
  (3) release our H2O-VESION in to maven

I am still not sure about (3). The option (2) is annoying, but possible.
(1) can be slightly more clever and apply the embedded version only if the actual Duke version is fleaky (kind of of runtime patch based on run of tiny test) .

**Comment by jakubhava** [comment]
@mmalohlava the difference between 1) and 2) is that in 1) we include just the changed class and use the rest of duke ( like in this PR ) and in 2)  we "merge" modified duke jar into h2o jar ?

**Comment by michalkurka** [comment]
lets do it this way :)

**Comment by jakubhava** [comment]
oki, are you happy with this @mmalohlava as well pls ? I will merge after I'm sure it's fine

**Pull request merged**
