### PR TITLE
[PUBDEV-3472] [PUBDEV-3473] support negative indices and strides in row selection in python

### PR DESCRIPTION
**Pull request by st-pasha**
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/435)

### CODE REVIEW

**Comment by st-pasha** [comment]
@h2o-ops please test

**Comment by abal5** [comment]
@h2o-ops please test

**Comment by abal5** [comment]
@h2o-ops please test

**Comment by abal5** [comment]
@h2o-ops please test

**Comment by navdeep-G** [comment]
@h2o-ops please test

**Comment by st-pasha** [comment]
Barring one `java.lang.IllegalStateException: Could not download file` the tests suggest it works fine.

**Comment by navdeep-G** [comment]
LGTM

**Pull request merged**
