### PR TITLE
[PUBDEV-8951] Add Link to steam jar and h2o client into Download Page [nocheck]

### PR DESCRIPTION
**Pull request by mn-mikke**
Screenshot 2023-01-04 at 15 15 16

### CODE REVIEW

**Review by hannah-tillman — APPROVED** [review]
Did small format updates to match previous pages -- LGTM

**Comment by mn-mikke** [comment]
@hannah-tillman Great, thanks!

**Review by valenad1 — APPROVED** [review]
LGTM, please check nightly release pipeline after merge that the documentation was correctly created. Last time a made a stupid mistake, and users cannot click anywhere in the release page... We can catch this error if we check it immediately 👍

**Comment by mn-mikke** [comment]
Thanks @valenad1 for the warning!

**Comment by mn-mikke** [comment]
@valenad1 IMHO, it looks ok: https://s3.amazonaws.com/h2o-release/h2o/master/6067/index.html

**Pull request merged**
