### PR TITLE
Make a pyunit for the config file reader

### PR DESCRIPTION
**Pull request by st-pasha**
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/549)

### CODE REVIEW

**Comment by st-pasha** [comment]
@h2o-ops please test!

**Comment by st-pasha** [comment]
@h2o-ops please test!

**Comment by st-pasha** [comment]
@h2o-ops please test!

**Comment by Mistobaan** [comment]
Why do we use a custom config parser instead of the [standard one](https://docs.python.org/3/library/configparser.html)

**Comment by st-pasha** [comment]
@Mistobaan The actual logic that reads and parses the file is quite small: about 20 lines. At the same time we use some features that are not in the standard `ConfigReader` class: language-specific key prefixes (such as `py:`), verification that all keys read are valid; and in case of error we log it to console instead of throwing an exception (thus h2o remains usable even if the config file is malformed). I suspect that trying to  implement all of these on top of the standard configreader would be more complicated than the current code.

**Pull request merged**
