### PR TITLE
Fix PUBDEV-3207, PUBDEV-3208, PUBDEV-3211 and a rollup cache bug

### PR DESCRIPTION
**Pull request by arnocandel**
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/75)

### CODE REVIEW

**Comment by arnocandel** [comment]
Looking at some failures in GLM in my personal jenkins.

**Comment by abal5** [comment]
Can one of the admins verify this patch?

**Comment by arnocandel** [comment]
Testing on private Jenkins again.

**Comment by arnocandel** [comment]
Tests are passing.

**Pull request merged**
