### PR TITLE
PUBDEV-4458: Move the rest of build_control args to top-level in R API

### PR DESCRIPTION
**Pull request by ledell**
https://0xdata.atlassian.net/browse/PUBDEV-4458

### CODE REVIEW

**Comment by ledell** [comment]
@h2o-ops please test!

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by ledell** [comment]
There are too many failed tests with this PR, so I am going to break it up into smaller PRs to debug the issues.  Here is the first one (which has been merged already): https://github.com/h2oai/h2o-3/pull/1182

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by ledell** [comment]
This PR was replaced by two other PRs: https://github.com/h2oai/h2o-3/pull/1182 and https://github.com/h2oai/h2o-3/pull/1187 and so this can be closed w/o merging.

**Pull request closed without merging**
