### PR TITLE
GLM datainfo imputeMissing and missingBucket parameters were swapped

### PR DESCRIPTION
**Pull request by ptoth-rapidminer**
https://0xdata.atlassian.net/browse/PUBDEV-3194

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/68)

### CODE REVIEW

**Comment by abal5** [comment]
Can one of the admins verify this patch?

**Comment by abal5** [comment]
Currently testing this PR please wait for response from the team.

**Comment by abal5** [comment]
Currently testing this PR please wait for response from the team.

**Comment by abal5** [comment]
Currently testing this PR please wait for response from the team.

**Comment by abal5** [comment]
Currently testing this PR please wait for response from the team.

**Comment by mmalohlava** [comment]
Is it possible to provide a jUnit test demonstrating `java.lang.ArrayIndexOutOfBoundsException` mentioned in the JIRA?

**Comment by ptoth-rapidminer** [comment]
Hi, we will try to add a test soon.

**Comment by arnocandel** [comment]
This is a no-brainer, the arguments were just flipped. Merging.

**Pull request merged**
