### PR TITLE
Fixes incorrect behavior of NewChunk.addUUID - the "chunk-local" version

### PR DESCRIPTION
**Pull request by michalkurka**
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/418)

### CODE REVIEW

**Comment by mmalohlava** [comment]
@h2o-ops please test

**Comment by michalkurka** [comment]
@h2o-ops please test

**Comment by michalkurka** [comment]
@h2o-ops please test

**Comment by michalkurka** [comment]
Seems like there was an issue with testing this branch. Personal jenkins is green, merging after discussion with Anmol.

**Comment by vpatryshev** [comment]
I don't get it; tests are failing, but we are merging? Or?

Thanks,
-Vlad

**Comment by kurkami** [comment]
@vpatryshev Tests are actually not failing. The builds were failing because of infrastructure issues. My personal builds on Jenkins were passing OK. I brought it up with @abal5 and we agreed on merging it.

**Pull request merged**
