### PR TITLE
PUBDEV-5924: Fixed merge bug where rows without merge key should be NaN or null

### PR DESCRIPTION
**Pull request by wendycwong**
This PR fixes JIRA: https://0xdata.atlassian.net/browse/PUBDEV-5924?filter=-1

Andrey found the following merge bug:
If there is a NaN in the right frame merge column, it will be included in the final merged frame.  However, this should not be the case.  Any rows in the right frame that contains NaN in the merge columns should be removed.

In this PR, I fixed this problem by going through the right frame and delete all rows with NaN in the merged columns. 

I have written a Junit unit test to verify that the bug exposed by Andrey is no longer there.

I wrote a longer pyunit test for large datasets to make sure that merge values found in one frame but not the other should be filled with NaN/null.  I checked and made sure that this is true for all.x=True, and all.y=True.

### CODE REVIEW

**Comment by wendycwong** [comment]
Andrey:  

Sure will do.  I will add a new test with your new frame values.

**Comment by wendycwong** [comment]
Andrey:  

You are right, the returned frame is too big.  The problem is with assigning the number of merged rows.  Fixing it now.  Good catch.


Wendy

**Comment by deil87** [comment]
Thank you @wendycwong ! Even though I'm not really sure that we should treat nulls differently like you were discussing with Matt (nullLeft and nullRight).... because I believe that null is null everywhere. And we should probably merge by null as well. Since you have decided to drop rows with nulls from the right side the only way I can use merge function in my Target Encoder is by imputing nulls with some value beforehand.... because I want to treat those rows just as a different category. But that is fine....I had this imputation logic written long ago. I've played with the tests a little bit more and they look stable. No objections from my side.

**Comment by wendycwong** [comment]
I have created a JIRA which will allow merging of null left and right rows: https://0xdata.atlassian.net/browse/PUBDEV-5973?filter=-2

**Pull request merged**
