### PR TITLE
Fix HTTPS on Jetty 9 (for Hadoop 3.x)

### PR DESCRIPTION
**Pull request by michalkurka**

### CODE REVIEW

**Comment by michalkurka** [comment]
@Pscheidl WIP, tests to come

**Comment by michalkurka** [comment]
This currently doesn't work in proxy mode with SSL enabled:

> GET / HTTP/1.1
> Host: 192.168.1.64:54323
> User-Agent: curl/7.55.1
> Accept: */*
> 
< HTTP/1.1 502 Bad Gateway
< Date: Thu, 24 Jan 2019 03:37:47 GMT
< Connection: close
< Server: Jetty(9.3.20.v20170531)

**Comment by michalkurka** [comment]
The issue above ^^^ should be fixed now, re-running tests.

**Comment by Pscheidl** [comment]
CDH 6.1 tests passed, several non-related tests failed. Re-running.

This failure appeared in CDH 5.9 tests: 
```
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/home2/jenkins/slave_dir_from_mr-0xc1/workspace/p-smoke-pipeline_michalk_fix-ssl/cdh-5.9---standalone/h2o-3/h2o-py/scripts/h2o-py-test-setup.py", line 182, in <module>
    h2o_test_setup(sys.argv)
  File "/home2/jenkins/slave_dir_from_mr-0xc1/workspace/p-smoke-pipeline_michalk_fix-ssl/cdh-5.9---standalone/h2o-3/h2o-py/scripts/h2o-py-test-setup.py", line 177, in h2o_test_setup
    elif _IS_PYUNIT_:    pyunit_utils.pyunit_exec(_TEST_NAME_)
  File "/home2/jenkins/slave_dir_from_mr-0xc1/workspace/p-smoke-pipeline_michalk_fix-ssl/cdh-5.9---standalone/h2o-3/h2o-py/tests/pyunit_utils/utilsPY.py", line 485, in pyunit_exec
    exec(pyunit_c, {})
  File "/home2/jenkins/slave_dir_from_mr-0xc1/workspace/p-smoke-pipeline_michalk_fix-ssl/cdh-5.9---standalone/h2o-3/h2o-hadoop-2/tests/python/pyunit_s3_import_export.py", line 25, in <module>
    s3_import_export()
  File "/home2/jenkins/slave_dir_from_mr-0xc1/workspace/p-smoke-pipeline_michalk_fix-ssl/cdh-5.9---standalone/h2o-3/h2o-hadoop-2/tests/python/pyunit_s3_import_export.py", line 19, in s3_import_export
    s3_frame = h2o.import_file(s3_path)
  File "/envs/h2o_env_python2.7/local/lib/python2.7/site-packages/h2o/h2o.py", line 433, in import_file
    return H2OFrame()._import_parse(path, pattern, destination_frame, header, sep, col_names, col_types, na_strings, skipped_columns)
  File "/envs/h2o_env_python2.7/local/lib/python2.7/site-packages/h2o/frame.py", line 315, in _import_parse
    rawkey = h2o.lazy_import(path, pattern)
  File "/envs/h2o_env_python2.7/local/lib/python2.7/site-packages/h2o/h2o.py", line 297, in lazy_import
    return _import_multi(paths, pattern)
  File "/envs/h2o_env_python2.7/local/lib/python2.7/site-packages/h2o/h2o.py", line 304, in _import_multi
    if j["fails"]: raise ValueError("ImportFiles of '" + ".".join(paths) + "' failed on " + str(j["fails"]))
ValueError: ImportFiles of 's3a://test.0xdata.com/h2o-hadoop-tests/test-export/s3a/exported.20190124-084946.8c54f3ee-498c-4433-b405-6aebca9210b9.csv.zip' failed on [u"Path does not exist: 's3a://test.0xdata.com/h2o-hadoop-tests/test-export/s3a/exported.20190124-084946.8c54f3ee-498c-4433-b405-6aebca9210b9.csv.zip'"]
```

**Comment by Pscheidl** [comment]
Started the tests once again.

**Pull request merged**
