### PR TITLE
[PUBDEV-3616] relocate certain Rapids classes

### PR DESCRIPTION
**Pull request by st-pasha**
https://0xdata.atlassian.net/browse/PUBDEV-3616

---

This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/434)

### CODE REVIEW

**Comment by mmalohlava** [comment]
Adding more people to reviews since 157 modified files is no go for me right now. 
There has to be really good reason for that since 157 modifications affects everybody.

**Comment by st-pasha** [comment]
@mmalohlava This PR arose from our discussion on [PR 384] (https://github.com/h2oai/h2o-3/pull/384). Remember, you mentioned that I should remove all those TODOs from the code and put them into a JIRA -- so that that JIRA can be owned by someone and implemented eventually (as opposed to TODOs which seem to remain in the code forever...). So I'm not quite certain why do you have reservations about this move right now, or what your proposed next steps are.

As for the number of files affected by the change -- most of those are only 1 or 2 lines of change per file; and also all changes are concentrated within the Rapids code, which only very small number of people work with.

**Comment by mmalohlava** [comment]
Yup yup, mea culpa - i did not expect that it will trigger so big change.

**Comment by mmalohlava** [comment]
Any feedback from affected parts? @michalkurka @tomasnykodym ?

**Comment by navdeep-G** [comment]
One question, could this possibly affect the other 31 PRs in the queue? If so, I would hold off on merging until the rest are resolved.

**Comment by michalkurka** [comment]
@mmalohlava I don't see any issue with this PR. The changes make sense to me and if the merge causes any merge-conflicts they will be easy to resolve.

**Comment by mmalohlava** [comment]
@michalkurka  thank you! i wanted to be sure that it is not going to interfere with your work for custs, since it is a wide change.

**Comment by st-pasha** [comment]
@tomasnykodym In computer science the word "primitive" has a specific meaning: https://en.wikipedia.org/wiki/Primitive_data_type
In Rapids there are multiple kinds of primitives, including AstId, AstNum, AstNumList, AstStr, AstStrList, AstFrame, AstFunction, AstPrimitive (in the old nomenclature). I may be missing some. Anyways, singling out one of them and calling it "the primitive" is highly misleading. 

Moreover using the name AstFunction to denote something that does not encompass all the functions in the language is similarly confusing.

**Comment by spennihana** [comment]
@st-pasha while you're at it, can you please fix your bad name changing of AST -> Ast... you should be aware that it's AST since acronyms are typically all capitalized (https://en.wikipedia.org/wiki/Abstract_syntax_tree)

**Comment by st-pasha** [comment]
@spennihana Hi, thank you for your feedback.
I'm well aware that "AST" stands for "abstract syntax tree", and the rules of English dictate that an abbreviation has to be capitalized. Unfortunately, we do not write in English, we write in Java, which has its own rules for capitalization. And the convention in the computing world seems to be that abbreviations should *not* in fact be capitalized:

* Google Style Guide: https://google.github.io/styleguide/javaguide.html#s5.3-camel-case
* http://stackoverflow.com/questions/2236807/java-naming-convention-with-acronyms
* (Facebook has the same rule, although they don't publish the style guide externally).

Bear in mind that this is not an arbitrary convention. There are literally dozen of reasons why such form is more usable than the more traditional uppercase.

**Comment by vpatryshev** [comment]
It's not a bad naming, it's a standard naming style in Java. 
See, e.g. this: http://www.oracle.com/technetwork/java/codeconventions-135099.html

I believe it is better not to surprise the world with home-made conventions.

**Comment by spennihana** [comment]
@st-pasha @vpatryshev thanks ya I've read these guides when I was still a student, too. But guides are not law, and it's better to follow the general trends and naming conventions so as not to confuse people that have been using these names for a long time.

For example, look at the Groovy code base:
https://github.com/groovy/groovy-core/tree/master/src/main/org/codehaus/groovy/ast

Or maybe take a look at Eclipse: https://github.com/eclipse/eclipse.jdt.core/tree/master/org.eclipse.jdt.apt.core/src/org/eclipse/jdt/apt/core/internal/declaration

**Comment by vpatryshev** [comment]
This may be not the right place for discussing Java, but I have to share
share my opinion on both Groovy and Eclipse. Neither are good examples of
Java programming. I'd hold closer to the standard source, which is now
Oracle, and not use marginal developers as an inspiration for good
practices, especially since their code is gradually going into oblivion
these days.

I am sure we, generally, rather should support good practices, and tolerate
not so good ones just because perfection is not our primary goal. But
insisting on continuing bad practices because "others do that too" sounds
really weird.


Thanks,
-Vlad

**Comment by arnocandel** [comment]
+1 I'd say we should focus in changes which actually bring some measureable benefit to H2O.

**Comment by spennihana** [comment]
it's not the right place, it's why i deleted my comment.
Changing AST -> Ast is counterproductive to people that have been maintaining this code for the last few years :). For example, I wanted to push loop-fusion and other _real_ optimizations. This type of name-mangling on a frequent basis is harmful.

**Comment by st-pasha** [comment]
@spennihana what if it is pro-productive to people that will be maintaining the code for the next few years? :)
Anyways, I apologize if any harm has been inadvertently done. If you have an old branch with loop-fusion and other optimizations that you can't reconcile because of this or other related changes -- please feel free to forward it to me and I'll see how to whip it into shape.
I agree overall that frequent name changes are to be avoided. In fact this PR changes only 3 names, those that I found to be most confusing. The majority of the changes are relocation of files that were improperly placed in the root of the package.

**Comment by cliffclick** [comment]
Wow, button pressing all the way.

My 0.02c -

- Name change benefits are always in the eye of the beholder.  To 
somebody writing the compiler.... what you did made it obviously harder 
to read, understand and maintain.  If you end up writing a few of your 
own (and I've written more than 20 full blow compilers that got heavy 
use by different folks, not just HotSpot C2), you'll discover the wisdom 
in the structure that I started with. Meanwhile, the original structure 
is annoying/confusing to you... but please try writing a few before you 
declare with Grand Pomp one way is better than another.

- ASTId is not, in fact, a primitive - by any programming language 
standard.  A primitive is a basic function in pure the mathematical 
sense, such as add or multiply; it can be a function taking a function, 
such as ddply.  Random is not a function technically, because the seed 
is side-effected.  ASTid holds a **value** which you can get, and 
sometimes side-effect update.  It's not a function, and does not purport 
to be one by any stretch.  You can do cool transforms with functions 
that you cannot do with ASTid, such as re-order without regard to 
side-effects.

- Me, I predate Groovy & Eclipse both, by a lot.  I predate nearly all 
the modern coding standards, be they Java or C or Fortran, usually by a 
lot.  I've seen coding standards come and go and mostly.... and mostly 
they just cause friction between people. Never seen an enforced common 
coding style actually make a project succeed, or apparently help it in 
any way.  I've seen plenty of failed projects with enforced standards.  
Like the fore-mentioned name-changes, the beauty is usually in the eye 
of the standard-writer and rarely in the eyes of more than a few of the 
programmers.  I suggest for the name-changers in the world you "chillax" 
a little and learn to roll with names that aren't your idea of pretty.

- When writing a compiler, do as compiler-writers do, not as the 
implementation language capitalization suggests.  AST vs Ast has 40+ yrs 
of history.  Learn the lingo, and 40yrs of history open up to you; fight 
it and you stub your toe with every step.

- Echoing Tomas, focus on changes that make a real difference... and 
then you'll realize that AST vs Ast is mostly noise, and the key thing 
is that you can execute a lisp-like language compiled on R/Python and 
executed in Java.  (The AST/Ast is nothing more than, nor less than, the 
vehicle for that cool functionality.  You may want to add more coolness 
(e.g. loop fusion) and then you might want to start looking at what 
other folks who've done this already did... and every syntactic 
difference between what you got and what you read is just another stumble).

- As for the endless appearance of junk null test PRs: *fail fast, fail 
hard*.  Then fix yer bugs.  40 years of solid experience here!!!  
Avoiding an NPE generally actually means you turned an obvious blatant 
bug into a subtle one... or that the null test can never fail (but by 
being in the code it *looks* like it can).  It would be nice if Java had 
a real null-ness type property aka Elm / Kotlin but it doesn't.  This 
means the code is FULL of invariants such as: 
"|(_ss==null)iff(_is==null)|", and very commonly |"A.length==B.length|" 
for two arrays A and B... but there's no way to enforce the invariant at 
the type level.  So you end up with either: tons of asserts (mostly all 
obviously redundant), or a Big Hairy Comment up front explaining the 
invariant... or junk tests that can never fail and obfuscate the code by 
making it look like the invariant doesn't hold.  None of these options 
are very appealing.  I always go with the Big Hairy Comment, and ask 
that programmers understand the Big Picture before making 
detail-oriented changes... it's faster code, it's cleaner code, and to 
mine eye more beautiful.  Next time you don't understand why an NPE 
can't happen, toss in an assert and find a test case... or stare 
harder.  If it hasn't broken yet, maybe it's because it can't!


Cliff

**Pull request merged**
