### PR TITLE
Create .h2o.getBinary() method to extract binary data from H2O (MOJOs)

### PR DESCRIPTION
**Pull request by navdeep-G**
* This PR creates a method .h2o.getBinary(), which will conduct a safe GET call to an H2O server in regards to getting binary data. This is useful for getting MOJOs.
* Also, this PR include updating the MOJO/h2oconfig test.

### CODE REVIEW

**Comment by navdeep-G** [comment]
A lot of issues with checking out the git hash. Running through a branch test now. cc @abal5

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by tomkraljevic** [comment]
Why create a getBinary function as opposed to always having the download be "binary"?
Is there ever a case where you want R to muck with the payload in unpredictable random R-ish ways?

**Comment by navdeep-G** [comment]
@tomkraljevic There was an issue where with getting the binary MOJO. It was only returning 1 byte by using .h2o.doSafeGET. This resolves that issue.

**Comment by tomkraljevic** [comment]
But instead of adding a new function with mostly duplicated code, what if you made the original function just download binary?

That what I (as the writer of the original function) would have expected it to do, anyway.

**Pull request closed without merging**
