### PR TITLE
[PUBDEV-5171] Aggregator to create mapping frame

### PR DESCRIPTION
**Pull request by mmalohlava**
Includes:
  - Unit test to check the length of mapping and a test to trigger mapping
  - Add a unit test to check for unique values of exemplarar in mapping file and the internal vector
  - Incorporated review comments
(cherry picked from commit 7cb025ddf240df366056d12434b95e8ff8ff240b)

### CODE REVIEW

**Comment by mmalohlava** [comment]
@michalkurka this is PR for rel-wheeler for PR #1902

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by michalkurka** [comment]
@mmalohlava @nikhilshekhar is it okay to merge this one?

**Comment by mmalohlava** [comment]
@michalkurka yes, @nikhilshekhar please just confirm that nothing changed in h2oai during weekend.

**Comment by nikhilshekhar** [comment]
@mmalohlava @michalkurka nothing changed in h2oai. It's okay to merge this PR.

**Comment by nikhilshekhar** [comment]
@mmalohlava @michalkurka. Yes, it's okay to merge this one. Nothing changed in h2oai that impacts this PR.

**Pull request merged**
