### PR TITLE
PUBDEV-8384: Explain floating point issue for POJOs

### PR DESCRIPTION
**Pull request by michalkurka**

### CODE REVIEW

**Review by g-eoj — APPROVED** [review]
Informative notebook! I don't see any issues.

**Comment by michalkurka** [comment]
thanks for reading through it @g-eoj

**Comment by neemah2o** [comment]
Thanks for creating this @michalkurka . If this becomes important for more users, it would be good to have a keyword option to change to doubles rather than use `rapids()`. Like `my_gbm.download_pojo(java_output_as_doubles=True)`

**Comment by michalkurka** [comment]
@neemah2o sure, we can expose it directly if there is demand for it - definitely; not a problem

**Pull request merged**
