### PR TITLE
Fix handling of unseen categorical levels PUBDEV-3865

### PR DESCRIPTION
**Pull request by arnocandel**
https://0xdata.atlassian.net/browse/PUBDEV-3865?filter=-3

### CODE REVIEW

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Comment by tomkraljevic** [comment]
Changing
    h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
means the tree visualizer code won't work anymore and needs updating, right?

**Comment by arnocandel** [comment]
Yes, likely. The bitset will be what it is, so won't need updates, but the < split might need extra logic.

**Comment by arnocandel** [comment]
@h2o-ops please test!!

**Comment by arnocandel** [comment]
runit_DRF_javapredict_30kcat.R needs to be looked at.

**Comment by arnocandel** [comment]
@h2o-ops test!

**Comment by arnocandel** [comment]
@h2o-ops test!

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Comment by arnocandel** [comment]
TODO: confirm tree viz

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by arnocandel** [comment]
We still need to add golden results in mojo-land.

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Pull request merged**
