### PR TITLE
PUBDEV-8535: Clarify feasible intervals for tweedie power in documentation

### PR DESCRIPTION
**Pull request by hannah-tillman**
For: [PUBDEV-8535](https://h2oai.atlassian.net/browse/PUBDEV-8535)

Added the values described in the attachment. Please let me know if anything else needs to be added.

### CODE REVIEW

**Review by ledell — CHANGES_REQUESTED** [review]
The values of 1 and 2 are not allowed, so I think we need to remove the second part completely.

There should be a similar update to the text on the GBM, Deep Learning and XGBoost pages.  I think there's the same issue where it suggests that 1 and 2 are ok values.

This is what happens when you try to use 1 or 2.

```r
> gbm <- h2o.gbm(y = 1, training_frame = as.h2o(iris), distribution = "tweedie", tweedie_power = 1)
  |================================================================| 100%

ERROR: Unexpected HTTP Status code: 412 Precondition Failed (url = http://localhost:54321/3/ModelBuilders/gbm)

water.exceptions.H2OModelBuilderIllegalArgumentException
 [1] "water.exceptions.H2OModelBuilderIllegalArgumentException: Illegal argument(s) for GBM model: GBM_model_R_1642627360306_1.  Details: ERRR on field: _tweedie_power: Tweedie power must be between 1 and 2 (exclusive).\n"
 [2] "    water.exceptions.H2OModelBuilderIllegalArgumentException.makeFromBuilder(H2OModelBuilderIllegalArgumentException.java:19)"                                                                                          
 [3] "    hex.ModelBuilder.trainModelOnH2ONode(ModelBuilder.java:334)"                                                                                                                                                        
 [4] "    water.api.ModelBuilderHandler.handle(ModelBuilderHandler.java:51)"                                                                                                                                                  
 [5] "    water.api.ModelBuilderHandler.handle(ModelBuilderHandler.java:16)"                                                                                                                                                  
 [6] "    water.api.RequestServer.serve(RequestServer.java:470)"                                                                                                                                                              
 [7] "    water.api.RequestServer.doGeneric(RequestServer.java:301)"                                                                                                                                                          
 [8] "    water.api.RequestServer.doPost(RequestServer.java:227)"                                                                                                                                                             
 [9] "    javax.servlet.http.HttpServlet.service(HttpServlet.java:707)"                                                                                                                                                       
[10] "    javax.servlet.http.HttpServlet.service(HttpServlet.java:790)"                                                                                                                                                       
[11] "    org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)"                                                                                                                                             
[12] "    org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)"                                                                                                                                         
[13] "    org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)"                                                                                                                                  
[14] "    org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)"                                                                                                                                 
[15] "    org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)"                                                                                                                                   
[16] "    org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)"                                                                                                                                          
[17] "    org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)"                                                                                                                                   
[18] "    org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)"                                                                                                                                  
[19] "    org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)"                                                                                                                                      
[20] "    org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)"                                                                                                                              
[21] "    org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)"                                                                                                                                    
[22] "    water.webserver.jetty9.Jetty9ServerAdapter$LoginHandler.handle(Jetty9ServerAdapter.java:130)"                                                                                                                       
[23] "    org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)"                                                                                                                              
[24] "    org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)"                                                                                                                                    
[25] "    org.eclipse.jetty.server.Server.handle(Server.java:531)"                                                                                                                                                            
[26] "    org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)"                                                                                                                                                  
[27] "    org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)"                                                                                                                                        
[28] "    org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)"                                                                                                                        
[29] "    org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)"                                                                                                                                                  
[30] "    org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)"                                                                                                                                               
[31] "    org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)"                                                                                                                             
[32] "    org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)"                                                                                                                           
[33] "    org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)"                                                                                                                          
[34] "    org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)"                                                                                                                                 
[35] "    org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)"                                                                                                           
[36] "    org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)"                                                                                                                                   
[37] "    org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)"                                                                                                                                    
[38] "    java.lang.Thread.run(Thread.java:748)"                                                                                                                                                                              

Error in .h2o.doSafeREST(h2oRestApiVersion = h2oRestApiVersion, urlSuffix = page,  : 
  

ERROR MESSAGE:

Illegal argument(s) for GBM model: GBM_model_R_1642627360306_1.  Details: ERRR on field: _tweedie_power: Tweedie power must be between 1 and 2 (exclusive).
```

**Comment by ledell** [comment]
In GLM, we have two related parameters, [`tweedie_link_power`](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/algo-params/tweedie_link_power.html) and [`tweedie_variance_power`](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/algo-params/tweedie_variance_power.html).  Maybe it would be helpful to discuss somewhere how these are all related?

**Comment by hannah-tillman** [comment]
@ledell Ah, sorry I misunderstood. I also tested ``tweedie_power = 0`` and got a similar error, so I removed that as well.

**Review by michalkurka — COMMENTED** [review]
Thank you @hannah-tillman

**Review by ledell — APPROVED** [review]
This is great, thanks!  @hannah-tillman Feel free to merge.

**Pull request merged**
