### PR TITLE
PUBDEV-3572: With some versions of the colorama package our Python bi…

### PR DESCRIPTION
**Pull request by rpeck**
…nding crashes.

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/364)

### CODE REVIEW

**Comment by rpeck** [comment]
https://0xdata.atlassian.net/browse/PUBDEV-3572

**Comment by h2o-ops** [comment]
Tests passed!

**Comment by arnocandel** [comment]
Can you please rebase your branch on top of master and force push? We'd like to only see commits relating to this PR.

**Comment by h2o-ops** [comment]
Tests passed!

**Pull request closed without merging**
