### PR TITLE
Update MOJO_QuickStart.md

### PR DESCRIPTION
**Pull request by poeticcapybara**
[FIX] Typo

### CODE REVIEW

**Comment by poeticcapybara** [comment]
I was in Windows and just noticed that the classpath separator is OS-dependent. Maybe a small note to alert for that difference would help newbies (like me) not to get stuck.

**Comment by angela0xdata** [comment]
Yes, that sounds correct. Perhaps a change similar to:

# Linux and OS X users
$ java -cp .:h2o-genmodel.jar main

# Windows users
$ java -cp .;h2o-genmodel.jar main

And thank you for finding this.

**Comment by poeticcapybara** [comment]
I just found it because after 10 years of Linux, I started my new job today and there's only Windows there XD

**Comment by angela0xdata** [comment]
Changes approved. Thanks again, and good luck with the new job!

**Pull request merged**
