### PR TITLE
Pubdev 4059

### PR DESCRIPTION
**Pull request by vitreuz**
Changes in client API for Steam R/Py clients

### CODE REVIEW

**Comment by st-pasha** [comment]
@mmalohlava 
I do not understand the purpose of this change (or the jira). The config file already supports connection arguments:
```
[init]
url = ...
proxy = ...
cluster_id = ...
verify_ssl_certificates = ...
cookies = ...
check_version = ...
```

**Comment by mmalohlava** [comment]
@st-pasha to support steam api:
```
cluster_config = steam.create_cluster(...)
h2o.connect(config = cluster_config)
```
however, cluster config can contain more steam-specific information, we would like to make sure that h2o picks only information for connection. Hence, we introduced a dedicated field which provides them.

**Comment by st-pasha** [comment]
Ah, so it's a different kind of config. Ok then...

Looks like `steam.create_cluster(...)` returns some kind of dictionary, which is not documented anywhere. Why not create a `SteamConfig` object (containing an `H2OConnectionConf` instance), which would be able to provide all those options more reliably?

**Comment by mmalohlava** [comment]
If you mean `SteamConfig` in H2O, then i would say no, h2o does not know nothing about steam ;-)

**Comment by mmalohlava** [comment]
Furthermore, we do not want to introduce dependency on H2O in steam. I would keep interface by convention.
H2O requires interface (structure of `config` variable), steam satisfies the structure.

**Pull request merged**
