### PR TITLE
PUBDEV-3488: Don't allow assigning to a categorical column if domain differs

### PR DESCRIPTION
**Pull request by michalkurka**
Don't allow assigning to a categorical column with a different domain than the source column

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/292)

### CODE REVIEW

**Comment by michalkurka** [comment]
@mmalohlava currently it just "randomly" re-assigns the values in the categorical column, the purpose of this pull request is to make sure that such error doesn't happen.

Re-mapping can be done. I don't know if this is a use case people have but I am happy to implement it if you think it is worth it.

**Comment by st-pasha** [comment]
@mmalohlava Current functionality (before this PR) is to assign categorical columns numerically, which could lead to all sorts of undesired behavior, and cannot produce any meaningful outcome. You may even put a frame into invalid state by inserting categorical values that do not map to anything in the domain. https://0xdata.atlassian.net/browse/PUBDEV-3488

@michalkurka When people think about categorical columns, they think about their values as strings. So it would be good to enable automatic expansion of the domain as you insert new values there. However this could be considered a new feature for a separate PR. In this case the assignment of a string to a categorical vec should also be enabled. Also a user would think it's a bug if he can't assign from a vec with domain ["cat", "mouse"] into a vec with domain ["mouse", "vec"]

**Comment by mmalohlava** [comment]
@michalkurka thanks, i was just curious about motivation behind it.

**Comment by michalkurka** [comment]
@st-pasha In a data frame in R you would first need to convert the factor levels to the same factor type to be able to assign a value to the column. R users are used to all kinds of obstacles :)

If we think of categorical just as of strings than the behavior can be quite flexible and we can even implement domain expansion.

**Comment by vpatryshev** [comment]
Like it!

**Pull request merged**
