### PR TITLE
PUBDEV-6014: set json request lenient for java binding otherwise NaN is not parsed

### PR DESCRIPTION
**Pull request by AlexKroeker**
It occured a MalformedJsonException when using the Java bindings. reason is that JSON forbids NaN and infinities. therefore Gson has to be configured to allow that.

### CODE REVIEW

**Comment by jabana** [comment]
Stackoverflow bug description: https://stackoverflow.com/questions/52937340/using-h2oapi-java-bindings-to-retrieve-h2o-frame-summary-ends-with-malformedjson/52964593

**Comment by jabana** [comment]
okay, I added a test to examine this behaivior.

**Comment by michalkurka** [comment]
thanks!

**Comment by michalkurka** [comment]
Mr. Jenkins, please test!

**Comment by michalkurka** [comment]
@jabana we are still seeing some tests failures on this PR - it might be caused by our infrastructure, right now we are target release 3.22.0.2 for this fix

I think your fixes look good but we need to make sure nothing breaks in the test suite. Thanks for your patience.

**Comment by joostvanbruggen** [comment]
When will this fix be merged? Thanks

**Pull request closed without merging**
