### PR TITLE
word2vec, transform sentences to vectors by averaging the word-vectors

### PR DESCRIPTION
**Pull request by michalkurka**
This PR adds support for "sentence/paragraph vector embedding" by averaging the words of the input sequence.

This can be further extended in the future by weighting using TF-IDF.

### CODE REVIEW

**Comment by michalkurka** [comment]
@h2o-ops please test!

**Comment by mdymczyk** [comment]
@michalkurka were you basing this impl on any whitepaper/other framework? I was looking into this sort of thing at my previous job and simple averaging didn't seem like a viable option. This was because you can get the same average using completely different paragraphs.

For example 2 simple paragraphs with 2 words each, first has a word from the lower left corner of the embedding space and the upper right - the average will give you the center point of the embedding space. The second paragraph has the first word from the upper left corner and lower right - average again gives you the center point and when comparing the averages both paragraphs will look identical.

**Comment by michalkurka** [comment]
@mdymczyk Thank you for you response!

Averaging word vectors is a frequently used method due to its simplicity. It can yield sub-optimal results depending on the use case. It is probably not the best option for sentiment analysis and use cases where order of the word matters. It could be okay for other use cases. I'm aware of one our customer that is using averaging and where it seems to perform well.

I didn't use any particular paper to implement it. I know about Paragraph Vectors/doc2vec, it performs better than simple averaging (although not as good as the original paper suggests - the original paper was wrong). Doc2vec would be great future addition to H2O, it is not much more complex than word2vec.

For now I want to add averaging for customers convenience and weighted averaging using TF-IDF in one of the next steps.

This "poster" shows very high level comparison of different methods of paragraph embeddings: http://jxieeducation.com/static/research/documentembedding_poster.pdf

**Comment by michalkurka** [comment]
@h2o-ops please test!

**Comment by michalkurka** [comment]
@h2o-ops please test!

**Comment by michalkurka** [comment]
@h2o-ops please test!

**Comment by michalkurka** [comment]
Rebased.

**Comment by michalkurka** [comment]
@h2o-ops please test!

**Pull request merged**
