### PR TITLE
word2vec, better reporting of progress of computation

### PR DESCRIPTION
**Pull request by michalkurka**

### CODE REVIEW

**Comment by michalkurka** [comment]
@h2o-ops please test

**Comment by michalkurka** [comment]
@h2o-ops please test!

**Comment by michalkurka** [comment]
@h2o-ops please test!

**Comment by michalkurka** [comment]
@st-pasha I did check the progress bar. It behaves better but it is still not perfect, there are still "jumps" when two or more chunks finish at the same time, I think this is a worthy improvement anyway - I will think about smoothening the progress bar behavior for the next release

**Comment by st-pasha** [comment]
@michalkurka You probably referring to R; there shouldn't be any jumps in python's progress bar.

**Pull request merged**
