### PR TITLE
[BUILD] comments updated

### PR DESCRIPTION
**Pull request by mmalohlava**
Testing PR

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/73)

### CODE REVIEW

**Comment by abal5** [comment]
Can one of the admins verify this patch?

**Comment by arnocandel** [comment]
Approved.

**Comment by mmalohlava** [comment]
Thx! I am going to merge it!

**Comment by st-pasha** [comment]
Why was this merged??? 👀

**Comment by mmalohlava** [comment]
I wanted to show the behavior of merge during our discussion.

**Pull request merged**
