### PR TITLE
Make a new recipe for frame creation

### PR DESCRIPTION
**Pull request by st-pasha**
This recipe is similar to the original one, only it allows more fine-tuned control over the frame being created.

Also part of the functionality of the `OriginalCreateFrameRecipe` was moved out into the base `CreateFrameRecipe` class.

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/555)

### CODE REVIEW

**Comment by st-pasha** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
LGTM. Lets wait for the tests.

**Comment by st-pasha** [comment]
@h2o-ops please test!

**Pull request merged**
