### PR TITLE
add Word2Vec algo to Flow WIP

### PR DESCRIPTION
**Pull request by micahstubbs**
This PR adds support for the new `Word2Vec` algo to Flow 🎉 

https://github.com/h2oai/drift/commit/ad4f7bb3ee18ce4f2651582c9682b7cb056dfce7

cc @michalkurka 

screen shot 2017-02-14 at 3 58 50 pm

### CODE REVIEW

**Comment by micahstubbs** [comment]
think that there is still an issue with the model metrics. will add a commit to fix that

**Comment by micahstubbs** [comment]
this is WIP for now - waiting for a more general solution that supports showing model outputs without specifying the algo name in `_schemaHacks`

**Comment by michalkurka** [comment]
@micahstubbs would the more general solution be available soon? or is there a reason why not to fix this for word2vec now and adopt the more general solution later?

**Comment by micahstubbs** [comment]
@michalkurka good question.  this branch includes changes that cause two other minor regression bugs - other custom models don't appear by default and error messages from the h2o-3 backend are logged to the browser console rather than displayed in the Flow UI.  @mmalohlava wanted to fix these other regressions first. 

hopefully we can have the general fix in a day or two, so that waiting for Word2Vec isn't too painful.  😅

**Comment by michalkurka** [comment]
@micahstubbs is this PR still needed?

**Comment by micahstubbs** [comment]
@michalkurka likely not. will close this PR for now, with the expectation that future versions of Flow will continue to support new custom algos without knowing the algo's name.

**Pull request closed without merging**
