### PR TITLE
PUBDEV-8649: Replace class() with inherits() in R

### PR DESCRIPTION
**Pull request by ledell**
https://h2oai.atlassian.net/browse/PUBDEV-8649

### CODE REVIEW

**Review by sebhrusen — APPROVED** [review]
I thought there would be more :)
thx @ledell

**Comment by ledell** [comment]
@sebhrusen There might be more in other files, but I think the CRAN check is only picking up regex for `if (class(object) == "string")` so I made the minimal number of changes required for this PR.

**Comment by tomasfryda** [comment]
I tried the `BiocCheck` and it found 2 more issues:
```
   * WARNING: Avoid class membership checks with class() / is() and == / !=; Use is(x,
      'class') for S4 classes
      Found in files:
        automl.R (line 522, column 77)
        frame.R (line 45, column 67)
```

**Comment by michalkurka** [comment]
@ledell @tomasfryda I am merging this because it passes tests and we want to see build results on all R versions sooner than later - please make a follow up PR for the additional changes

**Comment by ledell** [comment]
Thanks @michalkurka.

**Pull request merged**
