### PR TITLE
PUBDEV-4496: Change project to project_name in AutoML backend

### PR DESCRIPTION
**Pull request by navdeep-G**
* We use project_name in the AutoML R/Py APIs, so we should change the name on the backend (Java) as well for consistency. The R and Python APIs will also need a small change – they send project_name to the build_control$project / build_control['project'] , so that will require a small edit.

### CODE REVIEW

**Comment by ledell** [comment]
@navdeep-G Looks good, but do you know why the junit is failing?

**Comment by navdeep-G** [comment]
@ledell Couldn't start a cloud I think. Retrying.

**Comment by jakubhava** [comment]
@navdeep-G can you pls rebase on master and merge if test are passing ?

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Pull request merged**
