### PR TITLE
PUBDEV-7998: Fixed ICE plots keys issue

### PR DESCRIPTION
**Pull request by sergeiten**
As explained in the ticket there is no keys for ICE plot:

https://h2oai.atlassian.net/browse/PUBDEV-7998

Not sure if I fixed this in right way but it's working for me. Made it same as PDP plots.

Screen Shot 2021-02-08 at 10 29 27

### CODE REVIEW

**Comment by michalkurka** [comment]
thank you for the contribution @sergeiten!

**Review by tomasfryda — CHANGES_REQUESTED** [review]
Thank you for investigating and reporting this issue and for creating this PR!

 I believe a proper fix would be replacing `result["ice"]["plots"][columns][model]` with `result["ice"]["plots"][columns][model.model_id]` (lines 2148, 2161, and 2163). This way we will plot one ICE plot for each column and model.

**Comment by sergeiten** [comment]
I have added model id. I believe I should use "column" instead of "columns" so

Instead of:
```
result["ice"]["plots"][columns][model.model_id]
```

I have added:
```
result["ice"]["plots"][column][model.model_id]
```

**Comment by tomasfryda** [comment]
Good catch @sergeiten. Thank you!

**Review by tomasfryda — APPROVED** [review]

**Comment by ledell** [comment]
Thank you, @sergeiten!

**Pull request merged**
