### PR TITLE
simplify install string, partially closes PUBDEV-2963

### PR DESCRIPTION
**Pull request by jangorecki**
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/429)

### CODE REVIEW

**Comment by abal5** [comment]
@h2o-ops please test

**Comment by navdeep-G** [comment]
@ledell Thoughts on this? I like it.

**Comment by ledell** [comment]
Looks good to me, let's wait until the checks pass, then merge.

**Comment by jangorecki** [comment]
@h2o-ops please test

**Comment by jangorecki** [comment]
@h2o-ops please test

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by abal5** [comment]
@h2o-ops please test

**Pull request merged**
