### PR TITLE
PUBDEV-5780 Adds support for importing Teradata using JDBC interface

### PR DESCRIPTION
**Pull request by grigory93**
https://0xdata.atlassian.net/browse/PUBDEV-5780
Added support for Teradata database; 
refactored SQL generation code;
added tests for SQL generation;

### CODE REVIEW

**Comment by michalkurka** [comment]
thanks @grigory93 

CC: @seb-h2o you are both changing the same code base

**Comment by seb-h2o** [comment]
looks good.

besides no conflicts with https://github.com/h2oai/h2o-3/pull/2665, just small one with https://github.com/h2oai/h2o-3/pull/2667 due to encapsulation of row/columns information.

**Comment by michalkurka** [comment]
@seb-h2o should we merge this one? what is the status of your PR?

**Comment by seb-h2o** [comment]
please go, merge this one, there's no major conflict with #2665.
regarding mine, please see new comments in the PR

**Comment by michalkurka** [comment]
@seb-h2o ok, thanks for this gesture, appreciated

**Pull request merged**
