### PR TITLE
Meaningful reporting when disk is full (it was totally obscure before)

### PR DESCRIPTION
**Pull request by vpatryshev**
Saw a mystic error, turned out it's just disk full.

If you see something, say something.

### CODE REVIEW

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Pull request closed without merging**
