### PR TITLE
[PUBDEV-4151] FillNA, fill missing values sequentially for time series

### PR DESCRIPTION
**Pull request by mklechan**
PUBDEV-4251 first working version with test

PUBDEV-4251 junit test

PUBDEV-4151 wip bug fixes

PUBDEV-4151 wip bug fixes

PUBDEV-4151 fixed bugs with fillna across chunk boundaries

PUBDEV-4151 R client for fillna

PUBDEV-4151 fillna along rows

### CODE REVIEW

**Comment by navdeep-G** [comment]
LGTM. Lets rebase and let the tests run.

**Comment by mklechan** [comment]
Need to make R api take axis=1 to mean fill along the row, and axis=2 to fill down the columns according to @NidhiMehta 's recommendation

**Comment by mklechan** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Pull request merged**
