### PR TITLE
PUBDEV-5164: Add more info to checkpoint parameter in docs

### PR DESCRIPTION
**Pull request by angela0xdata**
- Added more information about how checkpointing works include a couple of scenarios.
- Updated list of parameters not allowed with checkpointing in Deep Learning

### CODE REVIEW

**Comment by ledell** [comment]
@angela0xdata This is great so far!  

I wonder if @meganjkurka and/or @laurendiperna could help add a bit more information about how checkpointing actually works for each algo?  e.g. RF trains additional trees on either same training frame, or a new data frame.  GBM trains additional trees on same training frame, but if you use a new training frame, it's a bit weird and technically works, but not really recommended.  DNN and GLM are more straight-forward (adding epochs/iterations).

**Comment by angela0xdata** [comment]
@ledell thanks for the clarification. I thought the only difference was in the parameters. I'll see if I can get more info from @meganjkurka and @laurendiperna.

**Comment by angela0xdata** [comment]
Note that examples are currently Python only. Still need to include R examples.

**Comment by angela0xdata** [comment]
Will merge this pull request after these minor changes and add more info as it becomes available. For now, we have examples and descriptions indicating that checkpointing in DL and RF can be run on existing training data and on new data. GBM example runs on existing data (though that particular example did seem to work with new data).

**Pull request merged**
