### PR TITLE
[PUBDEV-5500] Fix warning messages in automl

### PR DESCRIPTION
**Pull request by jakubhava**
Tiny change. It was confusing as I was looking for column `predictionis` however the column was `prediction`

### CODE REVIEW

**Comment by michalkurka** [comment]
Good change @jakubhava! Maybe we can follow the example set by Model.adaptTestForTrain and use quotes to clearly mark the column names?

This is how adaptTestForTrain reports issues:

              throw new IllegalArgumentException("Test/Validation dataset has a non-categorical column '"+names[i]+"' which is categorical in the training data");

**Comment by navdeep-G** [comment]
Changes LGTM. @michalkurka suggestion is a good one, too.

**Comment by jakubhava** [comment]
@michalkurka agree, will do this change

**Comment by jakubhava** [comment]
done

**Pull request merged**
