### PR TITLE
PUBDEV-5083: Updated changes.md for 3.16.0.1

### PR DESCRIPTION
**Pull request by angela0xdata**

### CODE REVIEW

**Comment by ledell** [comment]
@angela0xdata I moved around some tickets and updated a few ticket descriptions (mostly SE and AutoML).

**Comment by angela0xdata** [comment]
@h2o-ops please test!

**Comment by angela0xdata** [comment]
@h2o-ops please test!

**Comment by ledell** [comment]
@angela0xdata can we merge this now?

**Comment by angela0xdata** [comment]
The Changes.md file was added to master with commit 1875baf75b8921596c12c42a9476dc13befbd72c

**Pull request closed without merging**
