### PR TITLE
Test for factoring operations.

### PR DESCRIPTION
**Pull request by vpatryshev**
Also, frame.asfactor() fixed, so
a) more than one column is factored and the result type set
b) column type checked before passing to the server

### CODE REVIEW

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
The change needs more effort since the tests are failing:
```
h2o.exceptions.H2OValueError: Only 'int' or 'string' are allowed for asfactor(), got IsDepDelayed:enum 
```

**Comment by jakubhava** [comment]
Is this change planned to be in the next h2o release ? Would be great to make new Sparkling Water release based on h2o with this fix inside, but no rush if's too much of work.

**Comment by vpatryshev** [comment]
So, the other tests are all passing now. Trying to rerun failing tests on build machine.

**Pull request merged**
