### PR TITLE
Fix security vulnerabilities in `h2o3 3.46.0.2 87` 

### PR DESCRIPTION
**Pull request by poornaSavindi**
fixes [PRISMA-2023-0067](https://github.com/FasterXML/jackson-core/pull/827)

### CODE REVIEW

**Comment by rsujeevan** [comment]
I noticed high vulnerability from `com.fasterxml.jackson.core_jackson-core` 
image

Screenshot 2024-06-10 at 10 51 32 AM

**Comment by rsujeevan** [comment]
✅  I just noticed that the `com.fasterxml.jackson.core_jackson-core` library has been updated to version `2.15.0`. 

I noticed that we are using version 2.16.0 in the `jdbc.jar`. Can we update to a newer version?

**Comment by rsujeevan** [comment]
@poornaSavindi @this, do guys think we can get this for RC3?
I believe h2o3-3.46.0.3 has been released. Is it possible to incorporate these changes on top of 3.46.0.3?

**Comment by rsujeevan** [comment]
@poornaSavindi 
Can we incorporate changes from 3.46.0.3 release?

**Comment by this** [comment]
@poornaSavindi @rsujeevan PR https://github.com/h2oai/h2o-3/pull/16169 has been merged. So hopefully there will be a new release from the v3.46.0.x series. And we can use that. @poornaSavindi please followup with the h2o-3 team about the new release.

**Comment by poornaSavindi** [comment]
Covered in https://github.com/h2oai/driverlessai-recipes/pull/206

**Pull request closed without merging**
