### PR TITLE
Removed obsolete makefiles

### PR DESCRIPTION
**Pull request by pkozelka**
For now, I removed only those last updated by Cliff Click.
None of these Makefiles is working, and they are all very likely unused.

It is good to remove them because:

- every unused file present in the codebase is evil
- at least for the top-level makefile, it can be used to conveniently store commands for cleanup, build, various test tasks etc. which are often used during development; so it is good to first get rid of the original one

Remaining Makefiles are following:

```
ec2/Makefile
h2o-docs/src/product/Makefile
h2o-docs/src/product/architecture/src/Makefile
h2o-docs/src/booklets/v2_2015/source/Makefile
h2o-docs-theme/demo_docs/Makefile
h2o-py/docs/Makefile
h2o-web/Makefile
```

because I was not totally sure that they can be deleted.

### CODE REVIEW

**Comment by jakubhava** [comment]
Ideally, every build-related action should be stored in Gradle to have one source of the truth for the build

**Comment by angela0xdata** [comment]
I use h2o-docs/src/product/Makefile to build docs locally as I'm making updates. There is currently no comparable ./gradlew command for building these docs (that I'm aware of).

**Comment by angela0xdata** [comment]
Oh, I see that is the list of makefiles that have not been removed.

**Comment by jakubhava** [comment]
Also it would be good to port sphinx documentation build to Gradle as well. Sparkling Water already does that and docs can be build as `./gradlew site` so we can inspire there. CC: @michal-raska 

https://github.com/h2oai/sparkling-water/blob/master/doc/build.gradle

**Pull request merged**
