### PR TITLE
Remove data file from h2o-3 root

### PR DESCRIPTION
**Pull request by jakubhava**

### CODE REVIEW

**Comment by jakubhava** [comment]
@wendycwong just found out this file on repo and it was last updated by you. Do we need it here or can we delete it?

**Comment by michalkurka** [comment]
@jakubhava this file is used in JUnit tests, did you also upload it to S3? The tests failed because it was missing

**Comment by jakubhava** [comment]
I haven't done anything about this, just removed this file in repo as this file was located suspiciously in root. I see that this file is actually being used

**Comment by michalkurka** [comment]
We can remove it from Git and put to S3 instead. That would be much cleaner than having this random file in Git.

**Pull request closed without merging**
