### PR TITLE
PUBDEV-6335: GBM monotonicity constraints only work for gaussian distrib

### PR DESCRIPTION
**Pull request by michalkurka**

### CODE REVIEW

**Comment by angela0xdata** [comment]
@michalkurka what about XGBoost?

**Comment by michalkurka** [comment]
XGBoost is not restricted like that

**Comment by angela0xdata** [comment]
okay, thanks for the info!

**Comment by Mathieu-Jacob** [comment]
Can you explain why it is restricted to gaussian only? Is it planned to deploy it for other distributions also?

**Comment by Mathieu-Jacob** [comment]
I came across this link stating monotonic constraints are for regression only: https://0xdata.atlassian.net/browse/PUBDEV-6335

Is the restriction on regression only (which would allow other distributions like tweedie)? or on the distribution?

**Comment by michalkurka** [comment]
It is only allowed for Gaussian in this PR, Bernoulli is implemented in another PR

The reason why it is done this way is that it needs custom implementation for each distribution. We can add other later but at this point in time only Gaussian and Bernoulli will be supported

**Pull request merged**
