### PR TITLE
Generate consistent float values for R API

### PR DESCRIPTION
**Pull request by surekhajadhwani**
When we run `./gradlew build`, it auto-generates R API but based on the machine architecture, the precision of float values (especially, Math.MAX_VALUE) is different. This was discussed [here](https://h2oai.slack.com/archives/dev/p1482018838000511). In order to make it consistent, we will be restricting upto a precision of 10. This is also consistent with Python API [change](https://github.com/h2oai/h2o-3/pull/490/files)

### CODE REVIEW

**Comment by ledell** [comment]
@surekhajadhwani Why did you change some default values that are numeric/real-valued to integers?  E.g. `clip_gradient` was 10.0 and now it's 10.  Do these updates match with the Python API as well?

**Comment by surekhajadhwani** [comment]
@ledell All real numbers are now formatted to use precision of 10 digits. This causes 10.0 to be formatted as 10. Python API also uses same formatting for real numbers.

**Comment by jangorecki** [comment]
@ledell 10 is still numerical, at least in R, `is.integer(10)` will return false. `.0` in numeric is redundant IMO (at in R).

**Comment by ledell** [comment]
@surekhajadhwani @jangorecki Ok, that sounds good to me.

**Comment by surekhajadhwani** [comment]
@h2o-ops please test!

**Comment by surekhajadhwani** [comment]
Individual PR_runit_small succeeded. Logs are present at: http://172.17.2.151:8080/view/Branch-PR_Test/job/branch_runit_small/67/console.

**Pull request merged**
