### PR TITLE
PUBDEV-3726: added model.coef_std() to python and h2o.coef_std() to R…

### PR DESCRIPTION
**Pull request by laurendiperna**
…, fixed a few typos in doc help string

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/538)

### CODE REVIEW

**Comment by laurendiperna** [comment]
@h2o-ops please test

**Comment by Mistobaan** [comment]
Tests are missing. Docstring does not really explain what this function does, `standardized coefficients` is not really self explanatory.

**Comment by ledell** [comment]
@laurendiperna Please update the docstrings for these functions.

**Comment by laurendiperna** [comment]
@ledell @Mistobaan there is a bug in H2O Python's `model.coef()` and `model.coef_norm()`, which I used as a template to create the method `model.coef_std()` (this bug is not an issue in `R`). The bug is the result of hard coding the index from which a column of the `glm: coefficients table` is extracted. Once this bug is fixed `model.coef_norm()` will be the same as `model.coef_std()`. As a result I am going to close this PR and create a new one that fixes the bug and adds a test to catch the next time someone updates the `glm: coefficients table`. As for the doc strings, I'll update what we currently have for `model.coef()`, which is currently is "Return the coefficients for this model" and `model.coef_std()`, which currently is "Return the normalized coefficients" with a bit more detail.

**Pull request closed without merging**
