### PR TITLE
Github README update

### PR DESCRIPTION
**Pull request by johnygomez**
I had some troubles with building H2O and I noticed (correct me if I'm wrong), that building requires a properly set up Python with packages like `requests`. Maybe it would be suitable, if user was explicitly warned about that in the beginning, even before first code block containing the `./gradlew build`.
Thanks :)

### CODE REVIEW

**Comment by michalkurka** [comment]
@angela0xdata please take a look as well

**Comment by angela0xdata** [comment]
The text in the changes looks fine, but I’m a little confused. Is it normal that Python should be required in order to build H2O? 
Also, I’ve never seen “grip” before. (It’s not listed on h2o.ai/download > Install in Python tab, and it’s not listed in the https://github.com/h2oai/h2o-3/blob/master/h2o-py/conda/h2o/meta.yaml file.) Can you verify this with Pasha? I’ll have to update the user guide with this addition.

**Comment by michalkurka** [comment]
@angela0xdata good catch with the grip package, I didn't notice it. Thank you!

BTW the "grip" package was listed in the readme before but it might be a dependency that is no longer needed (need to check this!)

Python is needed to build H2O to generate the h2o-bindings.

**Comment by angela0xdata** [comment]
Is there a specific version or minimum version of Python that is required in order to generate the h2o-bindings?

**Pull request merged**
