### PR TITLE
PUBDEV-8131 Fixing typo of test name 'runit_GBM_iris_multiomial_auc.R' and merge it with the existing one

### PR DESCRIPTION
**Pull request by maurever**
Merge runit_GBM_iris_multiomial_auc.R and runit_GBM_iris_multinomial_auc.R

JIRA:
https://h2oai.atlassian.net/jira/software/c/projects/PUBDEV/issues/PUBDEV-8131
https://h2oai.atlassian.net/jira/software/c/projects/PUBDEV/issues/PUBDEV-8136

### CODE REVIEW

**Review by michalkurka — APPROVED** [review]

**Comment by maurever** [comment]
> @maurever PR looks good but maybe the PR title is misleading?

@michalkurka, what title do you suggest? 

This title is exact but it is too long:  Fix typo in runit_GBM_iris_multiomial_auc.R and merge it with runit_GBM_iris_multinomial_auc.R

**Comment by michalkurka** [comment]
I do not suggest anything, I was just confused by "Fix typo in runit_GBM_iris_multiomial_auc.R" - I did not know what typo is being fixed in that test.

**Comment by maurever** [comment]
> I do not suggest anything, I was just confused by "Fix typo in runit_GBM_iris_multiomial_auc.R" - I did not know what typo is being fixed in that test.

@michalkurka, is it know better?

**Comment by michalkurka** [comment]
@maurever now I get it - the typo was in the filename, I didn't notice it was renamed - thanks for clarifying

**Pull request merged**
