### PR TITLE
[HOTFIX] :fire: Remove HTTP protocol restriction from S3 configuration.

### PR DESCRIPTION
**Pull request by mmalohlava**
Summary: Make it configurable via system variable.

Test Plan: manual

Reviewers: pasha, arno

Differential Revision: https://test-4btqyg52txp2.phacility.com/D5

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/69)

### CODE REVIEW

**Comment by abal5** [comment]
Currently testing this PR please wait for response from the team.

**Comment by abal5** [comment]
Can one of the admins verify this patch?

**Comment by abal5** [comment]
Currently testing this PR please wait for response from the team.

**Comment by abal5** [comment]
Currently testing this PR please wait for response from the team.

**Comment by mmalohlava** [comment]
Fixed in PUBDEV-3210 : https://0xdata.atlassian.net/browse/PUBDEV-3210

**Pull request merged**
