### PR TITLE
Fix PUBDEV-3631 and add a JUnit: overwrite_with_best_model fails duri…

### PR DESCRIPTION
**Pull request by arnocandel**
…ng checkpoint restart.

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/439)

### CODE REVIEW

**Comment by abal5** [comment]
@h2o-ops please test

**Comment by abal5** [comment]
@h2o-ops please test

**Comment by arnocandel** [comment]
@h2o-ops please test

**Comment by abal5** [comment]
@h2o-ops please test

**Comment by abal5** [comment]
@h2o-ops please test

**Pull request merged**
