### PR TITLE
PUBDEV-7980 : Fix typo interaction_constraints

### PR DESCRIPTION
**Pull request by neemah2o**
Docs example show interaction_constraints for GBM, but it is only supported for XGBoost

### CODE REVIEW

**Review by maurever — APPROVED** [review]
Good catch @neemah2o! LGTM, thank you.

**Review by hannah-tillman — APPROVED** [review]
Good catch! Thanks!

**Review by michalkurka — CHANGES_REQUESTED** [review]
please also rename the returned models, right now it says "prostate_gbm"

**Comment by neemah2o** [comment]
Done - renamed returned models

**Review by michalkurka — APPROVED** [review]
Thank you @neemah2o!

**Pull request merged**
