### PR TITLE
PUBDEV-3700: Add RMSE, MAE, RMSLE, and lift_top_group as stopping metrics

### PR DESCRIPTION
**Pull request by navdeep-G**
* This PR will add RMSE, MAE, RMSLE, and lift_top_group as stopping metrics for all algos.
* The Python bindings were generated upon build while the R bindings for GBM and Random Forest were manually added.

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/515)

### CODE REVIEW

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by ledell** [comment]
@navdeep-G What happens when you pass in `stopping_criterion = "mae"` instead of `"MAE"`?  I think we should add support for lower-case in this same PR.

**Comment by navdeep-G** [comment]
@ledell Just pushed a change for that. Now a user can pass in `MAE,RMSE,RMSLE,AUC,MSE` or their lower case counterpart. Also, the autogen will pick up all cases. Thats why you'll notice we have `MAE,mae` in the list of acceptable stopping metrics.

**Comment by navdeep-G** [comment]
@ledell Not supported right now. We would need to check that on the client side. Otherwise the auto gen will make the output quite odd. For example, if I was to add `AUC,auc` in the backend then the Python binding would have `auc,auc` as acceptable input on the client side.This is because Python is case-insensitive. Will make the change as such.

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
I feel this PR is good as is considering how our R API is set up. Once we get auto-gen R bindings, then we can change this to allow lowercase and uppercase.

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by ledell** [comment]
@navdeep-G I agree.  As long as we plan to continue to support uppercase in the future, then there is no disadvantage to adding this now (vs waiting until later after the auto-gen bindings).  I think it's good to merge after the checks pass.

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
This PR looks good to all parties? @arnocandel @ledell

**Comment by navdeep-G** [comment]
@h2o-ops please test

**Pull request merged**
