### PR TITLE
:fire: [HOTFIX]: Store MOJO in tmp directory then remove directory on exit

### PR DESCRIPTION
**Pull request by navdeep-G**

### CODE REVIEW

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by jangorecki** [comment]
fyi, as cran is failed due to PUBDEV-3818

**Pull request closed without merging**
