### PR TITLE
PUBDEV-5440 Fix runit_automl_args.R test by always building at least 2 models

### PR DESCRIPTION
**Pull request by navdeep-G**

### CODE REVIEW

**Comment by navdeep-G** [comment]
@ledell I can make that change to this test. We can do the other change in another PR. Lets first isolate the known problem.

**Comment by navdeep-G** [comment]
@ledell Made the necessary changes to the test. Lets see how it goes.

**Comment by ledell** [comment]
@navdeep-G Ideally, we'd change all the tests to `max_models` here (there are several still using `max_runtime_secs`, just to simplify things and ensure against NPEs in the future, or was there some reason you're keeping those in?

**Comment by navdeep-G** [comment]
This specific error is not due to an NPE. That’s why I’m keeping the others the same in this PR. Not to say we can’t update in others but we just haven’t identified what the cause of the other intermittent NPEs are.

**Pull request merged**
