### PR TITLE
use drift flow.js bundle to add new top-level Plot menu to Flow

### PR DESCRIPTION
**Pull request by micahstubbs**
This PR uses the [drift](https://github.com/micahstubbs/drift) flow.js bundle to add a new top-level Plot menu to Flow

screen shot 2017-02-06 at 10 06 44 pm

### CODE REVIEW

**Comment by micahstubbs** [comment]
@abal5 could you review this one?

**Comment by micahstubbs** [comment]
a prerequisite for https://github.com/h2oai/h2o-3/pull/786

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by micahstubbs** [comment]
@h2o-ops please test!

**Comment by micahstubbs** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
Was this tested manually?

**Comment by mmalohlava** [comment]
^ CC: @abal5 - we need to make sure that:
 1) people are able to build H2O
 2) the menu is visible

**Comment by micahstubbs** [comment]
@mmalohlava I tested the build manually, happy to walk @abal5 through it as well

**Comment by mmalohlava** [comment]
👍 thank you @micahstubbs

**Comment by mmalohlava** [comment]
image
So far this is output from my local build...

**Comment by micahstubbs** [comment]
@mmalohlava found and fixed this one, will try to make a new PR

**Comment by micahstubbs** [comment]
^^ new PR https://github.com/h2oai/h2o-3/pull/791 with the patch

**Pull request merged**
