### PR TITLE
Update flow remove duplicate Google Analytics script HEXDEV-686

### PR DESCRIPTION
**Pull request by micahstubbs**
This PR updates Flow to remove the duplicate Google Analytics script and fix the broken `headless.coffee` phantomJS test. 

cc @abal5 @justinloyola 

related commits and PRs:
https://github.com/h2oai/h2o-flow/commit/2976e81cba7f8c57f6b2d8802566a62565ad12ed
https://github.com/h2oai/h2o-flow/commit/82e48f3c779120c2e3a1bc45359bcefd4bd50aa9
https://github.com/micahstubbs/drift/pull/124

### CODE REVIEW

**Comment by micahstubbs** [comment]
@abal5 please review and merge 😄

**Comment by micahstubbs** [comment]
restored three functions to the global `window.flow` object that were inadvertently removed in an earlier refactoring https://github.com/micahstubbs/drift/pull/125/files

the `headless.coffee` phantomJS test should have fewer errors now

**Comment by tomkraljevic** [comment]
Please explain why you want to remove the google analytics?

**Comment by vpatryshev** [comment]
still failing...

**Comment by micahstubbs** [comment]
@tomkraljevic the idea is to remove Google Analytics in order silence an outdated failing test, update the test,  then possibly restore Google Analytics later. just the messenger here,  can understand why we might want to instead just fix the outdated test.

**Comment by micahstubbs** [comment]
@tomkraljevic wants to keep Google Analytics in Flow. will close this PR for now, and instead invest some time in improving the phantomJS smoke test. 

cc @abal5 @justinloyola

**Comment by justinloyola** [comment]
Fixing the smoke test has to be done regardless. Removing the Google Analytics tag here would still be necessary since Google Analytics is being added twice - once from this script tag and once from Google Tag Manager.

**Comment by micahstubbs** [comment]
@justinloyola good point. I'll re-open and update the title of the PR then.

**Comment by abal5** [comment]
Also a good idea to add the Jira ticket related in the title so it can be linked dynamically e.g. PUBDEV-1234

**Comment by mmalohlava** [comment]
@tomkraljevic see explanation of @justinloyola - there is already GA inside flow

**Comment by abal5** [comment]
Junit failure unrelated to change

**Comment by vpatryshev** [comment]
I'll look into these other cases.
We are not done yet.
But it was a big step for humanity.

Thanks,
-Vlad

**Pull request merged**
