### PR TITLE
[PUBDEV-3912] Context path for connecting from py client through steam proxy

### PR DESCRIPTION
**Pull request by CreatureDev**

### CODE REVIEW

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@navdeep-G please have a look at R part of this PR. Thx!

**Comment by mmalohlava** [comment]
based on feedback in #api-channel, we will need to make a few changes

**Comment by st-pasha** [comment]
Seems like `context_path` argument is not needed at all: this setting can be provided within the existing `url` parameter. I.e. if the user passes `url="http://localhost:5555/h2o"` then connect to the provided url with the context path "h2o".

**Comment by CreatureDev** [comment]
@st-pasha I had tried that previously, but adding the context path to the url causes an assertion that the url matches some regular expression to fail
currently url is only expecting a host and port, anything extra is invalid

**Comment by st-pasha** [comment]
@CreatureDev It's easy to change the regular expression (much easier than adding a new parameter), and such change would be backward-compatible too.

**Comment by mmalohlava** [comment]
I pushed the configuration class here: https://github.com/h2oai/h2o-3/tree/feature/context_path_api (as it was proposed by @tomkraljevic)

The goal overlaps with this branch and I did not want to override Patrick changes here.

**Pull request closed without merging**
