### PR TITLE
Doing udf by chunk

### PR DESCRIPTION
**Pull request by vpatryshev**
take 2; just merged in the latest master.

### CODE REVIEW

**Comment by vpatryshev** [comment]
please test

**Comment by vpatryshev** [comment]
please test

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
please test

**Comment by vpatryshev** [comment]
please test!

**Comment by vpatryshev** [comment]
please test!

**Comment by vpatryshev** [comment]
please test!

**Comment by vpatryshev** [comment]
please test!

**Comment by vpatryshev** [comment]
please test!

**Comment by vpatryshev** [comment]
please test!

**Comment by vpatryshev** [comment]
please test!

**Comment by vpatryshev** [comment]
please test!

**Comment by vpatryshev** [comment]
please test!

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
Pasha, so, do you mind looking into it and approving or something?

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Pull request closed without merging**
