### PR TITLE
PUBDEV-5016: Major reorg & updates to Grid Search user guide page

### PR DESCRIPTION
**Pull request by ledell**
- Added an introduction
- Added a linkable index to the different sections of the page
- Added better code examples in R and Python
- Added more info about `search_criteria`
- Moved list of griddable parameters to the bottom
- Shuffled some other sections around

### CODE REVIEW

**Comment by ledell** [comment]
@angela0xdata For some reason the code highlighting is not working in the longer R code sections.  Can you take a look?

**Comment by angela0xdata** [comment]
I'll take a look today. I've found that sometimes highlighting fails when the code sample includes a combination of tabs and spaces.

**Comment by angela0xdata** [comment]
It seems like the very last line in each R Grid Search example is causing highlighting to fail, specifically the "$".
print(best_gbm1@model$model_summary)
print(best_gbm2@model$model_summary)

If you remove $ in the examples, then highlighting shows up. I'm trying to figure out why this happens. Looking at the binomial_double_trees example (in the Parameters section), the $ doesn’t cause an error in that example.

**Comment by angela0xdata** [comment]
@h2o-ops please test!

**Comment by ledell** [comment]
@angela0xdata Thanks for identifying why the code highlighting wasn't working.  I can rewrite that line to not include the $.

**Pull request merged**
