### PR TITLE
Gradle 6.3 and purge IDEA plugin

### PR DESCRIPTION
**Pull request by Pscheidl**
The more daring version of this: https://github.com/h2oai/h2o-3/pull/4565

- Resolves classpath issues. For some reason, the IDEA plugin interferes with how IntelliJ asembles the classpath, even though the project is imported as Gradle project.
- JGraphT extension has to be imported in a Gradle 5 friendly way to assemblies/genmodel
- Purged IDEA plugin, then the classpath is imported correctly.

Please review and let me know what I've forgotten. This is the first step to try to upgrade to gradle 5. Thank you.

Confirmed JGraphT is in place in assemblies genmodel JAR (Even with Gradle 6.3)

Screenshot from 2020-05-01 15-24-20

<details><summary>**Gradle 6 build output**</summary>

```
15:19:34: Executing tasks 'clean build --exclude-task test'...

> Task :buildSrc:compileJava UP-TO-DATE
> Task :buildSrc:compileGroovy UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE

> Configure project :
The project project ':h2o-ext-mojo-pipeline' needs CI for running tests! You can pass `-PdoCI=true` to force CI behaviour.
The project project ':h2o-persist-s3' needs CI for running tests! You can pass `-PdoCI=true` to force CI behaviour.

> Configure project :h2o-assemblies:main
== :h2o-assemblies:main: Using optional component: xgboost, version 3.30.0
== :h2o-assemblies:main: Using optional component: jython-cfunc, version 3.30.0

> Configure project :h2o-r


> Configure project :h2o-assemblies:genmodel
== :h2o-assemblies:genmodel: Using optional genmodel component: xgboost, version 3.30.0

> Task :cleanH2oDistTmp UP-TO-DATE
> Task :cleanTarget UP-TO-DATE
> Task :clean
> Task :h2o-algos:clean
> Task :h2o-app:clean
> Task :h2o-automl:clean
> Task :h2o-avro-parser:clean
> Task :h2o-bindings:cleanGenerateRESTAPIBindings
> Task :h2o-bindings:clean
> Task :h2o-core:cleanBuildVersionJava
> Task :h2o-core:clean
> Task :h2o-docs:cleanBooklets UP-TO-DATE
> Task :h2o-docs:cleanSphinxProjectVersionNumber
> Task :h2o-docs:clean UP-TO-DATE
> Task :h2o-ext-jython-cfunc:clean
> Task :h2o-ext-krbstandalone:clean
> Task :h2o-ext-mojo-pipeline:clean
> Task :h2o-ext-target-encoder:clean
> Task :h2o-ext-xgboost:clean
> Task :h2o-genmodel:clean
> Task :h2o-genmodel-ext-deepwater:clean
> Task :h2o-genmodel-ext-jgrapht:clean
> Task :h2o-genmodel-ext-xgboost:clean
> Task :h2o-hadoop-common:clean
> Task :h2o-hive:clean
> Task :h2o-jaas-pam:clean
> Task :h2o-jetty-8:clean
> Task :h2o-jetty-9:clean
> Task :h2o-k8s:clean
> Task :h2o-logger:clean
> Task :h2o-mapreduce-generic:clean
> Task :h2o-orc-parser:clean
> Task :h2o-parquet-parser:clean
> Task :h2o-parquet-v17-compat:clean
> Task :h2o-persist-gcs:clean
> Task :h2o-persist-hdfs:clean
> Task :h2o-persist-http:clean
> Task :h2o-persist-s3:clean

> Task :h2o-py:cleanBuild
Cleaning...

> Task :h2o-py:cleanCoverageData UP-TO-DATE
> Task :h2o-py:cleanUpSmokeTest UP-TO-DATE
> Task :h2o-py:clean UP-TO-DATE
> Task :h2o-r:cleanUp
> Task :h2o-r:cleanUpSmokeTest
> Task :h2o-r:clean UP-TO-DATE
> Task :h2o-scala_2.10:clean
> Task :h2o-scala_2.11:clean
> Task :h2o-security:clean
> Task :h2o-test-accuracy:clean
> Task :h2o-test-integ:cleanNodeJsSingleJVMTests UP-TO-DATE
> Task :h2o-test-integ:cleanPythonMultiJVMTests UP-TO-DATE
> Task :h2o-test-integ:clean
> Task :h2o-web:cleanUpSmokeTest
> Task :h2o-web:deleteDocFiles
> Task :h2o-web:deleteFlowFromWebRoot
> Task :h2o-web:deleteGenModelJarFromWebRoot
> Task :h2o-web:clean
> Task :h2o-webserver-iface:clean
> Task :h2o-assemblies:genmodel:clean
> Task :h2o-assemblies:main:clean
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :jar
> Task :assemble
> Task :licenseMain NO-SOURCE
> Task :licenseTest NO-SOURCE
> Task :license UP-TO-DATE
> Task :check
> Task :build

> Task :h2o-core:generateBuildVersionJava
NOTE: emitBuildVersionJava found no file, emitting new file
> Task :h2o-logger:compileJava
> Task :h2o-logger:processResources NO-SOURCE
> Task :h2o-logger:classes
> Task :h2o-logger:jar

> Task :h2o-genmodel:compileJava

> Task :h2o-genmodel:processResources
> Task :h2o-genmodel:classes
> Task :h2o-genmodel:jar
Note: /home/pavel/Projects/h2o-3/h2o-genmodel/src/main/java/hex/genmodel/GenModel.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
> Task :h2o-jaas-pam:compileJava
> Task :h2o-jaas-pam:processResources NO-SOURCE
> Task :h2o-jaas-pam:classes
> Task :h2o-jaas-pam:jar
> Task :h2o-webserver-iface:compileJava
> Task :h2o-webserver-iface:processResources NO-SOURCE
> Task :h2o-webserver-iface:classes
> Task :h2o-webserver-iface:jar

> Task :h2o-core:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:h2o-core:compileJava took 6.541 secs

> Task :h2o-core:processResources
> Task :h2o-core:classes
> Task :h2o-core:jar

> Task :h2o-algos:compileJava
/home/pavel/Projects/h2o-3/h2o-algos/src/main/java/hex/tree/DHistogram.java:5: warning: Unsafe is internal proprietary API and may be removed in a future release
import sun.misc.Unsafe;
               ^
/home/pavel/Projects/h2o-3/h2o-algos/src/main/java/hex/tree/DHistogram.java:108: warning: Unsafe is internal proprietary API and may be removed in a future release
  private static final Unsafe _unsafe = UtilUnsafe.getUnsafe();
                       ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 warnings
:h2o-algos:compileJava took 2.925 secs

> Task :h2o-algos:processResources
> Task :h2o-algos:classes
> Task :h2o-algos:jar
> Task :h2o-algos:assemble
> Task :h2o-algos:check
> Task :h2o-algos:build
> Task :h2o-genmodel-ext-xgboost:compileJava
> Task :h2o-genmodel-ext-xgboost:processResources
> Task :h2o-genmodel-ext-xgboost:classes
> Task :h2o-genmodel-ext-xgboost:jar

> Task :h2o-ext-xgboost:compileJava
:h2o-ext-xgboost:compileJava took 1.287 secs

> Task :h2o-ext-xgboost:processResources
> Task :h2o-ext-xgboost:classes
> Task :h2o-ext-xgboost:jar
Note: /home/pavel/Projects/h2o-3/h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostPojoWriter.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/pavel/Projects/h2o-3/h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostScoreTask.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :h2o-automl:compileJava

> Task :h2o-automl:processResources
> Task :h2o-automl:classes
> Task :h2o-automl:jar
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :h2o-ext-target-encoder:compileJava

> Task :h2o-ext-target-encoder:processResources
> Task :h2o-ext-target-encoder:classes
> Task :h2o-ext-target-encoder:jar
Note: /home/pavel/Projects/h2o-3/h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoderMojoWriter.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
> Task :h2o-app:compileJava
> Task :h2o-app:processResources NO-SOURCE
> Task :h2o-app:classes
> Task :h2o-app:jar
> Task :h2o-app:assemble
> Task :h2o-app:check
> Task :h2o-app:build
> Task :h2o-automl:assemble
> Task :h2o-automl:check
> Task :h2o-automl:build

> Task :h2o-avro-parser:compileJava

> Task :h2o-avro-parser:processResources
> Task :h2o-avro-parser:classes
> Task :h2o-avro-parser:jar
> Task :h2o-avro-parser:assemble
> Task :h2o-avro-parser:check
> Task :h2o-avro-parser:build
Note: /home/pavel/Projects/h2o-3/h2o-parsers/h2o-avro-parser/src/main/java/water/parser/avro/AvroParser.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :h2o-ext-jython-cfunc:compileJava
Note: /home/pavel/Projects/h2o-3/h2o-extensions/jython-cfunc/src/main/java/water/udf/JythonObjectFactory.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:h2o-ext-jython-cfunc:compileJava took 2.597 secs

> Task :h2o-ext-jython-cfunc:processResources
> Task :h2o-ext-jython-cfunc:classes
> Task :h2o-ext-jython-cfunc:jar

> Task :h2o-persist-hdfs:compileJava
:h2o-persist-hdfs:compileJava took 1.978 secs

> Task :h2o-persist-hdfs:processResources NO-SOURCE
> Task :h2o-persist-hdfs:classes
> Task :h2o-persist-hdfs:jar
> Task :h2o-ext-krbstandalone:compileJava
> Task :h2o-ext-krbstandalone:processResources
> Task :h2o-ext-krbstandalone:classes
> Task :h2o-ext-krbstandalone:jar
> Task :h2o-jetty-8:compileJava
> Task :h2o-jetty-8:processResources
> Task :h2o-jetty-8:classes
> Task :h2o-jetty-8:jar
> Task :h2o-k8s:compileJava
> Task :h2o-k8s:processResources
> Task :h2o-k8s:classes
> Task :h2o-k8s:jar
> Task :h2o-parquet-parser:compileJava
> Task :h2o-parquet-parser:processResources
> Task :h2o-parquet-parser:classes
> Task :h2o-parquet-parser:jar
> Task :h2o-persist-gcs:compileJava
> Task :h2o-persist-gcs:processResources NO-SOURCE
> Task :h2o-persist-gcs:classes
> Task :h2o-persist-gcs:jar
> Task :h2o-persist-http:compileJava
> Task :h2o-persist-http:processResources NO-SOURCE
> Task :h2o-persist-http:classes
> Task :h2o-persist-http:jar

> Task :h2o-persist-s3:compileJava

> Task :h2o-persist-s3:processResources
> Task :h2o-persist-s3:classes
> Task :h2o-persist-s3:jar
> Task :h2o-web:compileJava NO-SOURCE
Note: /home/pavel/Projects/h2o-3/h2o-persist-s3/src/main/java/water/persist/PersistS3.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
> Task :h2o-web:checkClientPrerequisites

> Task :h2o-web:installNpmPackages
audited 165 packages in 1.5s
found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
:h2o-web:installNpmPackages took 1.821 secs

> Task :h2o-web:compileHelpFiles
> Task :h2o-web:copyExampleFlows
> Task :h2o-web:installBowerPackages
> Task :h2o-web:copyFlowToWebRoot
> Task :h2o-genmodel-ext-jgrapht:compileJava
> Task :h2o-genmodel-ext-jgrapht:processResources
> Task :h2o-genmodel-ext-jgrapht:classes
> Task :h2o-genmodel-ext-jgrapht:jar
> Task :h2o-assemblies:genmodel:compileJava NO-SOURCE
> Task :h2o-assemblies:genmodel:processResources NO-SOURCE
> Task :h2o-assemblies:genmodel:classes UP-TO-DATE
> Task :h2o-assemblies:genmodel:downloadLicenses

> Task :h2o-assemblies:genmodel:shadowJar
:h2o-assemblies:genmodel:shadowJar took 1.948 secs

> Task :h2o-web:copyGenModelJarToWebRoot
> Task :h2o-web:copyHelpImages
> Task :h2o-web:processResources
> Task :h2o-web:classes

> Task :h2o-web:jar
:h2o-web:jar took 1.02 secs

> Task :h2o-assemblies:main:compileJava NO-SOURCE
> Task :h2o-assemblies:main:processResources NO-SOURCE
> Task :h2o-assemblies:main:classes UP-TO-DATE
> Task :h2o-assemblies:main:jar SKIPPED

> Task :h2o-assemblies:main:downloadLicenses
:h2o-assemblies:main:downloadLicenses took 6.813 secs

> Task :h2o-assemblies:main:licenseReport

> Task :h2o-assemblies:main:shadowJar
:h2o-assemblies:main:shadowJar took 25.203 secs

> Task :h2o-assemblies:main:copyJar

> Task :h2o-bindings:runGenerateRESTAPIBindingsSrc
Starting H2O cloud...
+ CMD: java -Xmx4g -ea -cp /home/pavel/Projects/h2o-3/h2o-assemblies/main/build/libs/main-3.30.0.jar water.H2OApp -name H2O_runit_pavel_4373727 -baseport 48000 -ip 127.0.0.1
H2O cloud 0 node 0 listening on port 48000
    with output file ../build/logs/java_0_0.out.txt

Generating R bindings... done (in 0.277s)
Generating Python bindings... done (in 0.077s)
Generating Docs Json bindings... done (in 0.600s)
Generating Thrift bindings... done (in 0.101s)
Generating C# bindings... done (in 0.130s)
Generating Java bindings... done (in 0.262s)

Killing JVM with PID 92890
:h2o-bindings:runGenerateRESTAPIBindingsSrc took 3.915 secs

> Task :h2o-bindings:compileJava

> Task :h2o-bindings:processResources NO-SOURCE
> Task :h2o-bindings:classes
Note: /home/pavel/Projects/h2o-3/h2o-bindings/src-gen/main/java/water/bindings/H2oApi.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
> Task :h2o-bindings:jar
> Task :h2o-bindings:startScripts
> Task :h2o-bindings:distTar
> Task :h2o-bindings:distZip
> Task :h2o-bindings:assemble
> Task :h2o-bindings:check
> Task :h2o-bindings:build
> Task :h2o-core:assemble
> Task :h2o-core:check
> Task :h2o-core:build
> Task :h2o-docs:assemble UP-TO-DATE
> Task :h2o-docs:check UP-TO-DATE
> Task :h2o-docs:createSphinxProjectVersionNumber
> Task :h2o-docs:build
> Task :h2o-ext-jython-cfunc:assemble
> Task :h2o-ext-jython-cfunc:check
> Task :h2o-ext-jython-cfunc:build
> Task :h2o-ext-krbstandalone:assemble
> Task :h2o-ext-krbstandalone:check
> Task :h2o-ext-krbstandalone:build

> Task :h2o-ext-mojo-pipeline:compileJava

> Task :h2o-ext-mojo-pipeline:processResources
> Task :h2o-ext-mojo-pipeline:classes
> Task :h2o-ext-mojo-pipeline:jar
> Task :h2o-ext-mojo-pipeline:assemble
> Task :h2o-ext-mojo-pipeline:check
> Task :h2o-ext-mojo-pipeline:build
> Task :h2o-ext-target-encoder:assemble
> Task :h2o-ext-target-encoder:check
> Task :h2o-ext-target-encoder:build
> Task :h2o-ext-xgboost:assemble
> Task :h2o-ext-xgboost:check
> Task :h2o-ext-xgboost:build
> Task :h2o-genmodel:assemble
> Task :h2o-genmodel:check
> Task :h2o-genmodel:build
Note: /home/pavel/Projects/h2o-3/h2o-extensions/mojo-pipeline/src/main/java/hex/mojopipeline/MojoPipeline.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
> Task :h2o-genmodel-ext-deepwater:compileJava
> Task :h2o-genmodel-ext-deepwater:processResources
> Task :h2o-genmodel-ext-deepwater:classes
> Task :h2o-genmodel-ext-deepwater:jar
> Task :h2o-genmodel-ext-deepwater:assemble
> Task :h2o-genmodel-ext-deepwater:check
> Task :h2o-genmodel-ext-deepwater:build
> Task :h2o-genmodel-ext-jgrapht:assemble
> Task :h2o-genmodel-ext-jgrapht:check
> Task :h2o-genmodel-ext-jgrapht:build
> Task :h2o-genmodel-ext-xgboost:assemble
> Task :h2o-genmodel-ext-xgboost:check
> Task :h2o-genmodel-ext-xgboost:build
> Task :h2o-hadoop-common:compileJava NO-SOURCE
> Task :h2o-hadoop-common:processResources NO-SOURCE
> Task :h2o-hadoop-common:classes UP-TO-DATE
> Task :h2o-hadoop-common:jar
> Task :h2o-hadoop-common:assemble
> Task :h2o-hadoop-common:check
> Task :h2o-hadoop-common:build

> Task :h2o-hive:compileJava
:h2o-hive:compileJava took 6.63 secs

> Task :h2o-hive:processResources
> Task :h2o-hive:classes
> Task :h2o-hive:jar
> Task :h2o-hive:assemble
> Task :h2o-hive:check
> Task :h2o-hive:build
> Task :h2o-jaas-pam:assemble
> Task :h2o-jaas-pam:check
> Task :h2o-jaas-pam:build
> Task :h2o-jetty-8:assemble
> Task :h2o-jetty-8:check
> Task :h2o-jetty-8:build
> Task :h2o-jetty-9:compileJava
> Task :h2o-jetty-9:processResources
> Task :h2o-jetty-9:classes
> Task :h2o-jetty-9:jar
> Task :h2o-jetty-9:assemble
> Task :h2o-jetty-9:check
> Task :h2o-jetty-9:build
> Task :h2o-k8s:assemble
> Task :h2o-k8s:check
> Task :h2o-k8s:build
> Task :h2o-logger:assemble
> Task :h2o-logger:check
> Task :h2o-logger:build
> Task :h2o-security:compileJava
> Task :h2o-security:processResources NO-SOURCE
> Task :h2o-security:classes
> Task :h2o-security:jar

> Task :h2o-mapreduce-generic:compileJava

> Task :h2o-mapreduce-generic:processResources
> Task :h2o-mapreduce-generic:classes
> Task :h2o-mapreduce-generic:jar
> Task :h2o-mapreduce-generic:assemble
> Task :h2o-mapreduce-generic:check
> Task :h2o-mapreduce-generic:build
Note: /home/pavel/Projects/h2o-3/h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :h2o-orc-parser:compileJava
Note: /home/pavel/Projects/h2o-3/h2o-parsers/h2o-orc-parser/src/main/java/water/parser/orc/OrcParser.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:h2o-orc-parser:compileJava took 2.212 secs

> Task :h2o-orc-parser:processResources
> Task :h2o-orc-parser:classes
> Task :h2o-orc-parser:jar
> Task :h2o-orc-parser:assemble
> Task :h2o-orc-parser:check
> Task :h2o-orc-parser:build
> Task :h2o-parquet-parser:assemble
> Task :h2o-parquet-parser:check
> Task :h2o-parquet-parser:build
> Task :h2o-parquet-v17-compat:compileJava NO-SOURCE
> Task :h2o-parquet-v17-compat:processResources NO-SOURCE
> Task :h2o-parquet-v17-compat:classes UP-TO-DATE
> Task :h2o-parquet-v17-compat:jar
> Task :h2o-parquet-v17-compat:assemble
> Task :h2o-parquet-v17-compat:check
> Task :h2o-parquet-v17-compat:build
> Task :h2o-persist-gcs:assemble
> Task :h2o-persist-gcs:check
> Task :h2o-persist-gcs:build
> Task :h2o-persist-hdfs:assemble
> Task :h2o-persist-hdfs:check
> Task :h2o-persist-hdfs:build
> Task :h2o-persist-http:assemble
> Task :h2o-persist-http:check
> Task :h2o-persist-http:build
> Task :h2o-persist-s3:assemble
> Task :h2o-persist-s3:check
> Task :h2o-persist-s3:build

> Task :h2o-py:compileJava
:h2o-py:compileJava took 10.642 secs

> Task :h2o-py:compileGroovy NO-SOURCE
> Task :h2o-py:processResources NO-SOURCE
> Task :h2o-py:classes
> Task :h2o-py:jar
> Task :h2o-py:assemble
> Task :h2o-py:check
> Task :h2o-py:copyH2OClientJar
> Task :h2o-py:copyClientSrcFiles
> Task :h2o-py:createVersionFiles
> Task :h2o-py:verifyDependencies
> Task :h2o-py:buildClientDist
> Task :h2o-py:copyH2OJar
> Task :h2o-py:copySrcFiles

> Task :h2o-py:buildDist
:h2o-py:buildDist took 4.903 secs

> Task :h2o-py:copyMainDist
:h2o-py:copyMainDist took 1.105 secs

> Task :h2o-py:build
> Task :h2o-r:compileJava NO-SOURCE
> Task :h2o-r:compileGroovy NO-SOURCE
> Task :h2o-r:processResources NO-SOURCE
> Task :h2o-r:classes UP-TO-DATE
> Task :h2o-r:jar
> Task :h2o-r:assemble
> Task :h2o-r:getRVersion
> Task :h2o-r:gitbranch
> Task :h2o-r:pdflatex

> Task :h2o-r:setProperties
    Git Branch: pavel/gradle-5
    R Version: 3.6.3
    PDF LATEX: 

> Task :h2o-r:cpH2OAppJar
> Task :h2o-r:setDevPackageFiles
> Task :h2o-r:setPackageFiles

> Task :h2o-r:buildPackageDocumentation
:h2o-r:buildPackageDocumentation took 4.465 secs

> Task :h2o-r:genPDF SKIPPED
> Task :h2o-r:cpPDF SKIPPED

> Task :h2o-r:buildPKG
:h2o-r:buildPKG took 7.046 secs


> Task :h2o-r:cpToR

> Task :h2o-r:publishPKG
:h2o-r:publishPKG took 1.163 secs

> Task :h2o-r:untar
:h2o-r:untar took 1.587 secs

> Task :h2o-r:cleaner
> Task :h2o-r:build_rh2o
> Task :h2o-r:check
> Task :h2o-r:build
> Task :h2o-scala_2.10:compileJava NO-SOURCE

> Task :h2o-scala_2.10:compileScala
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
:h2o-scala_2.10:compileScala took 17.575 secs

> Task :h2o-scala_2.10:processResources NO-SOURCE
> Task :h2o-scala_2.10:classes
> Task :h2o-scala_2.10:jar
> Task :h2o-scala_2.10:assemble
> Task :h2o-scala_2.10:check
> Task :h2o-scala_2.10:build
> Task :h2o-scala_2.11:compileJava NO-SOURCE

> Task :h2o-scala_2.11:compileScala
:h2o-scala_2.11:compileScala took 9.841 secs

> Task :h2o-scala_2.11:processResources NO-SOURCE
> Task :h2o-scala_2.11:classes
> Task :h2o-scala_2.11:jar
> Task :h2o-scala_2.11:assemble
> Task :h2o-scala_2.11:check
> Task :h2o-scala_2.11:build
> Task :h2o-security:assemble
> Task :h2o-security:check
> Task :h2o-security:build
> Task :h2o-test-accuracy:compileJava NO-SOURCE
> Task :h2o-test-accuracy:processResources NO-SOURCE
> Task :h2o-test-accuracy:classes UP-TO-DATE
> Task :h2o-test-accuracy:jar
> Task :h2o-test-accuracy:assemble
> Task :h2o-test-accuracy:check
> Task :h2o-test-accuracy:build
> Task :h2o-test-integ:compileJava NO-SOURCE
> Task :h2o-test-integ:processResources NO-SOURCE
> Task :h2o-test-integ:classes UP-TO-DATE
> Task :h2o-test-integ:jar
> Task :h2o-test-integ:assemble
> Task :h2o-test-integ:check
> Task :h2o-test-integ:build
> Task :h2o-web:assemble
> Task :h2o-web:check
> Task :h2o-web:compileAndInstallDocFiles
> Task :h2o-web:build
> Task :h2o-webserver-iface:assemble
> Task :h2o-webserver-iface:check
> Task :h2o-webserver-iface:build
> Task :h2o-assemblies:genmodel:jar SKIPPED
> Task :h2o-assemblies:genmodel:assemble
> Task :h2o-assemblies:genmodel:licenseMain NO-SOURCE
> Task :h2o-assemblies:genmodel:licenseTest NO-SOURCE
> Task :h2o-assemblies:genmodel:license UP-TO-DATE
> Task :h2o-assemblies:genmodel:check
> Task :h2o-assemblies:genmodel:build
> Task :h2o-assemblies:main:assemble
> Task :h2o-assemblies:main:licenseMain NO-SOURCE
> Task :h2o-assemblies:main:licenseTest NO-SOURCE
> Task :h2o-assemblies:main:license UP-TO-DATE
> Task :h2o-assemblies:main:check
> Task :h2o-assemblies:main:build

Task timings:
  25.203 secs  :h2o-assemblies:main:shadowJar
  17.575 secs  :h2o-scala_2.10:compileScala
  10.642 secs  :h2o-py:compileJava
   9.841 secs  :h2o-scala_2.11:compileScala
   7.046 secs  :h2o-r:buildPKG
   6.813 secs  :h2o-assemblies:main:downloadLicenses
   6.630 secs  :h2o-hive:compileJava
  53.014 secs  All others

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2m 18s
198 actionable tasks: 188 executed, 10 up-to-date
15:21:52: Tasks execution finished 'clean build --exclude-task test'.
```
</summary>

### CODE REVIEW

**Comment by michalkurka** [comment]
@Pscheidl thank you for this

We already tried upgrading to Gradle 5.x in the past, but had to revert back to 4.x because Java 13 was not supported by 5.x: https://github.com/h2oai/h2o-3/pull/4287

Then we tried upgrading to Gradle 6 but there was an issue with the scala build plugin. I believe @jakubhava had a PR but I cannot find it right now.

I think going to latest Gradle would be the better option (unless they added support for Java 13 & 14 to Gradle 5)

**Comment by Pscheidl** [comment]
Migrated to Gradle 6.3 - I thought it's impossible to easily migrate the plugin, but it turns out it is doable. Only my head is lazy & stupid.

**Comment by Pscheidl** [comment]
Builds on OpenJDK 13 locally.

**Comment by jakubhava** [comment]
just fyi: Sparkling Water no longer depends on h2o-scala.

**Comment by jakubhava** [comment]
nit: I would also try to have a look on deprecation warnings, but that can be done in another PR

**Pull request merged**
