### PR TITLE
PUBDEV-3198

### PR DESCRIPTION
**Pull request by angela0xdata**
For El Capitan users, added note stating that the --user flag is
required when starting H2O from command line or python.

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/103)

### CODE REVIEW

**Comment by abal5** [comment]
Can one of the admins verify this patch?

**Comment by st-pasha** [comment]
I don't understand this... My Mac runs El Capitan 10.11.3, and everything works fine without any flags

**Comment by mdymczyk** [comment]
We don't have a `user` flag, running `h2o -jar h2o.jar --user` will result in an error.

`--user` seems like a `pip` flag which installs packages locally for a user.

**Comment by angela0xdata** [comment]
+ Anmol and Abhishek,

Can you verify whether --user is required for starting H2O from command
line and from Python? It seems like it might not be.
Refer to https://0xdata.atlassian.net/browse/PUBDEV-3198 for reference.

**Comment by abal5** [comment]
I beleive it's only required for pip to install packages locally for the user like stated by Mateusz.

**Comment by jgambera** [comment]
The —user flag is required for MacOS X El Capitan and greater with built-in python, because of Apple lockdown of certain filesystems with no possible access.
It is only applicable for python pip.

**Comment by abhishekmalali** [comment]
I just tested the latest version of H2O wheel on the website. The --user tag is not required atleast for Mac OSX Yosemite. I tested it on both conda environments and system python and install was fine without the tag. And yes --user tag is only required for the installation via pip.

**Comment by arnocandel** [comment]
Does the current PR need to be modified to reflect the 'only via pip' part? It currently says that it's necessary from command line as well.

**Comment by angela0xdata** [comment]
I'm still confused about how to document this for El Capitan users as these comments conflict with what I was told when I created PUBDEV-3198. Is it just that El Capitan users who install H2O python? In this case, does the user have to specify pip install http://h2o-release.s3.amazonaws.com/h2o/rel-turing/3/Python/h2o-3.10.0.3-py2.py3-none-any.whl --user? And also in this case, does everything work fine for El Capitan users when they download just the h2o binary using (for example) curl -o h2o.zip http://download.h2o.ai/versions/h2o-3.10.0.3.zip?

**Comment by arnocandel** [comment]
Can you guys coordinate and close this PR?

**Comment by jgambera** [comment]
El Capitan has a protected /usr/ directory so the h2o package won't install.
If you use Brew Python or Anaconda this is not applicable.
If you are using the default python that ships with OS X El Capitan please use
pip install --user h2o

**Comment by arnocandel** [comment]
@angela0xdata can you update accordingly please? thx.

**Comment by angela0xdata** [comment]
I updated the text after discussing with Jeff. Let me know if anything has to change or is incorrect.

**Comment by angela0xdata** [comment]
documentation reviewed by jeff.

**Pull request merged**
