### PR TITLE
[GH-15840] Make release notes smaller to fix UI loading

### LINKED ISSUE #15840: Make release notes smaller to fix UI loading
The problem with UI loading:
Screenshot 2023-10-18 at 13 08 59

### PR DESCRIPTION
**Pull request by mn-mikke**
Closes #15840 

This PR proposes to split release notes into two files to fix the problem with GitHub UI. It also renames headers `Bug` to `Bug Fix` to allow us to introduce new section `Known Bug`

### CODE REVIEW

**Review by valenad1 — DISMISSED** [review]
👍

**Review by valenad1 — COMMENTED** [review]
I thought just now that we can link those files -> changes priors first line would be link to changes and changes.md at the end can link to changes-priors..

**Comment by mn-mikke** [comment]
@valenad1 Good idea, will try that.

**Review by valenad1 — DISMISSED** [review]
Works, thank you 💯

**Review by hannah-tillman — APPROVED** [review]
did a small fix -- thanks for fixing this!!!

**Pull request merged**
