### PR TITLE
Bring latest Deepwater (mostly TF) changes into master

### PR DESCRIPTION
**Pull request by arnocandel**
Bring TF backend of DeepWater into master, for easier distribution/testing.

### CODE REVIEW

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Comment by mstensmo** [comment]
@h2o-ops please test!

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by arnocandel** [comment]
Just had everything pass (21 successful checks - after retries).

**Comment by abal5** [comment]
Looks good now after retries.

**Pull request merged**
