### PR TITLE
GH-16397 - remove sun licence from jar

### LINKED ISSUE #16397: Remove Sun licence from the jar
jsp code contains files with Sun licence in it. Remove it from the packaged jar in order to pass licence check.

### PR DESCRIPTION
**Pull request by valenad1**
Fixed #16397

### CODE REVIEW

**Comment by wendycwong** [comment]
@valenad1: I think you want to put it into the release branch : rel-3.46.0

After I messed up with my GLM constrained, I pay attention to the branch now.

**Review by wendycwong — CHANGES_REQUESTED** [review]
@valenad1: I think you want to put it into the release branch : rel-3.46.0

After I messed up with my GLM constrained, I pay attention to the branch now.

**Comment by valenad1** [comment]
> @valenad1: I think you want to put it into the release branch : rel-3.46.0
> 
> After I messed up with my GLM constrained, I pay attention to the branch now.

Thanks

**Comment by valenad1** [comment]
> @valenad1: I think you want to put it into the release branch : rel-3.46.0
> 
> After I messed up with my GLM constrained, I pay attention to the branch now.

We have a Check Pull Request Metadata task which check the branch and couple of additional stuff like milestone and Project.

**Review by wendycwong — APPROVED** [review]

**Pull request merged**
