### PR TITLE
PUBDEV-3793: Auto-generate r bindings

### PR DESCRIPTION
**Pull request by surekhajadhwani**
Following image summarizes the changes in new R bindings in comparison to existing ones:
screen shot 2016-11-08 at 9 59 25 am

These changes shouldn't affect existing users as only new columns/values are added and nothing has been removed. 
Other than these changes, we now set default value to NULL for objects and 0 for numbers if it is not already set with the exception of x, y and training_frame columns. Also, max_confusion_matrix_size, ignore_columns and response_columns are skipped and not added to R API.

Tested branch using independent jenkins job: 
http://mr-0xa1:8080/view/Branch_Test/job/branch_build_all/28/

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/484)

### CODE REVIEW

**Comment by ledell** [comment]
@surekhajadhwani @arnocandel We have a history of setting numeric defaults to -1 rather than 0.  @surekhajadhwani Can you give me an example of a parameter whose default was changed from missing to 0?  I am concerned that some of these parameters will be set to 0 when they shouldn't be... or do we automatically convert zeros to "missing" when passed to H2O so that they take on their real (Java defined) default values?

**Comment by surekhajadhwani** [comment]
@ledell I just verified that we don't have any numeric column without a default value in Java currently but there are some object columns without default value in Java. Such columns are set to NULL. Also, we have a check in auto-gen code[ here ](https://github.com/h2oai/h2o-3/blob/4a637e641cc7cd3772946bd40cc3844d5327d0ab/h2o-bindings/bin/gen_R.py#L821) which assigns default value of 0 if nothing is defined in Java as per our previous discussion.

**Comment by ledell** [comment]
@surekhajadhwani Ok, I understand what you are doing now.  Have you done a sanity check to make sure all the new defaults of `NULL` and `0` make sense?  It would be great to have a diff table between the defaults of the existing API vs the auto-gen API, so we could easily look over everything and make sure the new values make sense in context.

**Comment by arnocandel** [comment]
@ledell The diff table is here: https://github.com/h2oai/h2o-3/pull/484/files

**Comment by ledell** [comment]
@arnocandel Ok, as long as that is consistent with Java that sounds good to me (I was under the impression that -1 was the primary default for numerics in Java based on past conversations).  By "diff" I meant a simple table that just shows the variables whose defaults have changed rather than the entire PR, but rather than create extra work for @surekhajadhwani, I'll look within the PR to sanity check the changes.

Another question -- the order of the parameters have changed, so if users were not explicitly naming parameters, then code will probably break.  Is that a concern we should address, or not?

**Comment by surekhajadhwani** [comment]
@ledell I can quickly create a list of params with new/old default values if you need. Also, the order of params is same as the order on Flow UI and coming from Java. Initial required params like x/y/training_frame which usually don't explicit naming have same order as old API.

**Comment by ledell** [comment]
@surekhajadhwani @arnocandel Here is the table.  There is a list of itemized issues/points that we should discuss below:


| Algorithm | Parameter with no default | New default |
|-----------:|------------:|:------------|
| **randomForest**       |        `model_id` |     NULL  
|       |        `checkpoint` |    NULL 
|       |        `sample_rate_per_class` |    NULL 
|       |        `class_sampling_factors` |    NULL 
|       |        `seed` |     -1 
| **gbm**       |        `model_id` |     NULL  
|       |        `checkpoint` |     NULL  
|       |        `sample_rate_per_class` |     NULL 
|       |        `class_sampling_factors` |    NULL 
|       |        `seed` |     -1  
|       |        `max_abs_leafnode_pred` |    1.79769313486e+308 
| **glm**       |        `model_id` |     NULL  
| **glrm**       |        `cols` |     NULL  
|       |        `k` |     1  
|       |        `model_id` |     NULL  
|       |        `validation_frame` |     NULL 
|       |        `loading_name` |     NULL 
|       |        `ignore_const_cols` |     TRUE
| **prcomp**       |        `k` |     1  
|       |        `model_id` |     NULL  
|       |        `seed` |     -1  
| **kmeans**       |        `k` |     1  
|       |        `model_id` |     NULL  
|       |        `seed` |     -1 
|       |        `ignore_const_cols` |     TRUE
| **svd**       |        `nv` |     1  
|       |        `seed` |     -1 
|       |        `use_all_factor_levels` |    TRUE
| **naiveBayes**       |        `model_id` |     NULL  
|       |        `seed` |     -1   
| **deeplearning**       |        `fold_column` |     NULL  
|       |        `model_id` |     NULL  
|       |        `validation_frame` |     NULL  
|       |        `fold_column` |     NULL  
|        |        `weights_column` |     NULL     
|        |        `offsets_column` |     NULL   
|        |        `class_sampling_factors` |     NULL     
|        |        `checkpoint` |     NULL     
|        |        `pretrained_autoencoder` |     NULL     
|        |        `hidden_dropout_ratios` |     NULL     
|        |        `initial_weights` |     NULL     
|        |        `initial_biases` |     NULL     

Additional Notes:

- This table excludes `x, y, training_frame` which are missing, but required. 
- This table does not include changes made to non-missing defaults (see below for that)
- Several algos had defaults changed from 0 to 0.0 (where appropriate).  


Points to be addressed:

1. glm has an error -- the order of the defaults changed to : `missing_values_handling = c("Skip", "MeanImputation")` and needs to be reversed back to what it was.
3. glm `family` order changed as well, might want to change it back.  Was: `family = c("gaussian", "binomial", "poisson", "gamma", "tweedie","multinomial")` Now: `family = c("gaussian", "binomial", "multinomial", "poisson", "gamma", "tweedie")`. 
- glm `early_stopping=FALSE` was changed to `early_stopping=TRUE` Why?
- glm `max_iterations = 50` changed to `max_iterations = -1`
- glm `beta_epsilon = 0` changed to `beta_epsilon = 0.0001`
- glm `solver = c("IRLSM", "L_BFGS")` changed to `solver = c("AUTO", "IRLSM", "L_BFGS", "COORDINATE_DESCENT_NAIVE", "COORDINATE_DESCENT")` but that seems like a good fix to me.
- glm `alpha = 0.5` changed to `alpha = NULL`.  Why?
- glm `seed = NULL` changed to `seed = -1`.  That is a good change.
- glm `lambda = 1e-05` changed to `lambda = NULL`.  Why?
- Let's discuss the change to specify a default for `k` in k-means and glrm, prcomp.  If we do want to specify a default (not sure we do yet), I am not sure that `k = 1` is the best choice...
- glrm parameter `max_updates` default is is now 2000 `2*max_iterations`, where `max_iterations` defaults to 1000.  Is that a better default than the previous one?
- svd: `transform` default changed from `transform = "NONE"` to `transform = c("NONE", "STANDARDIZE", "NORMALIZE", "DEMEAN", "DESCALE")` but that seems like a good fix to me.
- svd: Not sure that `nv = 1` is the best default...

**Comment by surekhajadhwani** [comment]
@ledell Parameter default values are automatically used from underlying Java code, if present. I had cross verified from Python API which already uses these values. If we want to change the sequence of ENUM values, I think it would be better to update in Java code so that it is consistent with Python API and easy to maintain instead of hard-coding in auto-gen code. May be @arnocandel could address other points.

**Comment by surekhajadhwani** [comment]
Thanks @tomasnykodym. For alpha, backend value is NULL currently. Should we just update in R API or backend value also?

**Comment by tomkraljevic** [comment]
The last person to approve this needs to be @angela0xdata 
Definitely do not merge this without a thorough review of the documentation.

Definitely do not put this into a dot release.  Major new release with major documentation.

**Comment by wendycwong** [comment]
Regarding GLRM, increasing the max_iteration is fine.  We have other conditions to check for early model termination.  From my playing around with it, I have yet to run more than 1000 iterations before the algo converges.

By the way, please add seed to GLRM as well.  We have random initial conditions and power methods which generates random vectors/arrays.  I assume it already have default value that that is the reason it is left out, right?

What about PCA?  Everything is fine there?


Thanks, Wendy

**Comment by surekhajadhwani** [comment]
@wendycwong Thanks for the review. We have added seed = -1 for GLRM also. Also, PCA seems to be fine.

@ledell @navdeep-G I have updated help for alpha (GLM) and max_updates (GLRM) as per our discussion. @arnocandel I have updated the order of missing_values enum (GLM, DeepLearning) so that R API takes the correct default value.

Thanks.

**Comment by angela0xdata** [comment]
I'm fine with whatever changes are approved. From what I can tell, the changes will result in some minor updates to the documentation regarding default values along with some other minor ordering updates.

**Comment by surekhajadhwani** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
@surekhajadhwani Can we remedy the conflicts?

**Comment by ledell** [comment]
@surekhajadhwani @navdeep-G Once the conflicts are fixed, I think this is ready to be merged.

**Comment by surekhajadhwani** [comment]
@ledell @navdeep-G Thank you :) I will merge these changes once Jenkins tests complete.

**Comment by navdeep-G** [comment]
@surekhajadhwani Awesome. Please make sure to squash and merge these commits :)

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by ledell** [comment]
There are now 2 conflicting files, can you take a quick look @surekhajadhwani ?  It's because we changed the new GLM family name from "quasi_binomial" to "quasibinomial".  Should be a quick fix.

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by surekhajadhwani** [comment]
@h2o-ops please test!

**Comment by surekhajadhwani** [comment]
@h2o-ops please test!

**Comment by surekhajadhwani** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
@surekhajadhwani @ledell @arnocandel All tests are passing except `PR_R_cmd_check`, which doesn't seem to start. I am running a branch test for this job specifically. Hold off on merge until I get results.

**Comment by surekhajadhwani** [comment]
sure, thanks @navdeep-G

**Comment by surekhajadhwani** [comment]
Individual branch test seems to be successful: http://mr-0xa1:8080/view/Branch-PR_Test/job/branch_R_cmd_check/59/. I will merge the changes now. Thanks.

**Pull request merged**
