### PR TITLE
[PUBDEV-4191] Remove minor version from hadoop distribution in buildi…

### PR DESCRIPTION
**Pull request by jakubhava**
…nfo.json file to be consistent with the rest of the naming of hadoop versions

### CODE REVIEW

**Comment by mmalohlava** [comment]
Could it trigger any problems in webpage/download page generation?

**Comment by jakubhava** [comment]
@mmalohlava sorry for late reply. I think we have changed the version naming on the page and everywhere to x.y and it seems like we just missed to edit buildinfo file. 

So from my point of view, this change should be safe, however would be good to have this confirmed by @abal5

**Comment by abal5** [comment]
This looks ok to me, we did something like this a while ago and there was an issue with the links on the download page.

**Comment by jakubhava** [comment]
So good to merge ?

**Comment by mmalohlava** [comment]
Spoke with Vinod, it is not used anymore, it will be used in future (maybe) :)

**Pull request merged**
