### PR TITLE
PUBDEV-8366 remove support for legacy makefile

### PR DESCRIPTION
**Pull request by valenad1**
https://h2oai.atlassian.net/browse/PUBDEV-8366
Issue that we talk about here: https://h2oai.slack.com/archives/C03HXQSLW/p1632315956190000

We can merge it as part of java 17 image build or separately.

### CODE REVIEW

**Comment by michalkurka** [comment]
> We can merge it as part of java 17 image build or separately.

@valenad1 I would prefer to merge separately to make sure there is no side effect

**Comment by michalkurka** [comment]
Can you please change the base branch to rel-zizler?

**Comment by valenad1** [comment]
It is ready 💯 I will wait for a build but I would not expect issues..

**Review by michalkurka — APPROVED** [review]
Thank you - looks good!

**Comment by valenad1** [comment]
All passed on PR pipeline 🥇

**Pull request merged**
