### PR TITLE
[WRI-ITA-333] Use AWS CLI for release upload to S3.

### PR DESCRIPTION
**Pull request by michal-raska**
(cherry picked from commit 5743dad31cf40f401db883b44373ed3a8fcca955)

Using AWS CLI is in master for a few days and it looks OK so far. I checked with @angela0xdata and also from docs perspective everything looks good.

### CODE REVIEW

**Comment by michal-raska** [comment]
@h2o-ops please test

**Comment by michal-raska** [comment]
@h2o-ops please test

**Comment by michal-raska** [comment]
@h2o-ops please test

**Comment by michal-raska** [comment]
@h2o-ops please test!

**Comment by michal-raska** [comment]
@h2o-ops please test!

**Comment by michal-raska** [comment]
@h2o-ops please test!

**Comment by michal-raska** [comment]
@h2o-ops please test!

**Comment by michal-raska** [comment]
@h2o-ops please test!

**Comment by michal-raska** [comment]
@h2o-ops please test!

**Comment by michal-raska** [comment]
please test!

**Comment by michal-raska** [comment]
please test!

**Comment by Rashitko** [comment]
please test!

**Comment by Rashitko** [comment]
please test!

**Comment by michal-raska** [comment]
please test!

**Comment by michal-raska** [comment]
please test!

**Comment by michal-raska** [comment]
please test!

**Pull request merged**
