### PR TITLE
Making sure DOONLY is enforced, right in H2OTestRunner

### PR DESCRIPTION
**Pull request by vpatryshev**
Michal,
I'm sure you'll like it.

### CODE REVIEW

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
It is not necessary, let's keep the caller to setup right parameters.

**Comment by vpatryshev** [comment]
Can you show me that it works? So far I could not make it work.

**Comment by mmalohlava** [comment]
```bash
export DOONLY="water.parser.ChunksizeTest"
./gradlew clean :h2o-core:test
```

**Pull request closed without merging**
