### PR TITLE
[PUBDEV-3857] [PUBDEV-2448] Major cleanup of all python docs

### PR DESCRIPTION
**Pull request by st-pasha**
Also: [PUBDEV-3889]

### CODE REVIEW

**Comment by wendycwong** [comment]
Pasha:  Wow, that is a lot of stuff you got there.  Most of them are documentation related.  It looks clear to me.  Thanks for fixing the h2o.frame() method.  The parts for GLRM/SVD/PCA looks good.

**Comment by st-pasha** [comment]
@h2o-ops please test!

**Comment by st-pasha** [comment]
@h2o-ops please test!

**Comment by st-pasha** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
for modeling.rst
for the new formatting `Supervised, Unsupervised, Misc..` under Modeling in H2O please use the updated format now in master (modeling.rst)  http://h2o-release.s3.amazonaws.com/h2o/master/3743/docs-website/h2o-py/docs/modeling.html

**Comment by laurendiperna** [comment]
Here are my notes (overall looks amazing!). Some of these should be updated in this PR others may be better placed in another ticket.

**frame.py :** 
has many missing return statements:
a few examples:
abs()
acos()
acosh()
all()
any()
any_na_rm()
anyfactor()
apply()
as_date()
ascharacter()
asfactor()

**and parameters statements:**
get_frame()
head()
moment()
mult()
tail()
type()
Groupby is missing parameters, and all the methods that apply to GroupBy are missing doc strings, parameter and return statements

**missing return statement formatting**
h2o.py: 
h2o.connect()
**h2o.connection() (this one has a typo :returns H2OConnection:**
should be :returns: H2OConnection.
h2o.lazy_import()
h2o.ls()
h2o.make_metrics()
h2o.cluster()

**grid_search.py**
starting with catoffsets() there are a few parameters that are missing return statements
**null_deviance() looks like the formatting is off for this parameter**

**in Model Categories:**
the threshold parameter throughout is missing its type
h2o.model.ModelBase has a few missing return statements
examples: catoffsets(), coef(), coef_norm()

**H20Assemby**
missing doc strings for all methods

**Comment by laurendiperna** [comment]
note some of the return statements contain nice formatting (:returns: an :class:`H2OFrame` object.) others don't ( :returns: H2OFrame
), would be nice to have this be consistent, but not required if not something that is quick to fix

**Comment by st-pasha** [comment]
@laurendiperna For `modeling.rst` I'm already using the updated formatting where models are grouped into sections. With the following differences: section titles use higher-level headings than the classes they group (for logical consistency), classes are sorted alphabetically (for stability), and "Misc" replaced with "Miscellaneous" because the former is not a real word.

For return statements, I feel they are not necessary if they just reiterate what the main description of the function says. For example for function `abs()` we could have had
```
"""
Make a new frame by taking absolute values of the current frame.

:returns: a new frame containing absolute values of the current frame.
"""
```
but this would be completely tautological. [PEP-257](https://www.python.org/dev/peps/pep-0257/) gives an example of an acceptable one-line docstring: 
```
def kos_root():
    """Return the pathname of the KOS root directory."""
    ...
```
which shows that having an explicit return statement is not required.

**Comment by st-pasha** [comment]
@h2o-ops please test!

**Comment by st-pasha** [comment]
@laurendiperna I've address your feedback in the last commit. Formatting in few functions fixed; added documentation for some missing parameters / return statements. 

I did not do the following: 
 * add `:return:` clause to all methods -- per explanation above, I do not believe having it is necessary for functions where the help is a one-liner already describing what the method returns.
 * supply missing documentation for certain classes such as GroupBy or Assembly -- I do not know what those classes are doing, and figuring that out is a separate task.

**Comment by wendycwong** [comment]
Pasha:  Finished reviewing your PR in details.  Very nice change that you have put in there.  I have one major issue and some minor ones.  I will put them each as a separate comment for you.  I tried to do things in order.

**Comment by wendycwong** [comment]
Major issue:  you have changed the return type of the two functions:

1. columns_by_type() return type was changed from list of column indices to H2OFrame.
2. which() return type was changed from H2OFrame to list of row indices.

My concern is this can break customer APIs.  I would like to know the reason for the return type change and if it is necessary, would like to roll these changes out slowly.  Let me know.

**Comment by st-pasha** [comment]
@wendycwong Thanks for spotting that, the functionality didn't change, it's just my mistake in rewriting the docs. I'll fix that right away

**Comment by wendycwong** [comment]
The following functions are either missing parameter descriptions or the wrong parameters are described:

h2o.get_frame(frame_id): parameter frame_id is not described;
h2o.group_by.GroupBy(fr, by) parameters not mentioned;
h2o.model.H2OBinomial.plot() missing parameter description for server;
h2o.model.model_base.ModelBase.download_pojo() parameter description missing for get_genmodel_jar;

h2o.model.binomial.H2OBinomialModel.find_idx_by_threshold() missing parameter description for threshold;
h2o.model.binomial.H2OBinomialModel.find_threshold_by_max_metric() missing parameter description for metric;
h2o.model.binomial.H2OBinomialModel.metric() missing parameter description for metric;
h2o.model.binomial.H2OBinomialModel.plot() missing parameter description for server;

h2o.model.clustering.H2OClusteringModel.centroid_stats(): extra parameter threshold description is found.  Please remove;
h2o.model.clustering.H2OClusteringModel.tot_withinss(): extra parameter threshold description is found.  Please remove;
h2o.model.clustering.H2OClusteringModel.totss(): extra parameter threshold description is found.  Please remove;
h2o.model.clustering.H2OClusteringModel.withinss(): extra parameter threshold description is found.  Please remove;

h2o.model.metrics_base.H2OBinomialModelMetrics.plot(): wrong parameter is described.  It should be server and not show.
h2o.grid.metrics.H2OBinomialGridSearch.find_idx_by_threshold():  add parameter description for threshold.
h2o.grid.metrics.H2OBinomialGridSearch.find_threshold_by_max_metric():  add parameter description for metric.

h2o.grid.metrics_H2OMultinomialGridSearch.confusion_matrix():  please add parameter description for data;
h2o.grid.metrics.H2OMultinomialGridSearch.hit_ratio_table():  Please change the return type, it should not be R2, right?

**Comment by wendycwong** [comment]
In h2o.assembly.H2OAssembly, there is no description of anything, parameters, return types.  Is this covered in another JIRA?  Let me know.

**Comment by wendycwong** [comment]
Since I am working on the python client api tests, it will be great if you can specify the return types for the following methods:

apply()
as_date()
as_character()
as_factor()

**Comment by wendycwong** [comment]
The return type frame is very confusing.  There are R, panda and H2O frames.  Can we add return H2OFrame instead of just frame in the following functions:

insert_missing_values()
cos()
sign()
exp()
expm1()
sin()
sinh()
sinpi()
sqrt()
tan()
tanh()
tanpi()
var()

**Comment by wendycwong** [comment]
The following return type is missing or hard to deduce:

countmatches()
cummax()
cummin()
cumprod()
cumsum()
floor()
gamma()
"gsub()"
scale()
tolower()
toupper()
match()
mean()
sum()
transpose()
trigamma()
lgamma()
log()
round()
rstrip()
log10()
log1p()
rep_len()
trunc()
log2()
"lstrip()"
na_omit();
"signif()"
sub();
week();
year().

If they have the same return type like H2OFrame, perhaps you can mention it instead of typing in for each one.

**Comment by wendycwong** [comment]
what does prod(na_rm=False) do again?  Does it multiple all columns and all rows of the frame and return a double as the final answer or does it do column wise multiplication?

**Comment by wendycwong** [comment]
h2o.grid.grid_search.H2OGridSearch return type is missing:  A new H2OGridSearch instance.

**Comment by wendycwong** [comment]
h2o.model.ModelBase.actual_params return type is a dictionary of actual parameters of the model;
h2o.model.model_base.ModelBase.default_parms() return type as dictionary instead of just parameters;
h2o.model.model_base.ModelBase.full_parameters() return type as dictionary instead of just parameters;

  I guess if you specified parameters are always returned as a dictionary, you will not need to specify this for every method.

**Comment by wendycwong** [comment]
Pasha:  That is all I got!  Great work.

**Comment by laurendiperna** [comment]
once H2OSingularValueDecompositionEstimator is under misc in the user table of contents, you're good for my review. Thanks!

**Comment by st-pasha** [comment]
@wendycwong Added JIRAs for documenting GroupBy & Assembly classes: [PUBDEV-3914] and [PUBDEV-3915]

All other suggestions implemented

**Comment by wendycwong** [comment]
Pasha:  Thanks for all the fixes.  Wendy

**Pull request merged**
