### PR TITLE
Update performance-and-prediction.rst

### PR DESCRIPTION
**Pull request by xiaochi-liu**
AUC is not good for imbalanced data.

### CODE REVIEW

**Comment by ledell** [comment]
AUC is good for imbalanced data, unlike other metrics such as accuracy.

**Review by ledell — COMMENTED** [review]
This update is not accurate.

**Comment by xiaochi-liu** [comment]
Thanks @ledell.

Just for clarification, can AUC be used for imbalanced data? In the previous section "AUC (Area Under the ROC Curve)", it says:

>  AUC is usually not the best metric for an imbalanced binary target because a high number of True Negatives can cause the AUC to look inflated. For an imbalanced binary target, we recommend AUCPR or MCC.

I'm working on an imbalanced binary classification problem using `h2o.automl()`, and I've set `balance_classes = TRUE` and `max_after_balance_size = 100` to oversample the minority class, which occupies 5% of the whole data. The leader model's `AUC` is good (around 0.8), but `AUCPR` is a little bit low (only around 0.3).

I'm also trying the [themis](https://themis.tidymodels.org/) package to use different oversample methods (e.g., SMOTE), but still, the `AUCPR` is not easy to improve, sometimes even worse.

May I ask:

1. Can I use `AUC` instead of `AUCPR` to evaluate the model handling imbalanced data? Would reviewers criticize me on this point?

2. Given the prevalence of minority class in my data is 0.05, whether an `AUCPR` of 0.3 is acceptable? Does it have to be close to 1? I've set `stopping_metric = "AUCPR"` in `h2o.automl()`. Are there other tips or parameter settings to improve `AUCPR` further?

Your kind help and guidance are much appreciated!

**Comment by xiaochi-liu** [comment]
> This update is not accurate.

Thanks @ledell.

Just for clarification, can AUC be used for imbalanced data? In the previous section "AUC (Area Under the ROC Curve)", it says:

>  AUC is usually not the best metric for an imbalanced binary target because a high number of True Negatives can cause the AUC to look inflated. For an imbalanced binary target, we recommend AUCPR or MCC.

I'm working on an imbalanced binary classification problem using `h2o.automl()`, and I've set `balance_classes = TRUE` and `max_after_balance_size = 100` to oversample the minority class, which occupies 5% of the whole data. The leader model's `AUC` is good (around 0.8), but `AUCPR` is a little bit low (only around 0.3).

I'm also trying the [themis](https://themis.tidymodels.org/) package to use different oversample methods (e.g., SMOTE), but still, the `AUCPR` is not easy to improve, sometimes even worse.

May I ask:

1. Can I use `AUC` instead of `AUCPR` to evaluate the model handling imbalanced data? Would reviewers criticize me on this point?

2. Given the prevalence of minority class in my data is 0.05, whether an `AUCPR` of 0.3 is acceptable? Does it have to be close to 1? I've set `stopping_metric = "AUCPR"` in `h2o.automl()`. Are there other tips or parameter settings to improve `AUCPR` further?

Your kind help and guidance are much appreciated!

**Pull request closed without merging**
