### PR TITLE
beings -> begins

### PR DESCRIPTION
**Pull request by micahstubbs**
improve word choice

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/45)

### CODE REVIEW

**Comment by abal5** [comment]
Currently testing this PR please wait for response from the team.

**Comment by abal5** [comment]
Currently testing this PR please wait for response from the team.

**Comment by angela0xdata** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/h2oai/h2o-3/45)*

**Comment by abal5** [comment]
Currently testing this PR please wait for response from the team.

**Pull request merged**
