### PR TITLE
[PUBDEV-5792] Minimal test, that reproduce a bug of numerical instability

### PR DESCRIPTION
**Pull request by woj-i**
Parser hangs on reading large numbers. The method of conversion should be fixed.

Sponsored by fingerprints.digital

### CODE REVIEW

**Comment by michalkurka** [comment]
@woj-i thanks for the reproducer, we will fix!

**Comment by woj-i** [comment]
@michalkurka here is the fix by @kjopek :)
I will add a few tests more and then you can merge.

**Comment by michalkurka** [comment]
@woj-i thanks for the implementation effort - I suspect it is overlapping with a PR we are currently working on: https://github.com/h2oai/h2o-3/pull/2530. This is just a heads up so that you know there are changes being done in the same code.

I think we want to avoid allocating new memory per-number when parsing the dataset. I wouldn't return a new Tuple from the method. Instead I would call compress2 to get the finalized representation of the Chunk and read the value from there - this would more higher level than a true unit test but it would make sure the desired outcome is accomplished and tested.

**Comment by woj-i** [comment]
@michalkurka could you please merge this bugfix, untill your solution will be ready? It helps me to keep the official releases of H2O without waiting for fix in the major change you mentioned.

**Comment by michalkurka** [comment]
@woj-i we will try to get this in master ASAP - probably sometime next week, this is a core change - we cannot rush the fix

**Comment by michalkurka** [comment]
Thanks again for your contribution!

**Comment by michalkurka** [comment]
@woj-i I tested this with our michrobenchmark suit, this PR introduces a performance regression, for example the benchmark NewChunkBench.writeDoubles runs twice as long as the original implementation.

I will be investigating ways to fix the issue and keep the original performance.

**Comment by kjopek** [comment]
@michalkurka Surely performance may be degraded but we compare function that may hangs under some circumstances to the one that is much better in that particular field. If we care about perfomance, there may be a way to avoid computing Math.floor twice in single loop pass.

**Comment by michalkurka** [comment]
@kjopek I see your point. I put together an alternative solution: https://github.com/h2oai/h2o-3/pull/2749

Please review. I wanted to maintain backward compatibility with the current method - I didn't want to change the results if this change is supposed to make it in the fix release.

**Comment by michalkurka** [comment]
resolved in #2749

**Pull request closed without merging**
