### PR TITLE
SE: Fix race condition in creating a transformed level-one frame

### PR DESCRIPTION
**Pull request by michalkurka**

### CODE REVIEW

**Comment by tomasfryda** [comment]
@michalkurka The logit transform isn't enabled by default in this PR so the tests won't probably show any error on this PR. However, I ran it locally with logit transform enabled and I got this:

```java
java.lang.AssertionError:  null vec: $04ffe5040000ffffffff$_91ba3aeb4971fdc4a3ba946e392346ed; index: 0
	at water.fvec.Frame.<init>(Frame.java:161)
	at water.fvec.Frame.<init>(Frame.java:141)
	at water.fvec.Frame.<init>(Frame.java:136)
	at water.fvec.Frame.add(Frame.java:634)
	at hex.ensemble.StackedEnsemble.addModelPredictionsToLevelOneFrame(StackedEnsemble.java:158)
	at hex.ensemble.StackedEnsemble$StackedEnsembleDriver.prepareLevelOneFrame(StackedEnsemble.java:257)
	at hex.ensemble.StackedEnsemble$StackedEnsembleDriver.prepareLevelOneFrame(StackedEnsemble.java:298)
	at hex.ensemble.StackedEnsemble$StackedEnsembleDriver.computeImpl(StackedEnsemble.java:358)
	at hex.ModelBuilder$Driver.compute2(ModelBuilder.java:246)
	at water.H2O$H2OCountedCompleter.compute(H2O.java:1600)
	at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
	at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
	at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1477)
	at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
```

**Comment by michalkurka** [comment]
@tomasfryda thanks, what is the best way to reproduce this?

**Comment by tomasfryda** [comment]
@michalkurka not sure if this is the best way but it is fast enough to reproduce it.

```diff
+++ b/h2o-automl/src/main/java/ai/h2o/automl/modeling/StackedEnsembleStepsProvider.java
@@ -113,6 +113,9 @@ public class StackedEnsembleStepsProvider
                 stackedEnsembleParameters._metalearner_fold_column = buildSpec.input_spec.fold_column;
                 stackedEnsembleParameters._metalearner_nfolds = buildSpec.build_control.nfolds;
 
+                if(aml().getResponseColumn().isCategorical())
+                    stackedEnsembleParameters._metalearner_transform = StackedEnsembleParameters.MetalearnerTransform.Logit;
+
```

```diff
+++ b/h2o-py/tests/testdir_misc/pyunit_explain.py
@@ -526,15 +526,15 @@ def test_learning_curve_for_algos_not_present_in_automl():
 
 
 pyunit_utils.run_tests([
-    test_get_xy,
-    test_explanation_single_model_regression,
-    test_explanation_automl_regression,
-    test_explanation_list_of_models_regression,
-    test_explanation_single_model_binomial_classification,
+    # test_get_xy,
+    # test_explanation_single_model_regression,
+    # test_explanation_automl_regression,
+    # test_explanation_list_of_models_regression,
+    # test_explanation_single_model_binomial_classification,
     test_explanation_automl_binomial_classification,
-    test_explanation_list_of_models_binomial_classification,
-    test_explanation_single_model_multinomial_classification,
-    test_explanation_automl_multinomial_classification,
-    test_explanation_list_of_models_multinomial_classification,
-    test_learning_curve_for_algos_not_present_in_automl,
+    # test_explanation_list_of_models_binomial_classification,
+    # test_explanation_single_model_multinomial_classification,
+    # test_explanation_automl_multinomial_classification,
+    # test_explanation_list_of_models_multinomial_classification,
+    # test_learning_curve_for_algos_not_present_in_automl,
     ])

```

**Comment by michalkurka** [comment]
@tomasfryda thanks, on it!

**Review by tomasfryda — APPROVED** [review]
Thank you @michalkurka! 

Locally, it passes the tests related to the metalearner transform.

**Review by sebhrusen — APPROVED** [review]
thanks @michalkurka

**Pull request merged**
