### PR TITLE
Fix (mathematical) typos in PCA documentation

### PR DESCRIPTION
**Pull request by mathemage**
- correct formula for :math:`C_{y}`
- use :math:`\times` for matrix dimensions
- correct formula for eigenvector
- fix :math:`\over` with :math:`\frac{}{}`
- replace :math:`\sum` with :math:`\Sigma`
- fix missing ')' and misplaced '`' in 'SVD (locally)'
- add missing '='
- remove redundant parentheses for left singular vectors

### CODE REVIEW

**Comment by mathemage** [comment]
@arnocandel @wendycwong @mmalohlava 
Can you review, please?

**Comment by mathemage** [comment]
@arnocandel Hi, Arno! Can you merge or is there a problem?

**Comment by arnocandel** [comment]
Yes, will merge once all reviewers approve.

**Comment by mathemage** [comment]
@arnocandel 
> Yes, will merge once all reviewers approve.

Are there any other reviewers? Is it @wendycwong whom I have mentioned? Because I don't see anyone else under "Reviewers" on the right.

**Pull request merged**
