### PR TITLE
[PUBDEV-5048] Progress bar fix for Zeppeling and DBC

### PR DESCRIPTION
**Pull request by jakubhava**

### CODE REVIEW

**Comment by jakubhava** [comment]
Thanks for review @st-pasha ! To be honest, I haven't tried to see all the consequences, just applied the suggested fix from https://0xdata.atlassian.net/browse/PUBDEV-5048.

Do you think that it is safe to apply these changes only if we run in notebook environment ? ( IPython, Zeppelin )

**Comment by st-pasha** [comment]
If the problem is that someone replaces `sys.stdout` with a class that has no `isatty` method, then simply checking for the presence of that method should be sufficient:
```
if not hasattr(sys.stdout, "isatty"):
    sys.stdout.isatty = lambda: False
```
If you want to detect that you're in a Jupyter / Ipython notebook, then the following code would do the trick:
```
try:
    import IPython
    import ipykernel
    ipy = IPython.get_ipython()
    if ipy:
        if isinstance(ipy, IPython.terminal.interactiveshell.TerminalInteractiveShell):
            # IPython Terminal
        elif isinstance(ipy, ipykernel.zmqshell.ZMQInteractiveShell):
            # Jupyter Notebook
        else:
            # unknown? (shouldn't happen, unless they create new kind of notebook)
except ImportError:
    # Regular terminal (or file)

```

**Comment by jakubhava** [comment]
Amazing! Thanks a lot @st-pasha

**Comment by jakubhava** [comment]
@st-pasha updated the change, verified in Zeppelin and works just fine with this fix.

**Pull request merged**
