### PR TITLE
Implements "SuperMOJO" for k-LIME

### PR DESCRIPTION
**Pull request by michalkurka**

### CODE REVIEW

**Comment by ledell** [comment]
Is this a "SuperPOJO" or "SuperMOJO"?  If the latter, we should edit the title of this PR. Great name, btw. ;-)

**Comment by michalkurka** [comment]
@ledell SuperMOJO, thanks! I will use the same approach for stacked ensembles

**Comment by michalkurka** [comment]
@h2o-ops please test!

**Comment by michalkurka** [comment]
@h2o-ops please test!

**Comment by michalkurka** [comment]
@st-pasha thank you. Yes, we will need a mojoland test for both k-LIME and k-means. GLM still doesn't have it either. I will plan a jira to this sprint.

**Pull request merged**
