### PR TITLE
Update to be consistent with imported Jetty version

### PR DESCRIPTION
**Pull request by jbentley1**
To review, compare against the [Jetty implementation](https://raw.githubusercontent.com/eclipse/jetty.project/jetty-9.4.40.v20210413/jetty-server/src/main/java/org/eclipse/jetty/server/Response.java). This brings things current to the version of Jetty being imported.

https://h2oai.atlassian.net/browse/PUBDEV-8802

### CODE REVIEW

**Comment by michalkurka** [comment]
thank you @jbentley1 - I will take a look

**Comment by jbentleyEG** [comment]
Here is the changes that were originally made in that file, which I copied over into the updated version https://github.com/h2oai/h2o-3/commit/e92776121155bc40e46dc0dd0ac64a7676358402

**Comment by michalkurka** [comment]
Hi @jbentley1 - I don't think we can actually merge this PR as-is. The issue is that the default H2O assembly is built on Jetty 9 and the specific version is 9.4.11.v20180605. Your commit would upgrade the Response implementation to a different version which I don't think we can do without consequences.

I think the issue here is that we actually modify the class in the dependency. We should only be doing that in H2O assemblies - otherwise we can cause harm whenever someone includes H2O as a dependency but has a different Jetty version.

**Comment by michalkurka** [comment]
I will make a PR that corrects the dependencies

**Comment by michalkurka** [comment]
@jbentley1 please take a look at this PR and let me know what you think: https://github.com/h2oai/h2o-3/pull/6308

**Pull request closed without merging**
