### PR TITLE
Update/organize R docs for H2OFrame methods in R API

### PR DESCRIPTION
**Pull request by navdeep-G**
* This PR organizes frame.R into several sections: 

- Private/Internal Functions
- Frame Operations
- Time & Date
- Overload base R methods
- Assignment Operations
- Summarizing Operations
- Overloading of `h2o.*` onto functions
- Casting Operations
- Merging Operations
- *ply methods

-Added proper examples to functions that require them. Most functions have example blocks or are quite straight forward in their description.

* Other changes will come in separate PR's

### CODE REVIEW

**Comment by navdeep-G** [comment]
@ledell Other files in the R package seem to be okay in terms of organization/docs (`model.R`, `export.R`, etc.)

**Comment by ledell** [comment]
@navdeep-G My only suggestion is to make sure you are using standard R conventions for all the example code.  For example, on `h2o.runif`, there are `=` instead of `<-`.

**Comment by navdeep-G** [comment]
@ledell Will do

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Pull request merged**
