### PR TITLE
Fix a test class to be compatible with Python 2.7 syntax

### PR DESCRIPTION
**Pull request by michalkurka**

### CODE REVIEW

**Comment by Pscheidl** [comment]
You know, that's just me. I always get carried away by dreaming of thing I cannot have. Always lost in those fantasies where platforms are type-safe and compilers provide as much safety as they can by making me type one more lexeme...

**Comment by michalkurka** [comment]
yep, seems like Mr. Marty McFly-Pscheild came from some kind of a future universe or something

**Comment by Pscheidl** [comment]
https://docs.python.org/3/library/typing.html

**Comment by michalkurka** [comment]
@Pscheidl I cannot access that link with my Netscape Navigator

**Comment by Pscheidl** [comment]
I'll extract the text and ship it to you on a persistent storage ? What do you Apple folks have these days ? Is 5" floppy ok ?

**Comment by michalkurka** [comment]
@Pscheidl My PowerBook 1400 prefers Zip drives. Please ship it over using Federal Express.

**Pull request merged**
