### PR TITLE
Isax v2

### PR DESCRIPTION
**Pull request by mklechan**
Implementation of http://www.cs.ucr.edu/~eamonn/SAX.pdf  for C1 Purple Rain Team

---

This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/413)

### CODE REVIEW

**Comment by mklechan** [comment]
@h2o-ops please test

**Comment by abal5** [comment]
@h2o-ops please test

**Comment by navdeep-G** [comment]
Note: This PR needs a lot more testing from me and @mklechan side.

**Comment by mklechan** [comment]
@h2o-ops please test

**Comment by mklechan** [comment]
@h2o-ops please test

**Comment by mklechan** [comment]
@h2o-ops please test

**Comment by mklechan** [comment]
@h2o-ops please test

**Comment by navdeep-G** [comment]
@h2o-ops please test

**Comment by abal5** [comment]
@h2o-ops please test

**Comment by mklechan** [comment]
@h2o-ops please test

**Comment by mklechan** [comment]
@h2o-ops please test

**Comment by mklechan** [comment]
Added Tomas, since he did the original code review with me in person

**Comment by mklechan** [comment]
@h2o-ops please test

**Pull request merged**
