### PR TITLE
PUBDEV-5959: Client Mode Improvement [WIP!!!]

### PR DESCRIPTION
**Pull request by michalkurka**

### CODE REVIEW

**Comment by michalkurka** [comment]
@jakubhava please take look!

**Comment by jakubhava** [comment]
Will have a look ASAP at the conf, on Tuesday or Wednesday

**Comment by jakubhava** [comment]
I like the refactoring and the changes, however any pointers where to start looking on possible issues would greatly help to speed up start with this change. Thanks @michalkurka!

**Comment by jakubhava** [comment]
First thing: I will try to write a test which will simulate this behaviour

**Comment by jakubhava** [comment]
Test for this behavior done. @michalkurka you mentioned that there was some hang in the client tests, was it during R client tests?

**Comment by michalkurka** [comment]
@jakubhava there was a NPE (caused most likely by a race condition): https://github.com/h2oai/h2o-3/pull/2912#issuecomment-439529438

This issue prevented one of the clusters used in client mode testing in operating properly. The affected node was hanging and causing the test suite to timeout. I found out this can be reliably reproduced on Jenkins. Please see the history of builds on your original PR.

**Comment by jakubhava** [comment]
Closing this one in favor of https://github.com/h2oai/h2o-3/pull/3108. It is the same set of changes, just for rel-xia to follow our PR cycle

**Pull request closed without merging**
