### PR TITLE
Angela jenkins

### PR DESCRIPTION
**Pull request by angela0xdata**
PUBDEV-2922 - Adding topic for GLRM in the Algorithms section. This change includes adding the new topic, adding an image to the /images folder, and updating the data-science.rst file to include this new topic.

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/83)

### CODE REVIEW

**Comment by abal5** [comment]
Can one of the admins verify this patch?

**Comment by arnocandel** [comment]
Can you make one nice commit for all these changes?

**Comment by angela0xdata** [comment]
I'm not sure why this is including all those changes from July. Those have already been merged into master.

**Comment by arnocandel** [comment]
It might be the same changes, but from different commit hashes. Did you sync up your branch to master before making the new changes?

You can do the following to make one commit with all the diffs from your branch to current top of master (and we'll keep a backup of your current branch):

cd h2o-3
git fetch
git checkout angela_jenkins
git checkout -b backup
git checkout angela_jenkins
git diff angela_jenkins origin/master > patch
git reset hard --origin/master
git apply patch
git commit -m "PUBDEV-2922 - Adding topic for GLRM in the Algorithms section. This change includes adding the new topic, adding an image to the /images folder, and updating the data-science.rst file to include this new topic."
git push origin angela_jenkins:angela_jenkins --force-with-lease

**Comment by angela0xdata** [comment]
I sync my branch almost every day (which is all those "merge master into angela_jenkins" commits). Then when I make a change and commit to master, I perform the following:
git checkout master
git pull
git checkout angela_jenkins
git rebase master
git checkout master
git merge mybranch
git push master

**Comment by arnocandel** [comment]
Ok - I'd still love to see the entire diff in one commit though.

**Comment by angela0xdata** [comment]
Yeah, I don't know why it's only showing July 7 commits. Going to try combining them all now, though.

**Pull request merged**
