### PR TITLE
[PUBDEV-4249] Allow users to override default Python binary

### PR DESCRIPTION
**Pull request by mmalohlava**
In some environment build fails on using wrong python version.
This patch allows users to override default names for Python and Pip.

### CODE REVIEW

**Comment by mmalohlava** [comment]
Reported also in  PUBDEV-4249

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@NidhiMehta this is change which should solve your issues with Python2/Python3. You can override default python executable, however, build scripts should correctly pick version of python which you are  using.

**Comment by mmalohlava** [comment]
So far no clue here. In some env, Python distro is picked wrongly:

Python on cmd line:
```
nidhimehta$ python --version
Python 3.6.1
```

Python reported when gradle launches `/bin/sh -c python --version`:
```
nidhimehta$ ./gradlew -q :h2o-py:pythonVersion
PyUnit smoke test (run.py --wipeall --testsize s)...
R smoke test (run.py --wipeall --testsize s)...
[TERM:xterm-256color, JAVA_HOME:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home, TERM_PROGRAM_VERSION:326, SHLVL:1, APP_ICON_55933:/Users/nidhimehta/h2o-3/media/gradle.icns, TERM_PROGRAM:Apple_Terminal, __CF_USER_TEXT_ENCODING:0x1F5:0:0, PWD:/Users/nidhimehta/h2o-3, TERM_SESSION_ID:53E8CF04-1870-4A25-8917-450EFE1642D7, LOGNAME:nidhimehta, __CHECKFIX1436934:1, SSH_AUTH_SOCK:/tmp/launch-mLgKOC/Listeners, LD_LIBRARY_PATH:/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/lib/server, JAVA_MAIN_CLASS_55933:org.gradle.wrapper.GradleWrapperMain, OLDPWD:/Users/nidhimehta/h2o-3, SHELL:/bin/bash, TMPDIR:/var/folders/n2/xvqbyvlj5c1_cqk7hmxl__bm0000gn/T/, SECURITYSESSIONID:186a5, APP_NAME_55933:Gradle, PATH:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/texbin, DISPLAY:/tmp/launch-DKmVcw/org.macosforge.xquartz:0, USER:nidhimehta, HOME:/Users/nidhimehta, Apple_PubSub_Socket_Render:/tmp/launch-3W6NQV/Render, LANG:en_US.UTF-8]
Python 2.7.5```

**Comment by jakubhava** [comment]
in sparkling water we are doing this trick : `return isWindowsBased() ? ['cmd', '/c'] + args : ['/usr/bin/env'] + args` here https://github.com/h2oai/sparkling-water/commit/1a15ce2257a8f1cb71b08c02bbaa706efcb34956

**Comment by jakubhava** [comment]
@h2o-ops please test!

**Comment by jakubhava** [comment]
@NidhiMehta Can you please test if the latest state of this branch fixes the issue for you?

**Comment by jakubhava** [comment]
Right now this branch has conflicts so I'm removing the release label. However, @NidhiMehta can you please test that the issues you were having are fixed ? This seems like a useful fix so would be nice to proceed with it

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Pull request merged**
