### PR TITLE
Added MethodRule implementation, some junits require it.

### PR DESCRIPTION
**Pull request by vpatryshev**
A bunch of tests started suddenly failing, complaining about this (MethodRule not implemented); added.

### CODE REVIEW

**Comment by mmalohlava** [comment]
It seems like configuration problem? Why some junits need it?

**Comment by vpatryshev** [comment]
I have no clue why it suddenly happened; Anmol did not know either.
I had a large tests failure (couple of dozens), so why not make sure it'll
never happen again?

Thanks,
-Vlad

**Comment by mdymczyk** [comment]
@mmalohlava @vpatryshev  Those errors are because we have too many JUnit versions on the classpath (4.8.2, 4.10, 4.11 and the one we are using in H2O - 4.12). We need to remove the older versions from our classpath and it should be ok.

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@mdymczyk fixing the build system is one thing, but the code more tolerant to versions than we have before is an important thing to have. OTOH, I'll appreciate it if you go ahead and fix all junit versions on all build machines. The thing is, then we'll have to watch for them changing all the time.

**Comment by mmalohlava** [comment]
agree with @mdymczyk - we need just to make sure that dependencies does not include wrong version of junit. It is part of gradle build subsystem.

**Comment by mdymczyk** [comment]
@vpatryshev 1) MethodRule is a deprecated class in the JUnit version we're using (4.12) 2) you don't need to change junit versions manually on any machine, you just need to exclude them in our `gradle` script since they are pulled as transitive dependenceis. The current state of affairs is simply bad.

**Comment by vpatryshev** [comment]
@mdymczyk we can always remove this as soon as our build system is updated. OTOH, we don't know what version of JUnit our customers have; they may want to build it too. Keeping compatibility with Java6 is a much heavier problem, I think, but we do it.

**Comment by mdymczyk** [comment]
@vpatryshev we pull JUnit libraries during the test step, customers don't need to have them installed anywhere... Also JUnit is build with JDK 1.5 so no need to worry.

**Comment by vpatryshev** [comment]
@mdymczyk do you imply that our build script is wrong then?

**Comment by mdymczyk** [comment]
@vpatryshev yes. Your fix might work on our jenkins, it might even work most of the time since it just implements an interface but the correct way should be to keep only one JUnit version in our system, if you have multiple versions of the same library on your classpath it's just asking for trouble.

The best would be to do `configurations.all { transitive = false }` but that's a bit drastic so let's start small.

**Pull request closed without merging**
