### PR TITLE
[GH-15629] Fixed typo changed core-sit.xml to core-site.html

### LINKED ISSUE #15629: Fix Typo on Hadoop Introduction page
https://docs.h2o.ai/h2o/latest-stable/h2o-docs/faq/hadoop.html#can-i-configure-hdfs-multiple-times

Screenshot 2023-07-11 at 17 40 07

The name of the file should be `core-site.xml`

### PR DESCRIPTION
**Pull request by Ashwani132003**
Close #15629

### CODE REVIEW

**Comment by Ashwani132003** [comment]
@mn-mikke please check it, Thanks!!

**Review by mn-mikke — DISMISSED** [review]
LGTM

**Comment by mn-mikke** [comment]
@Ashwani132003 Please rebase your change against `rel-3.42.0`. it would be good to ship it with the next fix release.

**Review by hannah-tillman — APPROVED** [review]
Thank you for the fix :)

**Pull request closed without merging**
