### PR TITLE
Ensemble - Weights Column

### PR DESCRIPTION
**Pull request by DustinVerzal**
The changes modify some of the functions within H2O's ensemble code to allow for models and performance to utilize weights. Learners will inherit the weights_column value defined in the ensemble model.

### CODE REVIEW

**Comment by dianjunren** [comment]
Hello, thanks for the effort to bring weights_column to the ensemble code. It's most useful to me. 

I got an error when I used your code in my script when I run the example from here. (http://learn.h2o.ai/content/tutorials/ensembles-stacking/). 

The reason is likely due to that your edit inadvertently deleted this line: 
`Z$y <- training_frame[,c(y)]` 
from ensemble.R file. around line 153. I added this line back, and your code works without an error. 

Let me know if that make sense, or if I overlooked something.

Thanks,

**Comment by DustinVerzal** [comment]
Glad to hear it was of use! Good catch on that, you're definitely right, I must have copy pasted my code into there incorrectly. I made the edit to the branch/pull request!

**Comment by dianjunren** [comment]
Thank you very much!

**Comment by ledell** [comment]
Hi @DustinVerzal, I'll have a chance to look at this next week.  We are actually in the process of moving the ensemble code into the Java backend (and into the h2o R & Python packages), so I am prioritizing that right now over h2oEnsemble updates.  See [this PR](https://github.com/h2oai/h2o-3/pull/554) for details.  Sorry for the delay and thanks for the PR!

**Comment by DustinVerzal** [comment]
Sounds good, @ledell! Ooh, thanks for sending that link over. I'm definitely looking forward to being able to monitor the process of ensembles through H2O Flow.

**Pull request closed without merging**
