### PR TITLE
[PUBDEV-3609] Recognize session-scoped $-ids in Rapids.

### PR DESCRIPTION
**Pull request by st-pasha**
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/421)

### CODE REVIEW

**Comment by st-pasha** [comment]
@h2o-ops please test

**Comment by abal5** [comment]
@h2o-ops please test

**Comment by st-pasha** [comment]
@h2o-ops please test

**Comment by st-pasha** [comment]
@arnocandel Yes, this is new.
Right now the `$` character is not legal to use in any `Key`. With this change if you try to use an id of the form `$smth` in Rapids, it will be automatically translated into `smth~session_id` making it a legal key. The intention here is that instead of passing Rapids expressions of the form 
    
    (tmp= py1_ses791gwr (+ 1 (tmp= py2_ses_791gwr (cols frame [0]))))

one would instead use a much simpler form

    (tmp= $py1 (+ 1 (tmp= $py2 (cols frame [0]))))

Not only it is easier to read, but is also easier to reuse in another session.

**Pull request merged**
