### PR TITLE
[WIP] Debugging PR test failures.

### PR DESCRIPTION
**Pull request by mmalohlava**
The commit:
  - Increases timeout for 1st test run before all junits.
  - Extracts "dkv cleaner" anonymous task into a private static class

Based on logs of failing jobs: the anonymous MRTask caused cloud lock.
Relevant portion of failure:
```
1) hex.AAA_PreCloudLock
java.lang.RuntimeException: Cloud size under 4
    at water.H2O.waitForCloudSize(H2O.java:1588)
    at water.TestUtil.stall_till_cloudsize(TestUtil.java:74)
    at water.TestUtil.stall_till_cloudsize(TestUtil.java:62)
    at hex.AAA_PreCloudLock.setup(AAA_PreCloudLock.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

Suspicious boot log message sequence:
```
11-28 14:50:25.170 172.16.2.143:45014    11808  main      INFO: Registered parsers: [GUESS, ARFF, XLS, SVMLight, CSV]
11-28 14:50:25.171 172.16.2.143:45014    11808  main      INFO: Registered 0 extensions in: 0mS
11-28 14:50:30.206 172.16.2.143:45014    11808  main      INFO: Registered: 136 REST APIs in: 5035mS
11-28 14:51:00.311 172.16.2.143:45014    11808  FJ-1-15   INFO: Locking cloud to new members, because water.TestUtil$1
11-28 14:51:12.061 172.16.2.143:45014    11808  FJ-126-15 INFO: Cloud of size 4 formed [/172.16.2.143:45008, /172.16.2.143:45010, /172.16.2.143:45012, /172.16.2.143:45014]
EE
```

Explanation:
  - EE means the first AAA_PreCloudLock failed
  - the test was block 30sec (=timeout for test clouding)
  - the first task executed on the cluster for `water.TestUtil$1` (DKV cleaner task)

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/558)

### CODE REVIEW

**Comment by arnocandel** [comment]
are you saying that 30 seconds wasn't enough, but it needs 90 seconds for that first test?

**Comment by mmalohlava** [comment]
Yup, based on logs, it was not able to cloud up in 30sec. I am just curious what happened if i increase timeout on pre-lock. However, the last iteration failed directly...

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
Oki, i am going to close this PR since GitHub is still considering a new branch as the old branch...

**Comment by mmalohlava** [comment]
Update, the backend PR system lost DNS - so it was unable to test

**Pull request closed without merging**
