### PR TITLE
update flow to version 0.6.1

### PR DESCRIPTION
**Pull request by micahstubbs**
This PR adds: 

+ 🐛  **fix:** error messages & stacktraces from the *h2o-3* backend render in the Flow UI [#134](https://github.com/micahstubbs/drift/pull/134)

+ 🐛  **fix:** model output now renders for custom algos [#136](https://github.com/micahstubbs/drift/pull/136)

+ a new [roomscale](https://support.steampowered.com/kb_article.php?ref=2001-UXCM-4439) scatterplot data visualization ✨   

screen shot 2017-02-07 at 4 39 15 pm
screen shot 2017-02-07 at 4 39 28 pm
screen shot 2017-02-07 at 4 39 48 pm

+ a new top-level Plot menu  

screen shot 2017-02-06 at 10 06 44 pm

### CODE REVIEW

**Comment by micahstubbs** [comment]
@arnocandel made a new clean PR.  we can wait for the tests to run again, but they should all pass like before on #857

**Comment by micahstubbs** [comment]
@arnocandel to answer the other question, this PR only changes `h2o-web/bower.json` because all it does is update Flow.  there are no other changes to `h2o-3`

**Comment by arnocandel** [comment]
Hard to review the changes of a release version :) I guess we'll just have to see how the "new" Flow behaves for Deep Water / XGBoost etc.

**Comment by micahstubbs** [comment]
@arnocandel agree with that.  I'm happy to invest the time to make sure that this client stays current with new algos we add to `h2o-3`. That said, most new algos should be supported out of the box.

**Pull request merged**
