### PR TITLE
PUBDEV-8014: Add num_of_features argument to explain's varimp

### PR DESCRIPTION
**Pull request by tomasfryda**
https://h2oai.atlassian.net/browse/PUBDEV-8014

Add ability to limit the number of features shown in the varimp_heatmap.

### CODE REVIEW

**Comment by sebhrusen** [comment]
`num_of_features`: this `of` is a bit ugly, isn't it? not common at API level…

`n_features` (a la sklearn)? `num_features`?
cc: @ledell

**Comment by ledell** [comment]
@sebhrusen I think `num_of_features` was used already somewhere in H2O and that's why it was re-used, is that right, @tomasfryda?

**Review by sebhrusen — COMMENTED** [review]
Looks good, I just don't like the name of the new param.

**Comment by sebhrusen** [comment]
>  I think `num_of_features` was used already somewhere in H2O

@ledell that's sad, it's one of those words that I would consider as 100% noise: imo API names should always try to be as concise as possible.
Apparently used for `varimp` and `std_coef` only… probably out of scope to rename this then.

**Review by sebhrusen — APPROVED** [review]

**Review by ledell — APPROVED** [review]
Works as expected, thanks!

**Comment by ledell** [comment]
```{r}
> aml <- h2o.automl(y = "Species", training_frame = as.h2o(iris), max_models = 5)
> h2o.varimp_heatmap(aml, num_of_features = 2)
```
Screen Shot 2022-03-24 at 11 41 31 PM

**Pull request merged**
