### PR TITLE
adding support for HDP 2.5

### PR DESCRIPTION
**Pull request by abal5**
added support for HDP 2.5

### CODE REVIEW

**Comment by abal5** [comment]
removed the R file changes

**Comment by mmalohlava** [comment]
Syntactically it looks ok, but did we try that to run on actual cluster? And run full suite of tests?

Two generic comments:
  - I still believe that releasing a new package per distribution is wasting of resources - we should be able to release for hadoop 2.2, 2.4, 2.6. 2.7 (as similar products are doing) and that  should be enough. However, tom would like to release per hadoop distro.
  - we should figure out how to test this kind of distribution

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by tomkraljevic** [comment]
> I still believe that releasing a new package per distribution is wasting of resources - we should be able to release for hadoop 2.2, 2.4, 2.6. 2.7 (as similar products are doing) and that should be enough. 

I disagree.
The customer expects to see his or her version of distribution there.
We get asked this at least once a week.
I also do like compiling against the exact same bits as the real distribution.

**Comment by mmalohlava** [comment]
@tomkraljevic I have to disagree :)

 - generating assembly for each hadoop distribution complicates build process and increase build time. It also complicates builds of "Kuba's cluster"
 - we are not testing them at all - i do not see any HDP2.5 tests in our jenkins :-/ 
 - at the end for each hadoop distribution we need to know which hadoop version it is bundling and then select a "random" version from hadoop provider. WHY this commit is build on top of the version `2.7.1.2.4.0.0-169` ? Why this version and not `-171` or any other build version? 
 - we are not using any hadoop distribution specific features or do we? There is NO reason to compile against HDP version here...
 - for customers we can still need to preserve mapping "HDP2.5 -> hadoop 2.7" and show them on download page. It is much more easier then extending build process.
    - Furthermore, we would be able to capture multiple "hadoop provider versions" by a single build.

I really would like to know a technical reason why we need to "compile against the exact same bits as the real distribution.".

**Comment by tomkraljevic** [comment]
@mmalohlava agree, kubacluster release process is an interesting consideration i haven't thought about yet.

compiling against the same exact bits, to a degree, is how we get away with not testing them individually.  because there are almost never issues.  the actual commit is less important because in hadoopland they are good about not breaking APIs on incremental bugfix releases.

copying a generic "hadoop2.7" to "hdp2.5" at the end would be OK if we are convinced we have a process that work.  it is important for the customer to see "hdp2.5".

if there are distro specific things, it would be related around orc/parquet/avro, etc.  i don't actually know.

how to release kubacluster is a good discussion once we're all back in the office...

**Pull request merged**
