### PR TITLE
[PUBDEV-3321] Allow arbitrary S3 connection end point/region.

### PR DESCRIPTION
**Pull request by mmalohlava**
The fix:
  - exposes system property "sys.ai.h2o.persist.s3.endPoint" which can override default
  S3 connection end point. For example, `java -Dsys.ai.h2o.persist.s3.endPoint="https://localhost:9000" -jar h2o.jar`

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/164)

### CODE REVIEW

**Comment by mmalohlava** [comment]
The motivation is to connect to API provided by Minio S3 implementation.

**Comment by badscooter23** [comment]
Should we also expose the region parameter?

**Comment by mmalohlava** [comment]
Yes, i will do that in PR update.

**Comment by arnocandel** [comment]
can this be merged?

**Comment by mmalohlava** [comment]
I would like it put into release - just need to be approved.

**Comment by badscooter23** [comment]
This fix is allowing us to specify multiple new configuration parameters which are needed if we are going to us Minio (an open source AWS S3 compatible object store) as an alternative to AWS S3 or S3  bound through HDFS...  

The THREE new config parms that we theoretically need to specify are:

- **endpoint** (to point at a minio server instance overriding the fact that today the endpoint is hardcoded to be AWS S3)

- **enable path style** which overrides the default S3 behavior to expose every bucket as a full DNS enabled path (recommended by Minio; technically not a required parm)

- **region** which allows the user to name their minio server instance as a “region” explicitly. S3 has regions (obviously)… minio servers can be assigned a region name… this appears to be mostly “descriptive” (not sure what functional value it provides). By default (through the S3 apis) the region is us-east-1 and minio observes the same default

The fixes Michal put in enable a H2O user to speficify all three config values via the java cmd line using the this syntax

`-Dsys.ai.h2o.persist.s3.endPoint="play.minio.io:9000"`
`-Dsys.ai.h2o.persist.s3.enable.path.style=true`
`-Dsys.ai.h2o.persist.s3.region="us-east-1"`

In addition to the three parms above, a user would need to specify the accessKeyId and secretKey for S3 the “normal” way

`-Daws.accessKeyId="Q3AM3UQ867SPQQA43P2F"`
`-Daws.secretKey="zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"`

The AWS accessKeyId and seecretKey config parms are not new, they (obviously) pre-existed for AWS users

Only endpoint, enable path style, and region are new.

I (scott) have done some (a decent amount, but not exhaustive) testing

To support the testing I created a script which will start and H2O cluster (on one node only, standalone - it does not handle clustering or alternative backends e.g. Hadoop)

The cluster will default all the parms to work with the publicly available [play.minio.io](url) cluster

There is even a bucket (currently called scott) where I uploaded the Airlines data set (just for some simple testing). You can browse the public minio environment by just clicking [play.minio.io:9000](url)

NOTES:

- region appears to be bugged today (ie: if you specify `-Dsys.ai.h2o.persist.s3.region="us-east-1"` you will get an error); the root cause appears to be that specifying region overrides the endpoint (it appears the “order matters).

-in general the current scheme has limitations… you can specify only ONE S3 endpoint… so a user/customer could either read data from AWS S3 or Minio S3 (they could not read data from both); to address this we need to decide on a syntax and implement additional changes…

**Pull request merged**
