### PR TITLE
Fix for PUBDEV-5931 cannot resolve netlib dependency when building fr…

### PR DESCRIPTION
**Pull request by jbentleyEG**
…om Maven with XGBoost

[https://0xdata.atlassian.net/browse/PUBDEV-5931](https://0xdata.atlassian.net/browse/PUBDEV-5931)

### CODE REVIEW

**Comment by michalkurka** [comment]
@h2o-ops please test

**Comment by michalkurka** [comment]
@jbentleyEG perfect! thank you for the contribution

**Comment by jbentleyEG** [comment]
@michalkurka You are welcome. It's my first open source pull request.

**Comment by michalkurka** [comment]
Mr. Jenkins, please test!

**Comment by michalkurka** [comment]
Merged, @jbentleyEG congratulations on your first open source contribution!

**Pull request merged**
