### PR TITLE
PUBDEV-8879: removed SW booklet from download page

### PR DESCRIPTION
**Pull request by hannah-tillman**
For: [PUBDEV-8879](https://h2oai.atlassian.net/browse/PUBDEV-8879)

I believe this is is the only place I need to remove it from. Please let me know if I'm missing/need to change anything.

### CODE REVIEW

**Review by mn-mikke — APPROVED** [review]
LGTM, thanks!

**Comment by mn-mikke** [comment]
There are also some occurrences of SparklingWaterBooklet.pdf in https://github.com/h2oai/h2o-3/blob/master/h2o-docs/src/product/faq/general.rst (line 303 and 382)

**Comment by hannah-tillman** [comment]
> There are also some occurrences of SparklingWaterBooklet.pdf in https://github.com/h2oai/h2o-3/blob/master/h2o-docs/src/product/faq/general.rst (line 303 and 382)

@marek-mihok Thank you for pointing this out -- I'll make a new ticket for it. I think I'm just going to update the link for the citation for the SW booklet. There doesn't seem to be a bibliography section in the SW user guide, anyways, so it'll be nice to have it somewhere. I should also update all the other citation links to use https...

**Comment by marek-mihok** [comment]
> @marek-mihok Thank you for pointing this out 
@hannah-tillman I think you wanted to tag other Marek - @mn-mikke

**Review by michalkurka — APPROVED** [review]
Thank you!

**Pull request merged**
