### PR TITLE
Sometimes I encounter chunks in categorical columns, which are all NA…

### PR DESCRIPTION
**Pull request by eeckstrand**
… (with chunk type of C0DChunk). When trying to rbind compatible frames with these NA chunks, the assertion in AstRBind.java ~ line 238 triggers (java.lang.RuntimeException: java.lang.AssertionError: Input chunk (class water.fvec.C0DChunk) has float, but is expected to be categorical). Is it possible to loosen the assertion?

### CODE REVIEW

**Comment by navdeep-G** [comment]
Proposed solution is here: https://github.com/h2oai/h2o-3/commit/a67bdf34494fa223f55d75cae2d26003d7eeeb33

**Comment by jakubhava** [comment]
@navdeep-G it this change final or should we postpone it ?

**Comment by navdeep-G** [comment]
@jakubhava i have another PR that addresses this, but please leave open and we will put into the release. https://github.com/h2oai/h2o-3/pull/1194

**Comment by jakubhava** [comment]
@navdeep-G I think it's better to close this PR if you have already new replacement. The links to this PR would still work, what do you think ? I'm removing the 4release label from here and adding it to https://github.com/h2oai/h2o-3/pull/1194

**Pull request closed without merging**
