### PR TITLE
PUBDEV-6758: added glrm to hadoop smoke test

### PR DESCRIPTION
**Pull request by wendycwong**
This PR completes task in JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6758?filter=-1

After talking to Honza, we have decided to add a GLRM test to hadoop smoke test.

### CODE REVIEW

**Comment by honzasterba** [comment]
does the INTERNAL prefix do anything? will the test run?

**Comment by wendycwong** [comment]
Honza:  It is format that we use for old hadoop test.  I will remove it.

**Comment by wendycwong** [comment]
I noticed that hadoop smoke test is not part of the jenkins test for PR.  How do I make sure it actually works?

**Comment by honzasterba** [comment]
you can add your branch to the jenkins job

**Comment by wendycwong** [comment]
Honza:

I added my branch to hadoop smoke test.  Once the test passed, I will remove it from it.

**Pull request merged**
