### PR TITLE
PUBDEV-7688 - Remove Jetty 8

### PR DESCRIPTION
**Pull request by Pscheidl**
https://0xdata.atlassian.net/browse/PUBDEV-7688

Goal of this PR is to make sure H2O always uses the latest Jetty with latest fixes, even on Hadoop, not only in Standalone builds.

1. Jetty 9 already used in standalone distribution
1. Jetty 8 still distributed inside hadoop-2 based distributions - **removed** and replaced with jetty 9.
1. Removed h2o-jetty-8 module files and removed it from the build & test pipelines
1. Migration guide already updated in https://github.com/h2oai/h2o-3/pull/4839/ for rel-zeno
1. **Keep** the abstraction layer - in future, Jetty might be swapped for any other alternative. This would keep the code changes at a somewhat lower level.

Before merging to-do list:
- run all hadoop tests (including kerberos) against this PR.

- Hadoop smoke multinode: http://mr-0xc1:8080/view/H2O-3/job/h2o-3-hadoop-multinode-pipeline/job/pavel%252Fpubdev-7688/
- Kerberos pipeline: http://mr-0xc1:8080/view/H2O-3/job/h2o-3-kerberos-smoke-pipeline/job/pavel%252Fpubdev-7688/
- Hadoop smoke: http://mr-0xc1:8080/view/H2O-3/job/h2o-3-hadoop-smoke-pipeline/job/pavel%252Fpubdev-7688/

Also tested manually on my local machine :wink: (cdh5.14 assembly - Hadoop 2.10 deployment)

Screenshot from 2020-08-10 13-59-30

Added @mn-mikke to give us green/red light regarding SW integration.

### CODE REVIEW

**Comment by michalkurka** [comment]
I would do this just on master, wdyt @Pscheidl

**Comment by Pscheidl** [comment]
> I would do this just on master, wdyt @Pscheidl

I can see no problem in that. Gives us more space.

**Comment by michalkurka** [comment]
@mn-mikke relocation in SW should be still needed (I would think), we shouldn't be publishing artifacts that bundle a (relocated) Jetty to maven.

**Comment by mn-mikke** [comment]
@Pscheidl How is it with `LdapLoginModule`? Are both namespaces for jetty-8 and jetty-9 still allowed. Or only `ai.h2o.org.eclipse.jetty.jaas.spi.LdapLoginModul`?

**Comment by mn-mikke** [comment]
@michalkurka How it's done that H2O utilizes jetty9 and runs on top of Hadoop? Do you ship jetty9 separately?

**Comment by michalkurka** [comment]
> @michalkurka How it's done that H2O utilizes jetty9 and runs on top of Hadoop? Do you ship jetty9 separately?

It is bundled (and relocated). My comment was only about artifacts published to Maven (which the Hadoop jars are not). If SW utilizes the jars directly, it doesn't need to relocate.

**Comment by mn-mikke** [comment]
I see. Thanks @michalkurka for explanation!

**Comment by Pscheidl** [comment]
@mn-mikke Users might choose to use

1. `org.eclipse.jetty.jaas.spi.LdapLoginModule` (from Jetty itself)
1. `ai.h2o.org.eclipse.jetty.plus.jaas.spi.LdapLoginModule` (H2O, simply extends the previous class).

**Comment by Pscheidl** [comment]
Nightly pipeline looks good, stopping. Other pipelines show errors, investigating.

**Comment by mn-mikke** [comment]
@Pscheidl If I'm not mistaken it was possible to use `ai.h2o.org.eclipse.jetty.jaas.spi.LdapLoginModule` without "plus" in namespace. Is it still possible?

**Comment by Pscheidl** [comment]
Not anymore. That one is related to Jetty 8 and should not be used - our documentation recommends `ai.h2o.org.eclipse.jetty.plus.jaas.spi.LdapLoginModule` for years. Unfortunately.

**Comment by Pscheidl** [comment]
Great, I found the issue. Just configuration. Running tests once again before merging to make sure no other problems arise.

**Review by honzasterba — APPROVED** [review]
lgtm

**Comment by Pscheidl** [comment]
Closing due to inactivity. Feel free to reopen at any time please.

**Pull request closed without merging**
