### PR TITLE
[PUBDEV-3894] [PUBDEV-3895] Fix binary comparisons on time columns

### PR DESCRIPTION
**Pull request by st-pasha**
This actually fixes 2 separate issues (but reported simultaneously):
1) binary comparisons did not work properly with time columns.
2) python module understood only native python `datetime` types, but not Pandas / numpy datetime objects. By supporting those we improve interoperability between our h2o module and pandas (numpy)

### CODE REVIEW

**Comment by st-pasha** [comment]
@h2o-ops please test!

**Comment by st-pasha** [comment]
@h2o-ops please test!

**Comment by st-pasha** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
Does this issue occur in the R API?

**Comment by st-pasha** [comment]
well, I don't know if R has any kind of time support, but if it does then the bug would manifest itself there too

**Pull request merged**
