### PR TITLE
PUBDEV-6508: Added validation of parameters for R Target Encoding API

### PR DESCRIPTION
**Pull request by deil87**
This PR is supposed to improve user experience of R Target Encoding API by validation of parameters and providing meaningful errors and warnings

### CODE REVIEW

**Comment by michalkurka** [comment]
@deil87 this is a good change and definitely a step in the right direction.

Do you think you can also add some backend validation? We shouldn't see NPEs coming from Java backend.

**Comment by deil87** [comment]
@michalkurka There is some validation on the backend. Messages from those exceptions are being nicely propagated to client though they contain Java-style parameters' names.  I actually think that anyway validation should be done on the client side (R/Py) whenever it is possible so that we don't even bother backend. I can improve backend validation as well but maybe It would be better to do it in a separate PR, wdyt? Python's validation could be also improved to match R's one.

**Comment by michalkurka** [comment]
sure, a new pr makes sense - I was referring to this particular exception:

```
ERROR: Unexpected HTTP Status code: 400 Bad Request (url = http://localhost:54321/99/Rapids)

java.lang.IllegalArgumentException
 [1] "java.lang.IllegalArgumentException: Name lookup of 'NULL' failed"                                                   
 [2] "    water.rapids.Env.lookup(Env.java:405)"                                                                          
 [3] "    water.rapids.ast.params.AstId.exec(AstId.java:33)"                                                              
 [4] "    water.rapids.ast.prims.mungers.AstTargetEncoderTransform.getInflectionPoint(AstTargetEncoderTransform.java:154)"
```

**Comment by meganjkurka** [comment]
@deil87 I think the target encoding transform function should work with the default parameters.  Right now if I leave the optional arguments with their default settings I will get an error.

**Comment by deil87** [comment]
Thank you @meganjkurka ! I know about this. Fixing this would require semantic change of the method and it should go to a separate PR. After our discussion in Slack I'm waiting for default parameters for hyper parameters. I pointed our that default values are different in DAI and in your previous R implementation so could you please investigate a little bit which version of default parameters is correct?

**Pull request merged**
