### PR TITLE
PUBDEV-6350: fixed rendering of multiple Confusion Matrices when using Py and R clients

### PR DESCRIPTION
**Pull request by seb-h2o**
https://0xdata.atlassian.net/browse/PUBDEV-6350

### CODE REVIEW

**Comment by seb-h2o** [comment]
will update, looks like there is the same bug with R client

**Comment by seb-h2o** [comment]
@ledell , @deil87 : this is a small one, and the build is fully green. It's rare enough to be worth a quick review, thx.

**Comment by seb-h2o** [comment]
anyone interested? @deil87 as a creator? @ledell for the R part? thank you....

**Comment by ledell** [comment]
Does anyone know why we call the list of metrics, `max_metrics`?  Max of what?

**Comment by deil87** [comment]
@ledell this is because we are looking for a threshold that maximises particular metric. So `max_metrics` is a list of metrics wrt which we are able to select optimal thresholds.

**Pull request merged**
