### PR TITLE
Improve efficiency of MRTask

### PR DESCRIPTION
**Pull request by st-pasha**
…when a set of vecs is given, avoid creating a full-fledged Frame out of them.

(waiting for tests to complete)

### CODE REVIEW

**Comment by mmalohlava** [comment]
What kind of problem are you trying to solve?

**Comment by st-pasha** [comment]
@mmalohlava The problem is this: when you do `mrTask.doAll(vec1, ..., vecN)`, then the method will first construct a new frame from these vecs, and only then run the MRTask over the new frame. However the MRTask doesn't actually need a frame for its operation -- all it needs is an array of vecs. In this regard, constructing a frame is wasteful, as it involves creating an array of string column names (which is relatively slow). Thus, this PR removes this inefficiency by making a "crippled" frame which contains vecs but not the names.

It may be that this is not the right approach. Perhaps instead of creating a "crippled" Frame, we should replace `_fr` in the MRTask with `Vec[] _vecs`...

**Comment by st-pasha** [comment]
@tomasnykodym Thanks for your suggestion, measuring performance would of course be helpful.
I added a Junit that tests the new method is indeed slightly faster than the old one. The measured difference is the following:
```
Time taken if creating the full Frame: 4300ns
Time taken if creating the vec bundle: 3570ns
```
or roughly 20% for a frame with 10000 columns and 150 rows.

**Comment by st-pasha** [comment]
@h2o-ops please test!

**Comment by st-pasha** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
LGTM.

**Comment by mmalohlava** [comment]
For me it is ok, @michalkurka @tomasnykodym can you approve this one.

**Comment by michalkurka** [comment]
My point of view is that it is potentially dangerous to use Frame as a container object for the collection of Vecs and violate the existing contracts of the Frame class. There are methods on the Frame class that require _names field to be properly initialized, in some cases it is not obvious (for an external caller) that they would not work without column names (see eg. checksum_impl(...)).

Presented performance improvement in my opinion doesn't justify the change (less than a millisecond difference for a wide dataset). Perhaps the measurements should also consider the cost of serializing & transmitting the column names over the network. This might show more significant improvement.

I like the mentioned idea of introducing _vecs field to MRTask better than this approach.

**Comment by st-pasha** [comment]
@michalkurka I'm aware that the "vecBundle" frame violates some of the internal assumptions of the `Frame` class, which means some of the methods of that object will fail if invoked (the comment on the method says so in unambiguous terms). However MRTask doesn't use any of those methods, and vecBundle isn't intended to be used anywhere outside of an MRTask. 

What is your proposal for how to proceed with this PR: merge, close, modify `MRTask` so that it uses `_vecs` instead of a `frame` ?

**Comment by michalkurka** [comment]
Right, MRTask currently doesn't use any of the methods that are affected by this change. However field "_fr" is exposed to the classes derived from MRTask and they might (in the future) be called.

I think it is worth to break the Frame's contract only if there is a significant performance benefit. If we can demonstrate the benefit then we can figure out how to implement it in the best possible way (or even merge as is).

@st-pasha, does it make sense? also @mmalohlava @tomasnykodym

**Comment by st-pasha** [comment]
@michalkurka Currently `_fr` in `MRTask` is public; it should at the very least be `protected`. There are 8 usages where this field is accessed from outside of MRTask or derived classes -- and in all those usages only the vecs of the frame are needed, not the actual frame. So we can make the field protected, and instead supply a public `vecs()` accessor.

Also you fear about accidental misuse of `_fr`, we can add `_vecs` field (similarly how we have `_keys` already), and then allow `_fr` to be null when MRTask is invoked with a list of vecs.

Alternatively, we can leave MRTask behavior as-is, but also retain the `vecBundle` method, and allow the caller to pass "vecBundle"d frame to the MRTask (that way the caller won't be likely to invoke wrong methods on the task's `_fr`).

To me even 1% of benefit is still a benefit (think about how would you feel if someone introduced a change that made all MRTasks slower by the same amount).

**Comment by michalkurka** [comment]
I don't think we can talk about the performance increase in terms of percentages. It only helps with the initialization phase and it is independent on the number of rows of the dataset.

> Alternatively, we can leave MRTask behavior as-is, but also retain the vecBundle method, and allow the caller to pass "vecBundle"d frame to the MRTask (that way the caller won't be likely to invoke wrong methods on the task's _fr).

The caller doesn't necessarily be the same person as the implementor of the MRTask. I am trying to avoid introducing a behavior that is not obvious and would possibly manifest itself in rare cases and cause some headaches.

**Comment by jakubhava** [comment]
@st-pasha @michalkurka @mmalohlava It seems like we can close this PR, or are there any changes plan regarding this ?

**Comment by jakubhava** [comment]
closing this PR after discussing with @st-pasha. It can be always re-opened if necessary.

**Pull request closed without merging**
