### PR TITLE
PUBDEV-3866 stratified split should maintain class balance

### PR DESCRIPTION
**Pull request by mklechan**
Faster version

clean up debugging code

intary to longary

### CODE REVIEW

**Comment by mklechan** [comment]
@h2o-ops please test!

**Comment by mklechan** [comment]
This fix assumes the test set size is no greater than 2^30 ~4B elements

**Comment by mklechan** [comment]
@h2o-ops please test!

**Comment by mklechan** [comment]
@h2o-ops please test!

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by mklechan** [comment]
@h2o-ops please test!

**Pull request closed without merging**
