### PR TITLE
PUBDEV-4501: updated leaderboard attribute to return an H2OFrame for …

### PR DESCRIPTION
**Pull request by laurendiperna**
…R and Python API. For R API added line to ensure metrics are numeric

### CODE REVIEW

**Comment by navdeep-G** [comment]
LGTM

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Pull request merged**
