### PR TITLE
Enriched Pair and Triple classes

### PR DESCRIPTION
**Pull request by vpatryshev**
So we are moving into the bright Future Perfect.

### CODE REVIEW

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
As I understand, all tests pass now.
Just upgraded Pair and Triple.

**Comment by mmalohlava** [comment]
Could you explain motivation for this change?

**Comment by vpatryshev** [comment]
There's a bunch or reasons.

The classes already exist, and are used here and there; but to use pairs
and triples properly we have to define equals() for them, and,
consequently, hashCode. A tuple is an element of a Cartesian product. If it
does not inherit equality from its component, it's not a Cartesian product
anymore. Implicit assumptions about what it is don't hold anymore. That's
Math.

Adding toString() just makes it easier to handle.

These classes are pretty important, and should be used wider than they are
now. Fortranish approach pf passing around arrays is both unsafe and
slower, performance-wise; it also does not allow to have heterogeneous
pairs.

I'm going to give a talk about these things some time, maybe next week.

Thanks,
-Vlad

**Pull request merged**
