### PR TITLE
[PUBDEV-4221] Checking domain structure validity.

### PR DESCRIPTION
**Pull request by vpatryshev**
Doing it in an assert, so if you turn off asserts, no extra calculations.

### CODE REVIEW

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
"Bad length" intermittent - track here - https://0xdata.atlassian.net/browse/PUBDEV-4222

The performance is good question (byte[] -> object).

@vpatryshev could you please look at performance implication (JMH?),

**Comment by vpatryshev** [comment]
The motivation is that the old code was causing "negative string length", randomly and unpredictably. The code has no tests, so there's no way to track specifically how it behaves. More, there's no reason to do it, we already have a good working implementation of domain merge logic.
Performance is not an issue here, as well as memory: these data are per table, not per row.
See also the Jira case.
https://0xdata.atlassian.net/browse/PUBDEV-4221

**Comment by wendycwong** [comment]
Last performance run after Tomas's change is:

10 Million Rows	Mean run time (s)	Run time STD (s)	Maximum run time (s) 	Minimum run time (s)
Vlad 10K factor levels, 10 Columns	3.45	2.39	13.45	1.47
Vlad 10K factor levels, 50 Columns	7.15	1.37	10.84	4.03
Vlad 10K factor levels, 100 Columns	31.87	28.04	143.39	7.52
Vlad 100K factor levels, 10 Columns	6.49	0.89	9.61	4.76
Vlad 100K factor levels, 50 Columns	23.05	2.19	29.74	18.38
Vlad 100K factor levels, 100 Columns	104.69	113.22	615.86	32.73
Vlad one million factor levels, 10 Columns	34.77	1.83	40.05	31.24
Vlad one million factor levels, 50 Columns	206.30			
				
Master 10K factor levels, 10 Columns	3.46	2.49	14.09	1.45
Master 10K factor levels, 50 Columns	7.55	1.25	10.64	4.51
Master 10K factor levels, 100 Columns	31.42	30.40	121.29	8.06
Master 100K factor levels, 10 Columns	6.41	0.92	9.64	5.00
Master 100K factor levels, 50 Columns	23.76	2.63	33.46	18.47
Master 100K factor levels, 100 Columns	97.97	98.36	547.78	32.22
Master one million factor levels, 10 Columns	33.99	1.70	38.45	30.75
master one million factor levels, 50 Columns	205.3119153

**Comment by vpatryshev** [comment]
I wonder if Arno and Michal still don't feel like they are just a pair of idiots. Are not they?

**Pull request merged**
