### PR TITLE
Make the k parameter for Clustering not required anymore (default is 1).

### PR DESCRIPTION
**Pull request by arnocandel**

### CODE REVIEW

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Pull request merged**
