### PR TITLE
Big Sort

### PR DESCRIPTION
**Pull request by cliffclick**
This PR enables the existing Matt D RadixSort code to support a plain Big Sort.
Since RadixSort is stable this Sort is stable.

90% of the work is cleanup & restructuring - and as such I suggest Matt D please code review this.
The other 10% is mostly about allowing the existing Merge & BinaryMerge code to support a missing "right frame" - there is only a left-frame in the Sort.
There is a simple wrapper in Merge.sort which takes a Frame and a list of columns to be used as sort keys.
There is a simple Rapids wrapper allowing (sort frame [col_list]) syntax.
There are some very minimalist tests.  
Largest test I ran sorted 3 cols with 30M rows, 2 are key columns, on a 5-node cluster.
No performance checking has been done - although I have several ideas to pass by Matt.
Cliff

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/60)

### CODE REVIEW

**Comment by abal5** [comment]
Currently testing this PR please wait for response from the team.

**Comment by abal5** [comment]
Currently testing this PR please wait for response from the team.

**Comment by abal5** [comment]
Currently testing this PR please wait for response from the team.

**Comment by abal5** [comment]
Currently testing this PR please wait for response from the team.

**Comment by mattdowle** [comment]
Looks very promising. But seeing an appreciable slow down on big size to work on and discuss.
PR:
image
master:
image
It's the last line I'm looking at most.
The highest with master (395s) is lower than the lowest of PR (396s) and PR has higher variance.

**Comment by cliffclick** [comment]
Ok, some more performance work has been done but not big servers in a fast i/o network cluster.  
Now only getting (modest) speedups on high-cardinality joins.  Please reprofile.

**Comment by mattdowle** [comment]
Have rerun same 8bn/9node/700GB test as above, and looks better now.  Great.
image
Let me have a look through the code changes ...

**Comment by cliffclick** [comment]
What's the status?  I've got unrelated bug fixes awaiting cliffc_jenkins getting cleared out before I can issue another PR.  Thanks

**Comment by mattdowle** [comment]
I've gone through it once in detail.  Almost all lines have changed (e.g. 700 in BinaryMerge.java).  It may have been a lot easier to do a formatting-only change separately.   A few things seem to have been removed that I'd like to keep like waitForSignalFromMatt and the detailed timing report on each RPC.  The changes of the key range overlap when merging is the main thing I think I should check.  We are missing extensive tests there so I'll add some.  Anmol is looking at why 'some checks haven't completed yet' above.   In general and overall it looks good though.
What does FFSB stand for?   It used to be MSB for Most Significant Byte.  FFSB= Frame F? Significant Byte maybe.
What's TODO "set 2 Frame and 2 int[] to NULL" and should it be done?
Why pass upp into bsearchLeft now?
Using _leftKO.at8order(j) I get I think instead of jb and jo,  but why is jb2 and jo2 added?
rightVec changed to riteSB I need to look at again.
Why access _riteSB._chunkNode[].  Isn't _ supposed to be private?
Good spot that resultLoc wasn't used in first scope so removed.
grrrsRiteRPC = null was important speed improvement before - is that definitely no longer needed?
Why rename batchSize to batchSizeUUID - I need to look again.
riteBase and leftBase changes need better merge range tests.  I can add.
BinaryMerge split into two .FFSB() calls I need to look at again.
Removed manual queue is great as per todo.

**Comment by cliffclick** [comment]
Awesome!  Obviously feel free to hack back in debugging utilities.  I bulk-yanked all the dead code without regard, but clearly some should go back.  
FFSB: Originally it had a long descriptive name, but then the name was too long and a pain for rapid development, then the structure's use and meaning changed.... i.e. FFSB is utterly meaningless.  Feel free to rename it something sensible.
TODO's: just cut-n-paste yours about didn't add any.  Maybe it's old.
upp into bsearchLeft: the arg is used.  I didn't touch the logic here.
'jb2' and 'jo2': new vars instead of reusing old ones, to be clear about which definition goes where.  Helps alot with code flow understanding.
grrsRitesRPC=null: now variable goes dead when function scope exits, and enables the GC.  As it stood the assign-to-null was always fairly dicey on when the GC got enabled; once the JIT decides a var is dead it's allowed to drop it out of all scopes anyways.
batchSizeUUID: same rename game as jb2/jo2; tell about the two different batchSize's.

**Comment by abal5** [comment]
Can one of the admins verify this patch?

**Comment by abal5** [comment]
Currently testing this PR please wait for response from the team.

**Comment by mattdowle** [comment]
Passes new tests I said I'd add : runit_merge_overlap.R
Passes Jenkins
Retested speed. A little slower but ok : 
image

**Pull request merged**
