### PR TITLE
PUBDEV-6097 - Jetty 8 updated to version 8.1.21.v20160908

### PR DESCRIPTION
**Pull request by Pscheidl**
Updated Jetty 8 to latest fix version.

### CODE REVIEW

**Comment by michalkurka** [comment]
@jakubhava that is a good suggestion

Do we need to spread the jetty version across multiple modules? Ideally h2o-jetty-8 module should be the only that defines the version. The overall goal is to be able to switch between h2o-jetty-8 and h2o-jetty-9 at assembly level. Having jetty versions in different modules would make it difficult (if not impossible).

**Comment by Pscheidl** [comment]
Removed the common Jetty version. Good idea @jakubhava . Thanks !

**Comment by Pscheidl** [comment]
@jakubhava we're solving the dependency definition and also the shape of the dependency graph as a whole in https://github.com/h2oai/h2o-3/pull/3101 .

Are you ok with that ? This PR is only about updating the verison.

**Comment by jakubhava** [comment]
@Pscheidl thanks for the note :) I'm all good with this PR

**Comment by pkozelka** [comment]
@Pscheidl @michalkurka is there anything we are waiting for, with this PR? I suggest to proceed with merge.

**Comment by jakubhava** [comment]
@Pscheidl should we merge?

**Pull request merged**
