### PR TITLE
[PUBDEV-3272] Change folder names in hadoop subproject to not contain…

### PR DESCRIPTION
**Pull request by jakubhava**
… minor versions and update actual versions to the latest one

Also fix problem that cdh5.4 was actually using artefacts from cdh5.3

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/117)

### CODE REVIEW

**Comment by mmalohlava** [comment]
Kuba, we fixed 2.4 problem in orc branch directly.

What is motivation for changing all versions? Did you test it with HDFS tests?

I am not sure if we would like to bump all version suddenly without proper in-deep testing on all platforms. It can have unpredictable impact on customers.

**Comment by mmalohlava** [comment]
Thinking about it more, syntactic changes are ok (unification 5.5.3 -> 5.5)

The changes in versions - we probably need more explanation for version bump.

**Comment by MadMan0708** [comment]
Yup, I understand. I wasn't sure whether it will be ok to update all the
versions, but your arguments make totally sense. I'll change this PR only
to fix the problem with cdh5.3 and to unify the naming.

Thanks!

**Comment by mmalohlava** [comment]
:+1: please check also buildinfo.xml (should be in `dist` directory) and if they are no references to old directories somewhere. Especially `make-dist.sh` script. Also we need to verify release script.

**Comment by MadMan0708** [comment]
@mmalohlava I've done the changes. Right now I only fixed that bug and unified the directories names. 

How can a release script can be tested, can I do it on my own or should we ask @abal5 ?

**Comment by mmalohlava** [comment]
Try to do `./make-dist` and please verify with this one as well: https://github.com/h2oai/h2o-release-scripts/blob/master/buildh2o3.sh

**Comment by MadMan0708** [comment]
Oki, testing now

**Comment by MadMan0708** [comment]
I have rebased this commit on top of master. I went carefully though each folder.

**Comment by mmalohlava** [comment]
👍 thx Kuba, orc commit only added 2 new parameters `orc*` to setup the assembly + changed the version in 5.5.2 to have hive support.

**Comment by MadMan0708** [comment]
@mmalohlava I've tested `make-dist.sh` script, works as expected

I'm ok to merge this if you're ok with that

**Comment by MadMan0708** [comment]
How does it please look, can I merge ?

**Comment by mmalohlava** [comment]
Not yet, we are still stabilizing master

**Comment by mmalohlava** [comment]
We can still have one error in HDFS run. When we get rid of it. We can proceed.

**Pull request merged**
