### PR TITLE
Revert "Add support for GRPC API to H2O-3"

### PR DESCRIPTION
**Pull request by mmalohlava**
Triggered build failure on all jobs since cannot install GRPC packages.

Reverts h2oai/h2o-3#773

### CODE REVIEW

**Comment by abal5** [comment]
We should test this on branch tests first and see what exactly needs to change, it seems to want to use py3.5 over anything else which is weird.

**Comment by spennihana** [comment]
Hey H2O team!

This is also breaking downstream projects 🔥  🚒 !

Here are two issues I ran into:
1. grpcio-tools cannot be pip installed on my mac (I get a clang error no matter what I try).

2. I am also unable to circumvent the grpcio-tools install. 
      I attempted to build a standalone h2o.jar, but each task attempted grpcio-tools.
           - :h2o-assemblies:main
           - :h2o-assemblies:main:jar  
           - :h2o-assemblies:main:shadowJar

I'm not sure if there is a task to build h2o.jar that doesn't hit grpc at some point in the DAG. Not sure if there is an easy way to explore gradle dags to discover such a task, either.

**Comment by st-pasha** [comment]
Hi @spennihana the clang issue you're running into is probably caused by using old version of `pip`. Try running `pip install --upgrade pip` and see if it resolves your issues.

**Comment by mmalohlava** [comment]
@spennihana thx for feebdack. We are going to disable GRPC part and keep it for now as an optional part of build system.

**Comment by mmalohlava** [comment]
@spennihana we disabled GPRC build at Gradle level. Can you, please, verify that your build is working? Thx!

**Comment by spennihana** [comment]
@st-pasha Thanks M. Pasha, just needed to update pip was all 🌮

**Pull request closed without merging**
