### PR TITLE
Reduces DW model training memory footprint

### PR DESCRIPTION
**Pull request by mdymczyk**
* Let the user choose not to cache data in memory for DW model training.
* Don't store the unnecessary mem field for DW KV store data

### CODE REVIEW

**Comment by mdymczyk** [comment]
@h2o-ops please test!

**Comment by mdymczyk** [comment]
@h2o-ops please test!

**Comment by mdymczyk** [comment]
@h2o-ops please test!

**Comment by mstensmo** [comment]
Looks good, trying to resolve test problems with Anmol. Will then merge

**Pull request merged**
