### PR TITLE
LoggerFactory slf4j related regression fix

### PR DESCRIPTION
**Pull request by yazun**
Fix the regression that caused DRF loading fail due to spurious dependency on slf4j when log4j2 exists. Check for water logging availability was throwing exception if slf4j was not used while loading some models. Seems like a regression between 3.30 and 3.40. https://github.com/h2oai/h2o-3/issues/6725

### CODE REVIEW

**Review by mn-mikke — APPROVED** [review]
@yazun The change looks good to me can you rebase your change against the branch `rel-3.42.0` so we could release it ASAP?

**Comment by yazun** [comment]
rebase to latest.

**Comment by yazun** [comment]
Hello @mn-mikke
Should we do anything else - was it accepted?

**Comment by BerryHoll** [comment]
Dear @mmalohlava, would you have time to review this change? I work in the academic team with @yazun and currently we have a cumbersome workaround using a custom-build jar file by @yazun , but we would much prefer to migrate to the latest version that has this fix included. Best regards, and thanks!

**Comment by mn-mikke** [comment]
@yazun I've created a new PR which is rebased on `rel-3.44.0` https://github.com/h2oai/h2o-3/pull/15918 so the change would be shipped in the next fix release. Once it gets merged, the change will be automatically propagated to the master branch. 

Sorry for the long delay. This PR got out of my attention.

**Pull request closed without merging**
