### PR TITLE
SW 156, take 2.

### PR DESCRIPTION
**Pull request by vpatryshev**
See if it crashes in pr build.

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/544)

### CODE REVIEW

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Pull request closed without merging**
