### PR TITLE
[GH-15909] Fix Jetty 9 SSL init 

### LINKED ISSUE #15909: Handle both old and new versions of Jetty despite class incompabilities related to deprecation

### PR DESCRIPTION
**Pull request by krasinski**
closes #15909

### CODE REVIEW

**Review by valenad1 — APPROVED** [review]
LGTM, thank you 👍

**Review by mn-mikke — COMMENTED** [review]
Please add some comments describing association between classes and jetty version also mention why we're doing that and why we keep old jetty.

**Review by mn-mikke — APPROVED** [review]
LGTM

**Review by valenad1 — APPROVED** [review]
LGTM, Thank you!

**Pull request merged**
