### PR TITLE
AutoBuffer - better error logging

### PR DESCRIPTION
**Pull request by vpatryshev**
AutoBuffer mysteriously fails while reading stuff. Added more information to figure out what exactly is going on.

### CODE REVIEW

**Comment by mmalohlava** [comment]
Do you have some description of failing case?

**Comment by vpatryshev** [comment]
I see obscure logs regularly, will pick something next time

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
Junit issues. See https://github.com/h2oai/h2o-3/tree/vlad_TestUtil_junit_compatibility_fix - will rerun after fixing

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
Michal, this is a small thing that helps investigate errors.

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Pull request merged**
