### PR TITLE
PUBDEV-8100: ModelDescriptor field in MOJO is not Serializable

### PR DESCRIPTION
**Pull request by michalkurka**

### CODE REVIEW

**Comment by michalkurka** [comment]
@satai the added serialization check revealed that CoxPH mojo was not serializable if model was trained with stratification, please take a look

**Comment by satai** [comment]
The code LGTM but maybe a test would be nice?

**Review by mn-mikke — APPROVED** [review]
LGTM

Strange, I would expect [this SW test](https://github.com/h2oai/sparkling-water/blob/master/ml/src/test/scala/ai/h2o/sparkling/ml/algos/H2OCoxPHTestSuite.scala#L45) to fail in case of the problem with serialization.

**Comment by satai** [comment]
@mn-mikke There is no stratification there, if I look correctly?

**Comment by mn-mikke** [comment]
> @mn-mikke There is no stratification there, if I look correctly?

Ok, got it. Thanks for your explanation!

**Comment by michalkurka** [comment]
> The code LGTM but maybe a test would be nice?
@satai the serialization is now tested in every invocation of testJavaScoring - https://github.com/h2oai/h2o-3/pull/5431/commits/23b31b0b924b6d5a6e6b1aa5ffa23d8ba8221e10

Did you mean that or something else?

**Comment by satai** [comment]
@michalkurka is stratification used there?

**Comment by michalkurka** [comment]
@michalkurka is stratification used there?

yes, that is how I found the failures

**Comment by michalkurka** [comment]
@satai I accidentally merged this already (instead of another PR) - if you have comments please send - I will incorporate in a new one

**Comment by satai** [comment]
OK for me @michalkurka

**Comment by michalkurka** [comment]
@satai thanks for confirming, sorry about the early merge

**Pull request merged**
