### PR TITLE
PUBDEV-4038 Add stddev to PDP twodimtable.

### PR DESCRIPTION
**Pull request by arnocandel**
In addition to the mean response per feature value, we want to show the standard deviation as well. This will allow to see if the model's predictions are getting less confident at a certain point

### CODE REVIEW

**Comment by arnocandel** [comment]
We will need to update Flow to show the standard deviation. @ivyywang @lo5 @micahstubbs  - how hard would that be?

**Comment by micahstubbs** [comment]
@arnocandel how would you like to show the standard deviation?  perhaps show it as **text in a metrics table** or as **an axis on a PDP Plot**?  Something else? with a clear design, it should be not be too difficult.

**Comment by arnocandel** [comment]
@micahstubbs - the TwoDimTable automatically shows up with an extra column already - so what we need is Flow to show that as an error bar on top of the line chart.

**Comment by amywang718** [comment]
@arnocandel Yup I can add it in after this merges.

**Comment by arnocandel** [comment]
@amywang718 it currently fails in models.R, and my change wasn't enough to make it work - that's why it can't be merged.

**Comment by amywang718** [comment]
Okay let me pull from the branch and check it out.

**Comment by amywang718** [comment]
Added the std dev as confidence intervals around the mean for python and R.

**Comment by arnocandel** [comment]
Thanks @amywang718!  Do we need tests for plotting with stddev = False?

**Comment by amywang718** [comment]
@arnocandel For all the runit and pyunits I had to set plot = False otherwise it won't pass. I don't know how to put the plots into the unit tests and test the plots. I can add into the partialPlot runit a test to make sure the plot points is what I expect them to be by calculating the std dev in R.

**Comment by arnocandel** [comment]
Thanks!

**Pull request merged**
