### PR TITLE
PUBDEV-1612 ORC Parser

### PR DESCRIPTION
**Pull request by tomasnykodym**
First version of orc parser. Works with some limitations (e.g. supports only primitive types, no structures/maps etc)

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/93)

### CODE REVIEW

**Comment by abal5** [comment]
Can one of the admins verify this patch?

**Comment by arnocandel** [comment]
Can you squash these commits down to maybe 10?  145 commits is a bit much to review :)

**Comment by mmalohlava** [comment]
The tests are passing even i have no orc files in small data. I can see only WARNING in the logs. The test should fail if data files are not found.

**Comment by mmalohlava** [comment]
Minor note: there are many of big files in small data.

**Pull request merged**
