### PR TITLE
PUBDEV-8284: Expose scale_pos_weight in XGBoost

### PR DESCRIPTION
**Pull request by michalkurka**

### CODE REVIEW

**Comment by ledell** [comment]
@michalkurka Just a reminder to add to the User guide page (so we don't forget): https://github.com/h2oai/h2o-3/blob/master/h2o-docs/src/product/data-science/xgboost.rst. Or maybe @hannah-tillman can do that real quickly...

**Comment by michalkurka** [comment]
> @michalkurka Just a reminder to add to the User guide page (so we don't forget): https://github.com/h2oai/h2o-3/blob/master/h2o-docs/src/product/data-science/xgboost.rst. Or maybe @hannah-tillman can do that real quickly...

not in this PR, modifying documentation in code PRs is a waste of jenkins resources

**Review by valenad1 — APPROVED** [review]
It looks good to me, thank you very much!

**Comment by michalkurka** [comment]
thanks for reviewing the PR @valenad1

**Pull request merged**
