### PR TITLE
PUBDEV-8034: Job polling will retry if connection fails

### PR DESCRIPTION
**Pull request by michalkurka**

### CODE REVIEW

**Comment by michalkurka** [comment]
Note: this also needs to be ported to rel-zermelo, however, using master as a target is easier for the review

**Comment by satai** [comment]
LGTM if the test is run in isolation

**Comment by michalkurka** [comment]
>LGTM if the test is run in isolation

@satai yes, on the client-side the tests run in isolation - a new process is spawned for each test (file), see https://github.com/h2oai/h2o-3/blob/master/scripts/run.py#L775

**Comment by michalkurka** [comment]
thanks for the review

**Pull request merged**
