### PR TITLE
PUBDEV-6006: Move Scala API to Sparkling Water

### PR DESCRIPTION
**Pull request by pkozelka**
After discussion with @jakubhava it seems that Scala API in H2O is not used by people who directly use `h2o.jar`.

It somewhat complicates build and especially IDE integration, the way it is currently wired (due to reused source roots).

This is a proposal to eliminate the API from h2o-3 and move it to Sparkling Water (the classes deleted here are still required in SW). As @jakubhava mentioned, the other part (adding them to SW) is simple.

As we will probably first want to go through the deprecation phase, I prepared  PR #2956 for that.

### CODE REVIEW

**Comment by jakubhava** [comment]
I think this is a good change. We should either have full Scala API in H2O or abandon this project and make it part of Sparkling Water.

The question is whether we should deprecate it first or is it fine to go directly without deprecation?

**Comment by pkozelka** [comment]
Very good point, I guess Michals should decide, based on their knowledge of the userbase.
For this reason, I prepared the deprecation pre-step in PR #2956 .

**Comment by jakubhava** [comment]
More I think the deprecation should be probably the first step. We can't be absolutely sure no one out there is not using this small API

**Comment by michalkurka** [comment]
There is a chance some of the tests in `h2o-scala/src/test/scala/water/udf/ScalaUdfTest.scala` are actually testing H2O code and the person who implemented those tests put it in h2o-scala because he wanted to write the tests in Scala. We will have to check whether the functionality is covered by java tests and migrate the tests to java if this suspicion is correct.

**Comment by mmalohlava** [comment]
Interesting change. However, what is motivation and value of moving code around? From my perspective, it will impact SW, H2O maven publication - but resulting value is minimal.  WDYT? 

Original idea is that Sparkling Water should be "way how to run H2O on Spark". From that perspective,  the Scala API is the way of exposing H2O Java api - there is nothing Spark/Sparkling Water specific, it is just another module in H2O-3 stack. 

Side note: The IDE problem can be solved easily via gradle+idea plugin configuration, however, it was never done, since the modules can be disabled via single click in Intelij Idea.

image

**Comment by pkozelka** [comment]
@mmalohlava - after discussion with @jakubhava we came to the opinion that this "logically" belongs to the SW project. The change here really does _not_ have any business value - which is the case of most cleanups. The value is for purity and developers comfort; removing any code that is misplaced, and mostly disturbs, is helpful.
- even if this can be done with single click, it is an extra step which needs to be done upon every reimport, plus I need to have the knowledge of this workaround, etc.
- it also slightly delays the build (loading scala and executing scalac does cost some time). Paying all these small prices (sometimes frequently, sometimes less) is definitely survivable, but I would rather ask, what value we get for that. I don't think we need to expose java api via scala modules
- but primarily: IF we happen to agree that this does not belong here THEN we should move it, no matter how small value it seems to bring

@michalkurka - you suggest that the value we get here is in the *tests* that are part of this code. _This really is_ something worth considering, but I am quite sure that this is the case for most tests that already exist in SW. So, maybe we should go the opposite direction and instead, move SW into h2o-3 repository, or at least, have their builds connected so that every commit in one runs the tests in the other? Just thinking aloud...
IMHO, having scala machinery present just for couple of tests, which can either be easily translated to java, or moved to SW with it, does not seem optimal to me.

It probably remained unnoticed, but I prepared the initial deprecation step in PR #2956 for the case that we eventually decide to move this into SW in future.

**Comment by jakubhava** [comment]
@pkozelka @mmalohlava I would like to revisit this change. 

We will need to publish h2o-scala 2.12 in order to be able to compile Sparkling Water with Scala 2.12. @mn-mikke recently created extensions projects in Sparkling Water which is used to provide extensions to H2O in order to work with Sparkling Water. Therefore all the code when it comes to external backend will be removed from SW.

I would personally really welcome moving this API to Sparkling Water as then, all Sparkling Water code is managed inside our repo and gives us more flexibility & also reducing the codebase for @michalkurka 

From technical point of view, this change can be done really quickly & I think it is safe. I would start with merging the deprecation PR @pkozelka created and just copy paste the required classes to sparkling-water-core and remove dependency for h2o-scala in our code.

When it comes to API, I don't think there are users using H2O via this Scala API. I think this is mainly for Sparkling Water.

Please let me know what do you think. @mn-mikke @mmalohlava @michalkurka.

**Comment by michalkurka** [comment]
> We will need to publish h2o-scala 2.12 in order to be able to compile Sparkling Water with Scala 2.12. @mn-mikke recently created extensions projects in Sparkling Water which is used to provide extensions to H2O in order to work with Sparkling Water. Therefore all the code when it comes to external backend will be removed from SW.

Moving everything related to external backend make perfect sense and improves the separation of concerns (H2O deals only with what it needs to deal with and doesn't care about SW). The h2o-scala API is however not meant just for Sparkling Water. I am just re-iterating what MM described in his comment https://github.com/h2oai/h2o-3/pull/2955#issuecomment-432338392

Having said that - I don't know of anyone who would _actually_ be using this API except for Sparkling Water.

That means I would be pragmatic about this change - if it makes it significantly easier for SW developers to have this module in the SW (you provided the example with support for Scala 2.12, are there other reasons?), I am in favor of that. There is one (tiny) hidden benefit for us: it would make migration to Gradle 6 easier as the cross-build plugin is not supported there.

> From technical point of view, this change can be done really quickly & I think it is safe. I would start with merging the deprecation PR @pkozelka created and just copy paste the required classes to sparkling-water-core and remove dependency for h2o-scala in our code.

Please see my comment here: https://github.com/h2oai/h2o-3/pull/2955#issuecomment-432337555 - what I am saying there is there was a (former) H2O engineer who wanted to write Scala tests instead of Java for testing H2O Core functionality and he added there tests to `ScalaUdfTest`. As I said in the comment, to preserve the test coverage of the H2O core classes we need to convert the relevant parts of this test suite to Java and integrate into H2O (assuming we don't want to deprecate UDF - but that is another discussion).

Regarding deprecation: We are assuming no one uses the module, theoretically, it should therefore not affect anyone. However, if this assumption is incorrect, we need to have an answer for people who will be affected - that means clearly describe what should they do instead (that could be done in a Technote for example). Depending on what the answer is we can decide whether to deprecate slowly (copy&paste to SW + keep here) or just do it (move to SW). If we can tell our users to temporarily use the artifact from SW project and start rewriting into Java - then we can do the quick approach.

**Comment by jakubhava** [comment]
Thanks @michalkurka for great summary!

I agree with you. Reasons why we would benefit from this change:
-> Easier upgrades of Scala
-> With transferring to H2O Rest API we will have our own H2OFrame class -> making this unused, but in the meanwhile, we might need to change some implementation underneath of this class.

I can propose even more pragmatic approach, before we decide what to do, or we go through deprecation phase :) I can just copy-paste the one class we actually just use from this package -> `H2OFrame` to our codebase and remove dependency on h2o-scala.

**Comment by jakubhava** [comment]
Just note: We have moved the H2OFrame and FrameOps classes to Sparkling Water to give us more flexibility. Therefore Sparkling Water no longer depends on h2o-scala in h2o-3.

**Comment by jakubhava** [comment]
> If we can tell our users to temporarily use the artifact from SW project and start rewriting into Java - then we can do the quick approach.

I would go with this approach. Starting from SW release based on 3.28.0.5, H2OFrame and FrameOps will be published in ``:sparkling-water-extensions package``.

I will port Scala tests to JAVA, create technical note about this that people should start transitioning to Java and in the meanwhile, they can use the identical class from this package.

**Pull request closed without merging**
