### PR TITLE
[PUBDEV-1270] Micro benchmarks support for H2O-core

### PR DESCRIPTION
**Pull request by mmalohlava**
The commit introduces JMH-based support for micro-benchmarking. The support is
by default disabled but can be invoked by:

```
./gradlew -PdoUBench=true :h2o-core:ubench
```
This will launch benchmarks and generate report stored
in `h2o-core/build/reports/jmh/` directory. The structure of report
is a plain CSV file:

```
"Benchmark";"Mode";"Threads";"Samples";"Score";"Score Error (99.9%)";"Unit";"Param: cols";"Param: rows"
"water.ChunkBench.colsRowsRead";"avgt";1;10;5.637806;0.044693;"ms/op";1000;1000
"water.ChunkBench.colsRowsRead";"avgt";1;10;561.605100;4.544644;"ms/op";1000;100000
"water.ChunkBench.colsRowsRead";"avgt";1;10;57.382850;0.289716;"ms/op";10000;1000
"water.ChunkBench.colsRowsRead";"avgt";1;10;6247.588900;1604.753068;"ms/op";10000;100000
"water.ChunkBench.colsRowsReadWithFinalChunk";"avgt";1;10;4.545261;0.030863;"ms/op";1000;1000
"water.ChunkBench.colsRowsReadWithFinalChunk";"avgt";1;10;450.692067;1.416793;"ms/op";1000;100000
"water.ChunkBench.colsRowsReadWithFinalChunk";"avgt";1;10;46.329032;0.247279;"ms/op";10000;1000
"water.ChunkBench.colsRowsReadWithFinalChunk";"avgt";1;10;4556.265900;53.616473;"ms/op";10000;100000
"water.ChunkBench.colsRowsReadWithTypeDispatch";"avgt";1;10;4.892451;0.042261;"ms/op";1000;1000
"water.ChunkBench.colsRowsReadWithTypeDispatch";"avgt";1;10;487.909633;5.038962;"ms/op";1000;100000
"water.ChunkBench.colsRowsReadWithTypeDispatch";"avgt";1;10;49.870490;0.210364;"ms/op";10000;1000
"water.ChunkBench.colsRowsReadWithTypeDispatch";"avgt";1;10;4906.383600;73.479700;"ms/op";10000;100000
"water.ChunkBench.colsRowsWithBulkRead";"avgt";1;10;1.611411;0.594086;"ms/op";1000;1000
"water.ChunkBench.colsRowsWithBulkRead";"avgt";1;10;143.838729;18.991037;"ms/op";1000;100000
"water.ChunkBench.colsRowsWithBulkRead";"avgt";1;10;15.094566;0.112915;"ms/op";10000;1000
"water.ChunkBench.colsRowsWithBulkRead";"avgt";1;10;1416.670300;26.315407;"ms/op";10000;100000
"water.ChunkBench.rawArrayRead";"avgt";1;10;0.865103;0.008616;"ms/op";1000;1000
"water.ChunkBench.rawArrayRead";"avgt";1;10;85.895733;0.567918;"ms/op";1000;100000
"water.ChunkBench.rawArrayRead";"avgt";1;10;9.092485;0.055540;"ms/op";10000;1000
"water.ChunkBench.rawArrayRead";"avgt";1;10;874.664350;2.781940;"ms/op";10000;100000
"water.ChunkBench.rowsColsRead";"avgt";1;10;18.486882;0.233694;"ms/op";1000;1000
"water.ChunkBench.rowsColsRead";"avgt";1;10;1609.273800;10.149139;"ms/op";1000;100000
"water.ChunkBench.rowsColsRead";"avgt";1;10;146.824827;7.188550;"ms/op";10000;1000
"water.ChunkBench.rowsColsRead";"avgt";1;10;18429.266800;558.858476;"ms/op";10000;100000
"water.KeyEqualsBench.keyEquals";"avgt";1;2;2.813257;NaN;"ns/op";;
"water.KeyEqualsBench.keyHash";"avgt";1;2;2.504290;NaN;"ns/op";;
```

The result can be optionally uploaded into S3 storage by specifying the following option `-PdoUploadUBenchResults=true`.

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/519)

### CODE REVIEW

**Comment by michalkurka** [comment]
It looks great at the first look! Cannot wait to use it.

**Comment by michalkurka** [comment]
Would it make sense to add guidance for IDEA to recognize the JHM source set?

add something like
```
apply plugin: 'idea'

sourceSets {
  jmh
}
```
see: http://mrhaki.blogspot.com/2016/03/gradle-goodness-source-sets-as-intellij.html

**Comment by mmalohlava** [comment]
Good catch! Yes! i will do a change. Thx Michal!

**Comment by michalkurka** [comment]
Looks good, i don't have further comments

**Comment by mmalohlava** [comment]
Just a comment to idea settings - the JMH is by default disabled. See `gradle.properties` - options `doUBench` - if you change it to `true` and refresh the project in idea you will be able to see `jmh`  source set.

**Comment by michalkurka** [comment]
okay, thanks, the JHM gradle plugin must handle that itself

I wanted to get it working in Idea without changing the properties since I don't want to accidentally commit the change of the flag in the future.

**Comment by mmalohlava** [comment]
yup, my strategy is to have default - which is enough for development. All advanced parts are by default disabled. I am looking into documentation if we can pass an option to gradle during idea refresh action.

**Comment by mmalohlava** [comment]
Ahh, found it: you need to setup `-Dorg.gradle.project.doUBench=true` in your Idea gradle importer and refresh project.
gradle-properties

**Comment by mmalohlava** [comment]
FYI: added option to run only subset of benchmarks:
`./gradlew -PdoUBench=true -PubenchIncludeOnly='water.Key*' :h2o-core:ubench`

**Comment by michalkurka** [comment]
Can we make the JMH source set enabled by default and just disable running it by default?

Just like with tests - you might not necessarily want to run them every time, but it is good that you still see them in your IDE and you can at least check that they compile.

If we disable JMH this way, h2o-core changes might break the benchmarks. What do you think?

**Comment by mmalohlava** [comment]
Yes, we just switch the option to `on`. it is just more complexity for regular developers having them in iDE.

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Pull request merged**
