### PR TITLE
allow to use arbitrary h2o.jar, closes PUBDEV-3534

### PR DESCRIPTION
**Pull request by jangorecki**
Very basic solution for PUBDEV-3534, as it became a blocker for PUBDEV-3689.
This PR allows to use custom defined h2o.jar in R and py packages. Path is controlled by `H2O_JAR_PATH` env var.

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/499)

### CODE REVIEW

**Comment by jangorecki** [comment]
@h2o-ops please test

**Comment by mmalohlava** [comment]
@bgallmeister @tomkraljevic @abal5 This change would allow us to do regression testing of Python API - we take master version of R/Python API - run tests, but sneak inside old jar.

**Comment by bgallmeister** [comment]
@rpeck interesting possibilities emerge.  I like the concept of new Python/R, old Jar for testing.  And vice-versa?

**Comment by jangorecki** [comment]
@mmalohlava added same logic for python

**Comment by tomkraljevic** [comment]
ok to me

**Comment by jangorecki** [comment]
@st-pasha thanks, adjusted.

**Comment by abal5** [comment]
@h2o-ops please test

**Pull request merged**
