### PR TITLE
throw a more informative exception for the user when wrapper gets a s…

### PR DESCRIPTION
**Pull request by nkarpov**
…trange value.

@tomkraljevic @tomasnykodym @arnocandel @mmalohlava @st-pasha 

Tom cautioned changes to this API should "go through the ringer", so added you all...

Motivation: when user passes in empty string for numerical feature parseDouble throws NumberFormatException. This can easily happen when filling RowData from some other store in a loop, where an empty string is a missing value (I think this makes sense). The NFE message sucks and it's not obvious what to do, so I think this at least is a little better. (customer ran into this)

Further question though: before parseDouble, the value is already NaN, so if you didn't add the feature to RowData, it will be interpreted as missing (correctly) anyways. With that behavior in place I believe it strange to throw an exception when feature value = ""... in my mind it's clearly missing... (Tom mentioned that sparse case is different somehow but that's beyond my knowledge...)

Perhaps one of these approaches next?

- either interpret value="" as missing for numericals by default
- add explicit flags like: setConvertEmptyStringToZero(true)), setConvertEmptyStringToNa(true))
- to avoid potentially adding flags for cases X,Y,Z in the future (since we already have this essentially same flag for unseen categorical to be NAs) ... create a flexible approach to let the user decide like... interpretNumerical(from, to) 

thoughts?

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/313)

### CODE REVIEW

**Comment by arnocandel** [comment]
With Deep Water, we'll be sending over actual strings to score (URLs/URIs to images, text, etc.), so I wouldn't assume that every string must be a number.

**Comment by nkarpov** [comment]
I imagine separate logic will have to be added to handle those cases. In this case the suggestion is strictly for numerical columns

`
if (domainValues == null) {
         // Column has numeric value.
         ...
`

**Comment by abal5** [comment]
@h2o-ops please re-build

**Comment by arnocandel** [comment]
This has to be revisited / merged, since i made lots of changes in that code part recently.

**Comment by tomkraljevic** [comment]
Nick, if you want to do this, create a 

PredictNumberFormatException

object that subclasses PredictException

and throw that

**Pull request merged**
