### PR TITLE
Add method to return confusion matrix as a data frame

### PR DESCRIPTION
**Pull request by navdeep-G**
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/526)

### CODE REVIEW

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by Mistobaan** [comment]
PR change is missing test

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
A lot of non related failures occurring here...

**Pull request closed without merging**
