### PR TITLE
Pasha t6

### PR DESCRIPTION
**Pull request by st-pasha**
PUBDEV-3223

This implements module to assist in parsing python files.
It also includes a bunch of irrelevant changes from other branches, because Git is stupid.

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/89)

### CODE REVIEW

**Comment by abal5** [comment]
Can one of the admins verify this patch?

**Comment by mmalohlava** [comment]
What is the motivation for the Python parser?

**Comment by st-pasha** [comment]
I need to be able to auto-generate Python code from REST API and then merge it smartly into existing scripts. In order to do this, i need a parser that is capable of telling me the structure of the  existing script.

**Comment by mmalohlava** [comment]
Ahh, I see - why not normal codegen approach - generate code which are filling well defined join-points? 

Regarding parser - does it support both Py2&Py3?

**Comment by st-pasha** [comment]
"Well-defined join-points" are usually not well-defined at all... The auto-generated piece could be complicated one, with multiple pieces that have to all fall into proper places. Moreover, I anticipate that we will want to occasionally modify the auto-generated code and the system should not overwrite any such changes. (For example just today we added some special handling for `build_age` and `build_too_old` properties. I want the code-generator to be able to recognize these pieces and not touch them. In short, it should work like magic, which is why I call the module pymagic :) )

**Comment by mmalohlava** [comment]
I see, i would be careful with modifying generating code and fitting regeneration into modifications... Guys from EMF tried that 10years ago, generating API+Impl from their models and it was not accepted at all :) but they over engineered their solution (but at least they created anti-pattern for code generation:).  At the end,  people generate only part which is changing, do not generate part which is static...

Regarding join points : they have to be well-defined (else they are useless) - for strong type languages it is easy, since you can enforce them by language constructs, for python it is probably more challenging....

**Comment by st-pasha** [comment]
My idea for the process is the following:
1) The parser analyzes the source file and creates a high-level overview of its structure. "High-level" here means that it detects such code sections as comments, docstrings, import statements, class definitions, functions, etc. The parsed object is **reversible** in the sense that you can "unparse" it and get the original code back exactly. OR you modify the parsed object, and then get the modified code back (which is more useful). This is the step covered in this PR.

2) The "magic" script looks at the parsed object and figures out which code it has to generate. Parts of the generated code will depend on the source (for example on the name of the class).

3) The new generated code is **merged into** the original parsed object. This is the trickiness. Basically I want something like git diff, only more structure-aware. For example, it's clear how to join import blocks: you just see if any imports are missing and add those lines (possibly observing the sections). Then, a class definition can be merged into the same class definition: see which methods are missing and add those (unless we detect that they are present but commented out by the user). For the existing methods I go inside and merge them line-by-line (i.e. for each line in the new code I check whether there is such line in the old code and if not I add it). If the resulting script breaks for whatever reason, the user can go there and rearrange the lines to make it work (or comment out an auto-generated line, then the script won't try to add it). 

The only controversial part are the docstrings, since they can be modified on the server, and the script has no way of knowing whether the docstring it sees right now was created by the user, or it is an old server version. So I am thinking my pymagic script will be aggressive in this case, and will overwrite the docstring entirely...

**Comment by st-pasha** [comment]
Please let me know if this is too fragile and error-prone in your opinion

**Pull request merged**
