### PR TITLE
PUBDEV-4413: Add rmse, mae, and rmsle for regression and logloss for binomial in automl leaderboard

### PR DESCRIPTION
**Pull request by navdeep-G**
* This PR adds rmse, mae, and rmsle to the leaderboard for regression runs in AutoML and logloss for binomial runs in AutoML

### CODE REVIEW

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by ledell** [comment]
Posting a copy of the output (in R) from @navdeep-G 

```
> #binomial
> fr = h2o.importFile("/Users/navdeepgill/Desktop/h2o-3/smalldata/logreg/prostate.csv")
  |===========================================================================================================================| 100%
> fr["CAPSULE"] = as.factor(fr["CAPSULE"])
> f = h2o.automl(y=2,training_frame = fr, max_runtime_secs = 5)
  |===========================================================================================================================| 100%
> f@leaderboard
                                 model_id      auc  logloss
1               DRF_model_1494279140391_3 0.864881 0.996920
2 StackedEnsemble_model_1494279140391_783 0.810714 0.517904
3             XRT_model_1494279140391_361 0.689881 0.599179
> #regression
> fr2 = h2o.importFile("/Users/navdeepgill/Desktop/h2o-3/smalldata/covtype/covtype.20k.data")
  |===========================================================================================================================| 100%
> h = h2o.automl(y=55,training_frame = fr2, max_runtime_secs = 5)
  |===========================================================================================================================| 100%
> h@leaderboard
                                 model_id mean_residual_deviance     rmse      mae    rmsle
1 StackedEnsemble_model_1494279140391_791               0.832828 0.912594 0.512087 0.222788
2             DRF_model_1494279140391_790               0.837065 0.914913 0.503059 0.224130
> #multinomial
> fr3 = as.h2o(iris)
  |===========================================================================================================================| 100%
> g = h2o.automl(y=5,training_frame = fr3, max_runtime_secs = 5)
  |===========================================================================================================================| 100%
> g@leaderboard
                                            model_id mean_per_class_error
1                        DRF_model_1494279140391_794             0.000000
2 GBM_grid__b7914cda3cc5cb15fc719dd1a1294ab1_model_1             0.000000
3 GBM_grid__b7914cda3cc5cb15fc719dd1a1294ab1_model_0             0.000000
4                        XRT_model_1494279140391_795             0.023810
5 GBM_grid__b7914cda3cc5cb15fc719dd1a1294ab1_model_3             0.023810
6 GBM_grid__b7914cda3cc5cb15fc719dd1a1294ab1_model_4             0.095238
7 GLM_grid__b7914cda3cc5cb15fc719dd1a1294ab1_model_0             0.666667
8 GLM_grid__b7914cda3cc5cb15fc719dd1a1294ab1_model_1             0.666667
```

**Comment by ledell** [comment]
@navdeep-G This PR looks good.

For posterity, here is the full list of possible model metrics, divided by task type (in case there are any others that we want to add):

**H2OBinomialMetrics**
- MSE, RMSE, logloss, mean_per_class_error, AUC, gini
- GLM only: r2, null_deviance, residual_deviance

**H2OMultinomialMetrics**
- MSE, RMSE, logloss, mean_per_class_error
- GLM only: r2, null_deviance, residual_deviance, aic

**H2ORegressionMetrics**
- MSE, RMSE, mae, rmlse, mean_residual_deviance
- GLM only: r2, null_deviance, residual_deviance, null_dof, residual_dof, aic

My suggestion would be to add "misclassification" (error) or "accuracy" to the multinomial case, but it looks like we only currently support accuracy in the binomial case via the `h2o.accuracy()` function and misclassification error for GLRM models only.

**Comment by navdeep-G** [comment]
@ledell Is MSE really needed if we already have RMSE?

**Comment by ledell** [comment]
@navdeep-G It just depends on the level of convenience we want to offer the user.  I'm not necessarily suggesting that we put all the metrics into the leaderboard at this time, I just posted the list so we could reference all our options.  

What are some of the cons of including all available metrics?  I can't think of any other than that the table is wider and would possibly wrap.  However, the cons of not including all of them is that the user has to write more code if they use one of our less-popular metrics.  

If the user wants MSE, but we only offer RMSE, then even though the leaderboard ranking will be identical, that will require more custom coding by the user.  In the case of R, not much, but still more than nothing:

```r
lb <- aml@leaderboard
lb$mse <- sapply(as.numeric(aml@leaderboard$rmse), function(m) m^2)
```
For other metrics, this is what they'd have to do:
```r
lb <- aml@leaderboard
lb$gini <- sapply(lb$model_id, function(m) h2o.giniCoef(h2o.performance(h2o.getModel(m), newdata = test)))
```
Which is actually more typing than I realized before actually typing this out.

However, even this clunky method is only possible if the user provided their own leaderboard/test frame. An issue which is not addressed, is that -- at least right now, the user has no way to retrieve the test frame that was used for the leaderboard if it was created by AutoML automatically.  So that complicates things a bit, since the user has no way to generate comparable metrics.

**Comment by navdeep-G** [comment]
@ledell Yes, I agree that getting metrics can be a pain for some. However, I think we have to include metrics that are more applicable to the masses (auc & logloss for binomial, mae,rmse, mean residual deviance, and even rmsle for regression). We can of course include every metric for every problem since its probably calculated, but it just doesn't make much sense to me, personally. I would much rather have a concise list of metrics and then see what else we can add.

**Comment by ledell** [comment]
@navdeep-G Let's merge this PR since it improves the leaderboard in it's current state, and then continue the discussion about whether or not to add all metrics on a separate JIRA/thread.

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Pull request merged**
