### PR TITLE
PUBDEV-7614: Include all available documentation in h2odriver distribution zip

### PR DESCRIPTION
**Pull request by michalkurka**

### CODE REVIEW

**Comment by angela0xdata** [comment]
@michalkurka I have a small change to make-dist in my PR to add back the index.html from the **/h2o-docs/src/front** folder (along with updates to that file and stylesheets):
https://github.com/h2oai/h2o-3/pull/4699/files#diff-c73cd4ea21296507f9e621c0a41c8d65

**Comment by bilcus** [comment]
@michalkurka Also, please ZIP the `docs-website` and let it be uploaded to S3 and link it from the download page.

**Comment by michalkurka** [comment]
> @michalkurka Also, please ZIP the docs-website and let it be uploaded to S3 and link it from the download page.

That would be another ticket

**Comment by michalkurka** [comment]
@bilcus imho this is the ticket you are referring to https://0xdata.atlassian.net/browse/PUBDEV-7431

**Comment by michalkurka** [comment]
@angela0xdata good to know - your PR was created first, you can merge first ;) 

there will be a slight conflict

**Comment by angela0xdata** [comment]
@michalkurka just merged. (And there are the conflicts :) 
Again, I just added this line:

mkdir target/docs-website/h2o-scala_2.11
cp -rp h2o-docs/src/front/* target/docs-website <- re-added the /front folder
cp -rp h2o-docs/src/product/_build/html/* target/docs-website/h2o-docs

**Comment by michalkurka** [comment]
@angela0xdata thank you, resolved

**Comment by michalkurka** [comment]
@abal5 please take a look

**Pull request merged**
