### PR TITLE
PUBDEV-6923 Demo tests that show that TE was broken as there is an inconsistency in encodings

### PR DESCRIPTION
**Pull request by deil87**
It was double checked that at this commit -> https://github.com/h2oai/h2o-3/commit/0b836a8dba0dc6ce6593e60cbdd17c24fcc07b99 given consistency tests went fine. I'm going to add another branch to show this. 

 Update:
Here is a branch forked at my last TE related commit https://github.com/h2oai/h2o-3/tree/te_is_not_broken_at_commit_0b836a8 . Consistency test is green there.

### CODE REVIEW

**Comment by Pscheidl** [comment]
## Consistency check tests
@deil87 Can you also provide us the code you've used to make it work against commit `0b836a8` ? 

Because I can reproduce this issue even against `0b836a8` really easily by adapting your test code just a tiny little bit. And at the time, you were the only one "coder" on TE, so you should know the root cause.

Both against latest master with my changes present and against the above mentioned commit `0b836a8`, **it all fails with the same error.**

```
java.lang.AssertionError: Encodings should be consistent across all attempts. Attempt number 1

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at ai.h2o.targetencoding.TargetEncoderBuilderTest.te_encoder_consistency_check(TargetEncoderBuilderTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at water.TestUtil$3$TimerStatement.evaluate(TestUtil.java:300)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

### Conclusion

Right now, there is a proof this defective behavior was already present in the commit `0b836a8` you're mentioning. At the time, you were the only code owner of TE (and still officially are to this day). Since then, no manipulation with TE logic was done. Only wrappers around it.

How to reproduce it ?

1. `git checkout TE_is_broken`
2. `git reset 0b836a8 --hard` (reset to the commit @deil87 claims to be working)
3. Apply the patch below:

```patch
Index: h2o-automl/src/test/java/ai/h2o/automl/targetencoding/TargetEncoderBuilderTest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- h2o-automl/src/test/java/ai/h2o/automl/targetencoding/TargetEncoderBuilderTest.java (revision 0b836a8dba0dc6ce6593e60cbdd17c24fcc07b99)
+++ h2o-automl/src/test/java/ai/h2o/automl/targetencoding/TargetEncoderBuilderTest.java (date 1569859396927)
@@ -1,16 +1,16 @@
-package ai.h2o.automl.targetencoding;
+package ai.h2o.targetencoding;
 
+import ai.h2o.automl.targetencoding.*;
 import org.junit.BeforeClass;
-import org.junit.Ignore;
 import org.junit.Test;
+import water.DKV;
 import water.Scope;
 import water.TestUtil;
 import water.fvec.Frame;
-import water.fvec.TestFrameBuilder;
-import water.fvec.Vec;
 
 import java.util.Map;
 
+
 import static ai.h2o.automl.targetencoding.TargetEncoderFrameHelper.addKFoldColumn;
 import static org.junit.Assert.assertTrue;
 
@@ -22,213 +22,126 @@
   }
 
   @Test
-  public void getTargetEncodingMapByTrainingTEBuilder() {
+  public void te_encoder_consistency_check(){
 
-    TargetEncoderModel targetEncoderModel = null;
     Map<String, Frame> encodingMapFromTargetEncoder = null;
     Map<String, Frame> targetEncodingMapFromBuilder = null;
-    Scope.enter();
-    try {
-      Frame fr = parse_test_file("./smalldata/gbm_test/titanic.csv");
-      Scope.track(fr);
-      String responseColumnName = "survived";
-
-      asFactor(fr, responseColumnName);
-
-      BlendingParams params = new BlendingParams(3, 1);
-      String[] teColumns = {"home.dest", "embarked"};
-
-      TargetEncoderModel.TargetEncoderParameters targetEncoderParameters = new TargetEncoderModel.TargetEncoderParameters();
-      targetEncoderParameters._withBlending = false;
-      targetEncoderParameters._columnNamesToEncode = teColumns;
-      targetEncoderParameters.setTrain(fr._key);
-      targetEncoderParameters._response_column = responseColumnName;
-
-      TargetEncoderBuilder builder = new TargetEncoderBuilder(targetEncoderParameters);
-
-      builder.trainModel().get(); // Waiting for training to be finished
-      targetEncoderModel = builder.getTargetEncoderModel(); // TODO change the way of how we getting model after PUBDEV-6670. We should be able to get it from DKV with .trainModel().get()
-       
-      // Let's create encoding map by TargetEncoder directly
-      TargetEncoder tec = new TargetEncoder(teColumns, params);
-
-      Frame fr2 = parse_test_file("./smalldata/gbm_test/titanic.csv");
-      asFactor(fr2, responseColumnName);
-      Scope.track(fr2);
-
-      encodingMapFromTargetEncoder = tec.prepareEncodingMap(fr2, responseColumnName, null);
-
-      targetEncodingMapFromBuilder = targetEncoderModel._output._target_encoding_map;
-
-      areEncodingMapsIdentical(encodingMapFromTargetEncoder, targetEncodingMapFromBuilder);
-
-    } finally {
-      removeEncodingMaps(encodingMapFromTargetEncoder, targetEncodingMapFromBuilder);
-      targetEncoderModel.remove();
-      Scope.exit();
-    }
-  }
-
-  @Test
-  public void teColumnNameToMissingValuesPresenceMapIsComputedCorrectly() {
-
     TargetEncoderModel targetEncoderModel = null;
-    Map<String, Frame> encodingMapFromTargetEncoder = null;
-    Map<String, Frame> targetEncodingMapFromBuilder = null;
-    Scope.enter();
-    try {
-      String responseColumnName = "ColB";
-      Frame fr = new TestFrameBuilder()
-              .withName("testFrame")
-              .withColNames("home.dest", "embarked", responseColumnName)
-              .withVecTypes(Vec.T_CAT, Vec.T_CAT, Vec.T_CAT)
-              .withDataForCol(0, ar("a", "b"))
-              .withDataForCol(1, ar("s", null))
-              .withDataForCol(2, ar("yes", "no"))
-              .build();
-
-      String[] teColumns = {"home.dest", "embarked"};
-
-      TargetEncoderModel.TargetEncoderParameters targetEncoderParameters = new TargetEncoderModel.TargetEncoderParameters();
-      targetEncoderParameters._withBlending = false;
-      targetEncoderParameters._columnNamesToEncode = teColumns;
-      targetEncoderParameters.setTrain(fr._key);
-      targetEncoderParameters._response_column = responseColumnName;
-      targetEncoderParameters._ignore_const_cols = false;
-
-      TargetEncoderBuilder builder = new TargetEncoderBuilder(targetEncoderParameters);
-
-      builder.trainModel().get(); // Waiting for training to be finished
-      targetEncoderModel = builder.getTargetEncoderModel(); // TODO change the way of how we getting model after PUBDEV-6670. We should be able to get it from DKV with .trainModel().get()
-
-      Map<String, Integer> teColumnNameToMissingValuesPresence = targetEncoderModel._output._teColumnNameToMissingValuesPresence;
-      assertTrue(teColumnNameToMissingValuesPresence.get("home.dest") == 0);
-      assertTrue(teColumnNameToMissingValuesPresence.get("embarked") == 1);
-    } finally {
-      removeEncodingMaps(encodingMapFromTargetEncoder, targetEncodingMapFromBuilder);
-      if (targetEncoderModel != null) targetEncoderModel.remove();
-      Scope.exit();
-    }
-  }
-
-  @Test
-  public void getTargetEncodingMapByTrainingTEBuilder_KFold_scenario(){
-
-    Map<String, Frame> encodingMapFromTargetEncoder = null;
-    Map<String, Frame> targetEncodingMapFromBuilder = null;
-
-    TargetEncoderModel targetEncoderModel = null;
-    Scope.enter();
-    try {
-      Frame fr = parse_test_file("./smalldata/gbm_test/titanic.csv");
-      String foldColumnName = "fold_column";
+
+    Frame reference = null;
+    for( int attempt = 0; attempt < 10; attempt++) {
+
+
+      Scope.enter();
+      try {
+        Frame fr = parse_test_file("./smalldata/gbm_test/titanic.csv");
+        String foldColumnName = "fold_column";
 
-      addKFoldColumn(fr, foldColumnName, 5, 1234L);
-      
-      Scope.track(fr);
-      String responseColumnName = "survived";
+        addKFoldColumn(fr, foldColumnName, 5, 1234L);
+
+        Scope.track(fr);
+        String responseColumnName = "survived";
 
-      asFactor(fr, responseColumnName);
+        asFactor(fr, responseColumnName);
 
-      BlendingParams params = new BlendingParams(3, 1);
-      String[] teColumns = {"home.dest", "embarked"};
-
-      TargetEncoderModel.TargetEncoderParameters targetEncoderParameters = new TargetEncoderModel.TargetEncoderParameters();
-      targetEncoderParameters._withBlending = false;
-      targetEncoderParameters._columnNamesToEncode = teColumns;
-      targetEncoderParameters._teFoldColumnName = foldColumnName;
-      targetEncoderParameters.setTrain(fr._key);
-      targetEncoderParameters._response_column = responseColumnName;
-
-      TargetEncoderBuilder builder = new TargetEncoderBuilder(targetEncoderParameters);
+        TargetEncoderModel.TargetEncoderParameters targetEncoderParameters = new TargetEncoderModel.TargetEncoderParameters();
+        targetEncoderParameters._response_column = responseColumnName;
+        targetEncoderParameters._fold_column = foldColumnName;
+        targetEncoderParameters._seed = 1234;
+        targetEncoderParameters._ignored_columns = ignoredColumns(fr, "home.dest", "embarked", targetEncoderParameters._response_column,
+                targetEncoderParameters._fold_column);
+        targetEncoderParameters._train = fr._key;
+        
+        TargetEncoder tec = new TargetEncoder(new String[]{ "embarked", "home.dest"});
 
-      builder.trainModel().get(); // Waiting for training to be finished
-      targetEncoderModel = builder.getTargetEncoderModel(); // TODO change the way of how we getting model after PUBDEV-6670. We should be able to get it from DKV with .trainModel().get()
+        encodingMapFromTargetEncoder = tec.prepareEncodingMap(fr, responseColumnName, foldColumnName, false);
 
-      //Stage 2: 
-      // Let's create encoding map by TargetEncoder directly
-      TargetEncoder tec = new TargetEncoder(teColumns, params);
+        printOutFrameAsTable(encodingMapFromTargetEncoder.get("home.dest"));
 
-      Frame fr2 = parse_test_file("./smalldata/gbm_test/titanic.csv");
-      addKFoldColumn(fr2, foldColumnName, 5, 1234L);
-      asFactor(fr2, responseColumnName);
-      Scope.track(fr2);
+        Frame transformedTrainWithTargetEncoder = tec.applyTargetEncoding(fr, responseColumnName, encodingMapFromTargetEncoder,
+                (byte) 1, foldColumnName, false, 0, false, targetEncoderParameters._seed);
 
-      encodingMapFromTargetEncoder = tec.prepareEncodingMap(fr2, responseColumnName, foldColumnName);
+        Frame subframe1 = transformedTrainWithTargetEncoder.subframe(new String[]{"embarked_te", "home.dest", foldColumnName, "home.dest_te"});
+        DKV.put(subframe1);
+        Frame.export(subframe1, "te_encoder" + attempt + ".csv", fr._key.toString(), true, 1)
+                .get();
 
-      targetEncodingMapFromBuilder = targetEncoderModel._output._target_encoding_map;
+        Scope.track(transformedTrainWithTargetEncoder);
 
-      areEncodingMapsIdentical(encodingMapFromTargetEncoder, targetEncodingMapFromBuilder);
+        if(reference == null) {
+          reference = transformedTrainWithTargetEncoder;
+        } else {
+          assertTrue("Encodings should be consistent across all attempts. Attempt number " + attempt,
+                  isBitIdentical(reference, transformedTrainWithTargetEncoder));
+        }
 
-    } finally {
-      removeEncodingMaps(encodingMapFromTargetEncoder, targetEncodingMapFromBuilder);
-      targetEncoderModel.remove();
-      Scope.exit();
-    }
-  }
+      } finally {
+        removeEncodingMaps(encodingMapFromTargetEncoder, targetEncodingMapFromBuilder);
+        Scope.exit();
+      }
+
+    }
 
-  @Ignore("Enable when TargetEncoderModel is a full fledged model: PUBDEV-6670")
+  }
+
   @Test
-  public void transform_KFold_scenario(){
+  public void te_builder_consistency_check() {
 
     Map<String, Frame> encodingMapFromTargetEncoder = null;
     Map<String, Frame> targetEncodingMapFromBuilder = null;
     TargetEncoderModel targetEncoderModel = null;
-    Scope.enter();
-    try {
-      Frame fr = parse_test_file("./smalldata/gbm_test/titanic.csv");
-      String foldColumnName = "fold_column";
+
+    Frame reference = null;
+    for (int attempt = 0; attempt < 10; attempt++) {
+
+      Scope.enter();
+      try {
+        Frame fr = parse_test_file("./smalldata/gbm_test/titanic.csv");
+        String foldColumnName = "fold_column";
 
-      addKFoldColumn(fr, foldColumnName, 5, 1234L);
+        addKFoldColumn(fr, foldColumnName, 5, 1234L);
 
-      Scope.track(fr);
-      String responseColumnName = "survived";
+        Scope.track(fr);
+        String responseColumnName = "survived";
 
-      asFactor(fr, responseColumnName);
+        asFactor(fr, responseColumnName);
 
-      BlendingParams params = new BlendingParams(3, 1);
-      String[] teColumns = {"home.dest", "embarked"};
-
-      TargetEncoderModel.TargetEncoderParameters targetEncoderParameters = new TargetEncoderModel.TargetEncoderParameters();
-      targetEncoderParameters._withBlending = false;
-      targetEncoderParameters._columnNamesToEncode = teColumns;
-      targetEncoderParameters._teFoldColumnName = foldColumnName;
-      targetEncoderParameters.setTrain(fr._key);
-      targetEncoderParameters._response_column = responseColumnName;
+        TargetEncoderModel.TargetEncoderParameters targetEncoderParameters = new TargetEncoderModel.TargetEncoderParameters();
+        targetEncoderParameters._response_column = responseColumnName;
+        targetEncoderParameters._fold_column = foldColumnName;
+        targetEncoderParameters._seed = 1234;
+        targetEncoderParameters._ignored_columns = ignoredColumns(fr, "home.dest", "embarked", targetEncoderParameters._response_column,
+                targetEncoderParameters._fold_column);
+        targetEncoderParameters._train = fr._key;
 
-      TargetEncoderBuilder builder = new TargetEncoderBuilder(targetEncoderParameters);
-
-      builder.trainModel().get(); // Waiting for training to be finished
-      targetEncoderModel = builder.getTargetEncoderModel(); // TODO change the way of how we getting model after PUBDEV-6670. We should be able to get it from DKV with .trainModel().get()
-      
-      long seed = 1234;
-      byte strategy = TargetEncoder.DataLeakageHandlingStrategy.KFold;
-      Frame transformedTrainWithModelFromBuilder = targetEncoderModel.transform(fr, strategy, seed);
-      Scope.track(transformedTrainWithModelFromBuilder);
-      targetEncodingMapFromBuilder = targetEncoderModel._output._target_encoding_map;
-      
-      //Stage 2: 
-      // Let's create encoding map by TargetEncoder directly and transform with it
-      TargetEncoder tec = new TargetEncoder(teColumns, params);
-
-      Frame fr2 = parse_test_file("./smalldata/gbm_test/titanic.csv");
-      addKFoldColumn(fr2, foldColumnName, 5, 1234L);
-      asFactor(fr2, responseColumnName);
-      Scope.track(fr2);
-
-      encodingMapFromTargetEncoder = tec.prepareEncodingMap(fr2, responseColumnName, foldColumnName);
+        TargetEncoderBuilder builder = new TargetEncoderBuilder(targetEncoderParameters);
+        targetEncoderModel = builder.trainModel().get();
+        
+        Frame transformedTrainWithModelFromBuilder = targetEncoderModel.transform(fr, (byte) 1, targetEncoderParameters._seed);
+        Scope.track(transformedTrainWithModelFromBuilder);
+        targetEncodingMapFromBuilder = targetEncoderModel._output._target_encoding_map;
+        printOutFrameAsTable(targetEncodingMapFromBuilder.get("home.dest"));
 
-      Frame transformedTrainWithTargetEncoder = tec.applyTargetEncoding(fr2, responseColumnName, encodingMapFromTargetEncoder, strategy, foldColumnName, targetEncoderParameters._withBlending, true, seed);
-     
-      Scope.track(transformedTrainWithTargetEncoder);
-      
-      assertTrue("Transformed by `TargetEncoderModel` and `TargetEncoder` train frames should be identical", isBitIdentical(transformedTrainWithModelFromBuilder, transformedTrainWithTargetEncoder));
+        Frame subframe = transformedTrainWithModelFromBuilder.subframe(new String[]{"embarked_te", "home.dest", foldColumnName, "home.dest_te"});
+        DKV.put(subframe);
+        Frame.export(subframe, "te_model.csv", fr._key.toString(), true, 1)
+                .get();
+
+        if (reference == null) {
+          reference = transformedTrainWithModelFromBuilder;
+        } else {
+          assertTrue("Encodings should be consistent across all attempts. Attempt number " + attempt,
+                  isBitIdentical(reference, transformedTrainWithModelFromBuilder));
+        }
 
-    } finally {
-      removeEncodingMaps(encodingMapFromTargetEncoder, targetEncodingMapFromBuilder);
-      targetEncoderModel.remove();
-      Scope.exit();
+      } finally {
+        removeEncodingMaps(encodingMapFromTargetEncoder, targetEncodingMapFromBuilder);
+        targetEncoderModel.remove();
+        Scope.exit();
+      }
+
     }
+
   }
 
 
@@ -239,11 +152,4 @@
       TargetEncoderFrameHelper.encodingMapCleanUp(targetEncodingMapFromBuilder);
   }
 
-  private void areEncodingMapsIdentical(Map<String, Frame> encodingMapFromTargetEncoder, Map<String, Frame> targetEncodingMapFromBuilder) {
-    for (Map.Entry<String, Frame> entry : targetEncodingMapFromBuilder.entrySet()) {
-      String teColumn = entry.getKey();
-      Frame correspondingEncodingFrameFromTargetEncoder = encodingMapFromTargetEncoder.get(teColumn);
-      assertTrue(isBitIdentical(entry.getValue(), correspondingEncodingFrameFromTargetEncoder));
-    }
-  }
 }
Index: h2o-core/src/test/java/water/TestUtil.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- h2o-core/src/test/java/water/TestUtil.java  (revision 0b836a8dba0dc6ce6593e60cbdd17c24fcc07b99)
+++ h2o-core/src/test/java/water/TestUtil.java  (date 1569859351211)
@@ -1131,6 +1131,12 @@
     return true;
   }
 
+  public static final String[] ignoredColumns(final Frame frame, final String... usedColumns) {
+    Set<String> ignored = new HashSet(Arrays.asList(frame.names()));
+    ignored.removeAll(Arrays.asList(usedColumns));
+    return ignored.toArray(new String[ignored.size()]);
+  }
+
   public static boolean compareFrames(final Frame f1, final Frame f2) throws IllegalStateException {
     return compareFrames(f1, f2, 0);
   }
```

4. Run `TargetEncoderBuilderTest.te_encoder_consistency_check` - result is the same stacktrace as in the latest master.

To keep changes at bare minimum and make it easier for you to spot the adaptation changes, I kept the original test code by @deil87.

**Conclusion** For now, the code example reproducible on commit `0b836a8` above proves this problem is related to Target Encoder even in earlier versions. The diff of changes did after the above-mentioned commit is second proof the origin is somewhere in the original code  - no manipulation with the internals of Target Encoder was done.

Here is a screenshot with `git log` in console to quickly demonstrate the issue exists since forever:

Snímek z 2019-09-30 17-38-39


## Test notes
The tests are not in a good shape
- Unused variables -  I already had to clean them many times from your code. Please make sure not to repeat the same mistake again and again, over and over. :warning:
- The test `te_encoder_consistency_check` leaks keys. I really have to urge this one, as such problems were fixed in production for you last time and this PR shows the same signs of problems. It's easier to focus on reproducing the real issue and hunt it down, if there are no beginner-level mistakes in the code. :warning: 

```
java.lang.AssertionError: Keys leaked: 2, cnt = 2

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at water.TestUtil.checkLeakedKeys(TestUtil.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by deil87** [comment]
@Pscheidl these tests are to show the root cause of the problem. I did not care about unused variables and leaked keys. There is no need to polish demo tests as it is a waste of time. Your "test notes" are unacceptable. Regarding tests I need some time to understand your setup and will be back soon.

**Comment by deil87** [comment]
@Pscheidl Here is a screenshoot where test passed. And there is no code "to make it work". It just worked. Only keys leaked as I did not care to remove them for the demo. There might be some reason for our different results but we  just need to find it. 
Screenshot 2019-09-30 at 18 44 36

**Comment by deil87** [comment]
@Pscheidl and what is wrong with corresponding Jira?

**Comment by Pscheidl** [comment]
@deil87 Gave you the full code and steps to reproduce - it fails on your commit. Nothing more I can do for you.

Fix it or point out where in the code is the mistake. I basically took your code and made it run on the older codebase - with no adjustments. It's up there.

**Comment by deil87** [comment]
@Pscheidl My point was that any, I stress - ANY ( your or anyone's on the project) changes that happened after mentioned commit might be a reason for the inconsistency.  I will take a look at your code and will be back.

**Comment by deil87** [comment]
@Pscheidl I found an issue with your adaptation of my test. You did not disable tracking of the `reference` frame and it was removed by Scope.exit() and of course test was failing in your version as you were comparing with empty frame.

 In my demo branch everything was fine and test was green. Leaked keys were not related to an issue I was trying to point out.  I pushed changes to the a branch `te_is_not_broken_at_commit_0b836a8`https://github.com/h2oai/h2o-3/pull/3937  and fixed key leakage to make it easier for you to see the issue.

**Comment by Pscheidl** [comment]
I used your example 1:1, did not remove or add any tracking. Just give me the code. It's simple rule: talk is cheap, show me the code. Then we can move ourselves further. 

Please give me a patch against that commit that works, as I'm unable to reproduce. With the same setup of course. Thanks.

**Comment by deil87** [comment]
@Pscheidl You did not use it 1:1. In the description of the PR there was always( from the very beginning) the link to the another branch PR with the test(my screenshoot is from that branch). Please first pay attention to the description and then make any conclusions about PR.

**Comment by Pscheidl** [comment]
You should have the right code then. Why don't you just give us a patch, like I did ? I can't see any major difference besides import adaptation.

**Comment by deil87** [comment]
@Pscheidl I gave you a branch with the code you can pull and try test without any patching. Please confirm that my test in the branch https://github.com/h2oai/h2o-3/commit/0b836a8dba0dc6ce6593e60cbdd17c24fcc07b99  is not failing. Anyone is free to choose any tools and ways to show something and my way is as good as yours. It is not the point to compare this things here.

**Comment by michalkurka** [comment]
@deil87 I just pushed a commit to this branch. I played around with Scope in order to make this test pass. Currently passes locally.

**Comment by deil87** [comment]
@michalkurka yeah, false alarm. Actually there is an issue in my Broadcast Join branch locally where I did rebase on master. My mistake here is that I did not check that frame comparison fails by the same reason. Here frame was just being removed by Scope and what is more dramatic is that I did untrack `reference` frame in the demo branch from my old commit but not here.

**Comment by michalkurka** [comment]
@deil87 ok, phew - glad it is resolved - do you want to close the 2 PRs + the jira?

**Pull request closed without merging**
