### PR TITLE
PUBDEV-3885: fixed bug so user_points parameter could be passed, incl…

### PR DESCRIPTION
**Pull request by laurendiperna**
…uded extra checks if typos in parameter init were made, updated the doc string for python and Rfor user_points, updated gen_python.py so that it returns the correct type for user_points (a H2OFrame instead of a string)

fixed typo in kmeans.R which mixed up init with user_points, added a check for the init parameter, updated the api help string for user_points to be more detailed

### CODE REVIEW

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by ledell** [comment]
@laurendiperna Do you know what the conflicts in kmeans.py are about?

**Comment by laurendiperna** [comment]
@ledell fixed the conflicts

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
test

**Pull request merged**
