### PR TITLE
PUBDEV-6732: Fix model export via java-rest-bindings

### PR DESCRIPTION
**Pull request by dietzc**
https://github.com/dietzc/h2o-3/commit/dbd30f49d5e4deb43460327ebf61857874ece07d adds a model export to the `GBM` example, which results in a failing test. https://github.com/dietzc/h2o-3/commit/9d561c97da9cd517a4c45cb7c869343fa775dcde fixes the problem by using `@Query` for non-`POST` methods.

I hope this helps.

### CODE REVIEW

**Comment by dietzc** [comment]
any update on this? https://community.h2o.ai/questions/2117/using-frames-endpoint-with-java-rest-bindings.html seems to be related.

**Comment by mdymczyk** [comment]
LGTM but paging doctor @rpeck

**Comment by entusias** [comment]
Related: https://stackoverflow.com/questions/44110233/using-h2oapi-java-bindings-to-retrieve-h2o-frame

**Comment by rpeck** [comment]
What is the failure that you were seeing before this change?

This changes all POSTs from url-form-encoded to query-string.  Query parameters are limited to 2k in IE, so large POSTs, such as ModelBuilder or Parse with lots of columns will fail.  We need to find another fix for the problem.  :-)

**Comment by dietzc** [comment]
@rpeck Thanks for the review. The failure I experienced before the fix can be reproduced if you simply ignore my second commit (first commit introduces failing test).

Also: https://stackoverflow.com/questions/44110233/using-h2oapi-java-bindings-to-retrieve-h2o-frame fails without the fix.

**Comment by dietzc** [comment]
@rpeck just wanted to check if there is anything I can do on my side at the moment?

**Comment by mdymczyk** [comment]
@rpeck doesn't this only change `GET`s from url-form-encoded to query-string and leave `POST` as it was?

**Comment by jakubhava** [comment]
This doesn't seem to be finalised yet. Postponing it into the next release.

**Comment by COA1IMB** [comment]
Are there any updates on this issue yet? I'd also highly appreciate it if this bug gets fixed

**Comment by BruceZhaoR** [comment]
@jakubhava @michalkurka @mdymczyk  any updates?

```java
water.bindings.pojos.FramesV3
...

/**
* Frames
*/
public FrameBaseV3[] frames;
```
I overrided `FrameBaseV3[]` to `FrameV3[]`,  it workded. 

``` java
FramesV3 fr = h2o.frameColumn(glmParms.trainingFrame, "y");
double[] y = fr.frames[0].columns[0].data;
```

@entusias 
maybe could solve this problem: <https://stackoverflow.com/questions/44259044/h2oapi-java-bindings-columns-endpoint-not-returning-column-metadata>.

**Comment by BruceZhaoR** [comment]
https://0xdata.atlassian.net/browse/PUBDEV-5724

**Comment by oazais** [comment]
Hello guys, any chance for this fix to be merged in a release soon?

**Comment by michalkurka** [comment]
@oazais thanks for the reminder - we will look into this for the next fix release

I made a jira to track this so that it doesn't go unnoticed: https://0xdata.atlassian.net/browse/PUBDEV-6732

**Comment by Pscheidl** [comment]
We've made some changes in https://github.com/h2oai/h2o-3/pull/3773 . It was also easier and faster for me to resolve conflicts against current master branch. The PR is based on this one. Therefore, this PR can be closed.1

Danke sehr @dietzc , your contribution is much welcome.

**Pull request closed without merging**
