### PR TITLE
Vlad c str chunk small fix

### PR DESCRIPTION
**Pull request by vpatryshev**
See [PUBDEV-3905](https://0xdata.atlassian.net/browse/PUBDEV-3905) for details

### CODE REVIEW

**Comment by vpatryshev** [comment]
Nick, pls take a look. Anmol told me to ignore those error messages (they are all unrelated artifacts).

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
Is there any jira connected to this PR?

**Comment by vpatryshev** [comment]
No; I can enter, though.

Thanks,
-Vlad

**Comment by mmalohlava** [comment]
I mean what is original motivation for the change - was it customer request, or failing jira, or detected bottle neck. It is good for tracking...

**Comment by vpatryshev** [comment]
It was a bottleneck, and while investigating, I found a bug.

Thanks,
-Vlad

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Pull request closed without merging**
