### PR TITLE
PUBDEV-5476 - Expose offset column in EasyPredictModelWrapper

### PR DESCRIPTION
**Pull request by Pscheidl**

### CODE REVIEW

**Comment by michalkurka** [comment]
Regression should also support offset column. Could you also add tests?

Would be nice we supported offset column also in the predict function. Idea: user sets the offset column name when creating the Wrapper config and the predict function takes the offset from the RowData structure passed in predict() function. WDYT?

**Comment by Pscheidl** [comment]
@michalkurka Yes, regression too. Sorry.

Let's also implement it in the predict function !

**Comment by Pscheidl** [comment]
Could this ever work, even for the Binomial as there is

```java
    throw new UnsupportedOperationException("`offset` column is not supported");
```
in method:
```java
  public double[] score0(double[] row, double offset, double[] preds) {
    throw new UnsupportedOperationException("`offset` column is not supported");
  }
```
I failed to catch this error, as there are no tests (will add, as mentioned).

**Comment by Pscheidl** [comment]
I wanted to create test and had a look around - looks like `score0` method is not '`@Overridden`' in desired classes, such as `GlmOrdinalMojoModel` or `GlmMultinomialMojoModel`.

I made several assumptions. There was a JIRA to [expose binomial only](https://0xdata.atlassian.net/browse/PUBDEV-5473). I assume the corresponding MojoModel for Binomial is `GlmMultinomialMojoModel`. If correct, then this model does not override score0 method with offset parameter, leaving it to the default `GenModel` implementation. The default GenModel's implementation throws UnsupportedOperationException.

```java
  public double[] score0(double[] row, double offset, double[] preds) {
    throw new UnsupportedOperationException("`offset` column is not supported");
  }
```

I can test it on an artificial MojoModel (we already have those in our test suite) and leave it as is. Or it can be tested properly. The we need to implemented those scoring functions as well (more work for now).

The only models implementing `score0` method with `offset` parameter are:

snimek obrazovky porizeny 2018-04-24 15-24-27

- DeepLearningModel (not MOJO)
- DeepwaterMojoModel
- DrfMojoModel
- GbmMojoModel
- XGBoostMojoModel

Do we need to implement this method in the rest of `*MojoModel` classes ?

**Comment by Pscheidl** [comment]
Finally decided to use Mockito for the job, thus added `testCompile 'org.mockito:mockito-core:2.18.3'`.

Please review.

**Comment by mmalohlava** [comment]
Off-topic note: should we generate a set of MOJOs  (for each algo and model) with each major release, and test that we can load them with latest h2o-genmodel?

**Comment by michalkurka** [comment]
@mmalohlava this is done with the "MOJO Land" tests. I am not sure if these were actually ported to pipelines - I will check.

**Comment by michalkurka** [comment]
@Pscheidl mockito is perfect for this kind of tests, good addition.

for readability purposes - it would be good to statically import Mockito.*

**Comment by Pscheidl** [comment]
@michalkurka Your Mockito is now statically import, you can drink any time !

**Pull request merged**
