### PR TITLE
Smarter NBHM.toArray

### PR DESCRIPTION
**Pull request by cliffclick**
Plus BufferedString.hashCode caches

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/44)

### CODE REVIEW

**Comment by abal5** [comment]
Can one of the admins verify this patch?

**Comment by abal5** [comment]
Can one of the admins verify this patch?

**Comment by cliffclick** [comment]
Thanks!

**Comment by srisatish** [comment]
Thank you!

**Pull request merged**
