### PR TITLE
PUBDEV-8426: GAM multiple model builds

### PR DESCRIPTION
**Pull request by wendycwong**
This PR verifies that the problem in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8426 has been fixed.  Please update to latest H2O.

### CODE REVIEW

**Review by neemah2o — APPROVED** [review]
LGTM

**Comment by michalkurka** [comment]
Thank you @wendycwong , did you check that this test would fail without fix for https://h2oai.atlassian.net/browse/PUBDEV-8407?

**Comment by wendycwong** [comment]
@michalk:  GOOD POINT.  Let me try and get back to you.  I want to know too.  I also would like to add tests to this PR.

**Comment by wendycwong** [comment]
@michalkurka I was right, this problem was fixed by the gam CV PR.  The test pass in commit d1dfa916e8a3dd13875fc0cdd1447116a4be7bd1 but failed in commit 8808cf3c24c2817fbd3e6cd007e95aab1a653ab6

commit d1dfa916e8a3dd13875fc0cdd1447116a4be7bd1
Author: wendycwong <wendy@h2o.ai>
Date:   Mon Nov 8 10:03:54 2021 -0800

    PUBDEV-8163: fix GAM CV bug (#5821)
    
    Changed Java backend so that cross-validation is run in GLM and not in GAM
    Finished adding all support to GAM CV
    Done adding python unit test from Erin
    Add custom readAll_impl method
    Added test to test serialization/de-serialization per MK suggestion
    Reformat new test and unused imports per tomf suggestion

commit 8808cf3c24c2817fbd3e6cd007e95aab1a653ab6
Merge: 26b86addf1 2bef246077
Author: Michal Kurka <michalk@h2o.ai>
Date:   Fri Nov 5 16:59:37 2021 -0400

    Merge pull request #5864 from h2oai/michalk_switch-to-mr-0xd4
    
    Use mr-0xd4 as a namenode in tests (instead of mr-0xd6) [nocheck]

**Comment by michalkurka** [comment]
@wendycwong thank you for checking!

**Review by michalkurka — APPROVED** [review]

**Pull request merged**
