### PR TITLE
[PUBDEV-3466] Do not allow AstAssign to overwrite an existing frame

### PR DESCRIPTION
**Pull request by st-pasha**
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/242)

### CODE REVIEW

**Comment by mmalohlava** [comment]
What is motivation? Does it pass tests? I think people is using this functionality.

**Comment by mmalohlava** [comment]
Will this work:

```py
 input_df = h2o.import_file(path=pyunit_utils.locate("smalldata/covtype/covtype.20k.data"))
    new_df = h2o.import_file(path=pyunit_utils.locate("smalldata/covtype/covtype.20k.data"))
    df = h2o.assign(input_df, "table_0")
    table = "table_0"
    for i in range(1,1000):
        df = h2o.get_frame(table)
        df_rbind = df.rbind(new_df)
        df_rbind = h2o.assign(df_rbind, "table_0")
```

**Comment by navdeep-G** [comment]
I think the motivation is to avoid overriding a frame's. But the use case @mmalohlava brings up is interesting, and possibly useful. We can add a flag to do this. The flag can be `override=T` by default, which shouldn't be a breaking change.

**Comment by mmalohlava** [comment]
I think it is good intention, but it is breaking change. What about tests results?

**Comment by st-pasha** [comment]
Yeah, there doesn't seem to be a good solution here...
On the one hand Michal's example shows a valid use-case (well, valid in the absence of any "in-place" rapids functions). On the other hand it's clearly very error-prone to allow the user to manipulate frame's id like this. 

(Tests seem to be failing). I may withdraw this PR; looks like it's not a no-brainer

**Comment by mmalohlava** [comment]
We should think about it little bit more: 

When should user call `h2o.assign`? There is already op `frame_id` attribute which can be used to override existing frame id...(it is calling `h2o.assign` & `rename` under the hood).  Then does it make sense to expose `h2o.assign`?

**Pull request closed without merging**
