### PR TITLE
Allow zero-chunk AppendableVec

### PR DESCRIPTION
**Pull request by cliffclick**
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/94)

### CODE REVIEW

**Comment by abal5** [comment]
Can one of the admins verify this patch?

**Comment by arnocandel** [comment]
Can you add a JUnit test to demonstrate the utility?

**Comment by cliffclick** [comment]
Ok, take another look.  Now it's an actual bug fix, plus a strengthening 
of an invariant.

VectorGroups now demand that all layouts have an equal number of 
Chunks.  This invariant was blown in a few interesting cases:
- Multifile parses; the VG had layouts for both the original 1st file 
Chunk count, plus also layouts for all files combined
- ASTRBind produces a whole new layout from whole cloth (by basically 
leaving all the data alone but arranging that the Chunks end up exactly 
as they are now, but like a Multifile parse all stitched together).
- Vec.makeCon could be asked to make multiple Chunks, but still went in 
VG_LEN1 which has only 1 Chunk

Multiple zero-length Chunks are explicitly allowed now.

Cliff

**Comment by arnocandel** [comment]
This set of commits is quite ugly, do you mind squashing them into 1 commit that contains just the diff to the current top of tree?

**Comment by mmalohlava** [comment]
We need to re-pick the changes since PR showing lot of changes already integrated in the master. 
@tomasnykodym the better view is to compare Cliff's branch with master directly - https://github.com/h2oai/h2o-3/compare/cliffc-zerochunk

**Comment by cliffclick** [comment]
Likely a few more smaller fixes coming; the runit's look like rapids 
row-slicing is showing a similar bug.

Cliff

**Comment by mmalohlava** [comment]
This is the way how to reset the branch:
```bash
git fetch origin                   # Get the latest master
git diff origin/master..origin/cliffc-zerochunk  > /tmp/patch.1 # Save the patch
git checkout cliffc-zerochunk 
git reset --hard origin/master     # Reset cliffc-zerochunk to to master state
git apply /tmp/patch.1             # Apply the save patch
git add  .                         # Add and commit modified files
git commit
```

**Comment by mmalohlava** [comment]
@tomasnykodym has some good comments ^^^

**Comment by cliffclick** [comment]
On 8/16/2016 7:41 PM, tomasnykodym wrote:

> Cliff, what's the advantage of ensuring the same number of chunks if 
> the rows-per chunk do not match? The vecs are not gonna be compatible 
> that way anyway?
>
You at least get to align by Chunks this way - and then do not have to 
move any data.  Changing the chunk borders will do that.


> Also, I see you make new vector group during parse instead of using 
> the one from the input data. That will make output to be homed to 
> different node than input and we'll be sending output data to remote 
> all the time. It should probably create new group only if it's 
> multifile, otherwise keep the one from the input.
>
Yes, I thought about that - its a good idea.

> (btw, M. Kurka had an idea to jam all the files into one virtual file 
> vec. that would save us re-distributing the output chunks and provide 
> better distribution for many small files cases).
>
This redistributes the raw text instead of the hex file?
Or are you thinking of making the "virtual file" before loading any 
data?  i.e., NFSFileVec handles a bunch of files?  Will make seeking & 
reading weird... you might have to open/read/close repeatedly for a 
single "load from disk" operation, until you fill up your raw text 
chunk.  Still could be faster than redistributing or rebalancing after 
you get a skillion tiny chunks.

Cliff

**Comment by cliffclick** [comment]
fyi, this produces:

> C:\Users\Cliff\Desktop\h2o-3 [cliffc-zerochunk ↓]> git apply /tmp/patch.1
> fatal: unrecognized input

for me, and my workspace has been reset.

The patch file looks entirely sane however.

Cliff

**Comment by mmalohlava** [comment]
@cliffclick i rebased the changes on top of master to get rid of merge conflicts. The backup i shared inside cliffc-zerochunk-backup. Also pushed for testing to verify nothing was lost during merge.

**Comment by arnocandel** [comment]
@cliffclick - Can you add a JUnit test to demonstrate the utility (or where the old behavior was wrong)?

**Comment by arnocandel** [comment]
where do we stand on this? i'd like to know better what the benefits of this PR are...

**Comment by mmalohlava** [comment]
CC: @tomasnykodym

**Comment by vpatryshev** [comment]
At least it has more type safety.

Thanks,
-Vlad

**Comment by cliffclick** [comment]
This ensures:
- all layouts in a VectorGroup have the same count of Chunks, which means at least MRTask,map is called uniformly (otherwise MRTask will crash on mixed-layouts)
- No layouts have zero chunks.
- Most 1-chunk layouts use the default small VectorGroup.VG_LEN1

**Comment by arnocandel** [comment]
Can you add a JUnit test to demonstrate the utility (or where the old behavior was wrong)?

**Comment by cliffclick** [comment]
Not really.  On H2O startup & first touch with multiple unrelated 
datasets you can get conflicting chunk counts on the same layout... 
which leads to crashes down the line when mixing Vec's from same 
VectorGroup but different chunk counts.  Would require launching an H2O 
instance, then probing it from multiple places e.g. python processes.

Once the original layouts get built, H2O starts re-using them and is 
stable.  I.e., if no crash on startup, then no crash.

Also fixed is making lots of unrelated VG's for 1-chunk tiny datasets.  
Happens a lot in testing, and then leads to silly incompatibilities 
(which, if run from Rapids triggers auto-rebalance, which does nothing 
productive but makes life slower and more complex).  If run from custom 
Java code and not Rapids, you get incompatibilities (mixing VG's) for 
tiny files for no good reason.  This one can probably get a JUnit that 
does something (probably making 2 small constant Vecs, and verify they, 
being small, use the same VG_LEN1 VG instead of a new one).


Cliff

**Comment by arnocandel** [comment]
rebased to master - will merge soon.

**Comment by arnocandel** [comment]
Lots of tests are failing....

**Comment by cliffclick** [comment]
Nifty, what's the link?
And thx for not dropping this, it's actually a well needed bit of 
internal stability

Cliff

**Comment by arnocandel** [comment]
pyunit_mojo.py fails with
Server error java.lang.AssertionError:
  Error: java.lang.AssertionError: Input chunk (class water.fvec.C0DChunk) has float, but is expected to be categorical
  Request: None

**Comment by arnocandel** [comment]
Retesting now.

**Comment by arnocandel** [comment]
still fails with the same error:
  Error: java.lang.AssertionError: Input chunk (class water.fvec.C0DChunk) has float, but is expected to be categorical
  Request: None

**Comment by cliffclick** [comment]
Sorry just back from Chicago with a raging cold; I'll look at thjis as I can

Cliff

**Comment by arnocandel** [comment]
Just rebased on top of master, let's wait for the test results.

**Comment by st-pasha** [comment]
@h2o-ops please test!

**Comment by abal5** [comment]
@h2o-ops please test

**Comment by arnocandel** [comment]
Just rebased again, let's see what Jenkins says this time.

**Comment by mmalohlava** [comment]
Merge or Close?

**Comment by navdeep-G** [comment]
What is the status of this? @mmalohlava @arnocandel

**Comment by arnocandel** [comment]
Testing again.

**Comment by arnocandel** [comment]
Test Result (2 failures / +2)
r_suite.pyunit_mojo.py
r_suite.pyunit_unique.py

**Pull request closed without merging**
