### PR TITLE
PUBDEV-5296: Add import/export utility functions in Java

### PR DESCRIPTION
**Pull request by michalkurka**
@ledell I changed the suggested names of the utility functions to import/export. It better matches the corresponding endpoints in the REST API.

### CODE REVIEW

**Comment by michalkurka** [comment]
@jakubhava can you please update the utility functions in SW?

**Comment by jakubhava** [comment]
@michalkurka sure thing! I will prepare PR which can be merged when 3.18.0.1 is out

**Comment by michalkurka** [comment]
@h2o-ops please test!

**Comment by michalkurka** [comment]
Renamed

**Pull request merged**
