### PR TITLE
PUBDEV-5894 adding cdh 6 support

### PR DESCRIPTION
**Pull request by abal5**

### CODE REVIEW

**Comment by michalkurka** [comment]
@michal-raska please review - I see changes in your code as well

**Comment by michal-raska** [comment]
@michalkurka yes, I pushed one commit, which makes build of smoke image for CDH 6.0 possible. However it still doesn't build, because of the issue I mentioned earlier.

**Comment by seb-h2o** [comment]
@michal-raska 
> CDH 6.0.0 is based on Apache Hadoop 3.0.
CDH 5 is the current stable release, based on Apache Hadoop 2.3.0 or later.

cf. https://www.cloudera.com/documentation/enterprise/6/release-notes/topics/rg_cdh_6_version_packaging_download.html
 I think this answers your question about hadoop-client, besides the snapshot client in the repo dates from 2016...

**Comment by michal-raska** [comment]
@seb-h2o I belive we already did upgrade to the new client lib. Please see h2o-hadoop/h2o-cdh6.0/build.gradle. 

This is the error now: 
```
/home/jenkins/slave_dir_from_mr-0xc1/workspace/-hadoop-smoke-pipeline_cdh6-CX2FSBCNKN2WDFNRDLO3EAXUMJ2U2PLQMRHVBUAXEU4FGQJPDLDA/h2o-3/h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/mapred/H2OYARNRunner.java:10: error: package org.apache.hadoop.mapreduce.v2.app does not exist

import org.apache.hadoop.mapreduce.v2.app.MRAppMaster;
                                         ^
/home/jenkins/slave_dir_from_mr-0xc1/workspace/-hadoop-smoke-pipeline_cdh6-CX2FSBCNKN2WDFNRDLO3EAXUMJ2U2PLQMRHVBUAXEU4FGQJPDLDA/h2o-3/h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/mapred/H2OYARNRunner.java:33: error: cannot find symbol

  private static final Class NEW_APP_MASTER_CLASS = MRAppMaster.class;
                                                    ^
  symbol:   class MRAppMaster
  location: class H2OYARNRunner

/home/jenkins/slave_dir_from_mr-0xc1/workspace/-hadoop-smoke-pipeline_cdh6-CX2FSBCNKN2WDFNRDLO3EAXUMJ2U2PLQMRHVBUAXEU4FGQJPDLDA/h2o-3/h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/mapred/H2OYARNRunner.java:34: error: cannot find symbol

  private static final Class DEFAULT_APP_MASTER_CLASS = MRAppMaster.class;
                                                        ^
  symbol:   class MRAppMaster
  location: class H2OYARNRunner
```

**Comment by seb-h2o** [comment]
@michal-raska for the `MRAppMaster` compilation issue, the `mapreduce.v2.app` package is not shipped anymore with CDH6 client jar (org.apache.hadoop:hadoop-client:3.0.0-cdh6.0.0), however it is still available separately as (org.apache.hadoop:hadoop-mapreduce-client-app:3.0.0-cdh6.0.0).

this needs to be added to our h2o-mapreduce-generic module.

Another solution is to completely get rid of any reference to this MRAppMaster in our code: we don't seem to do anything useful with it anyway. cf. `H2OYarnRunner`

```java
private static final Class NEW_APP_MASTER_CLASS = MRAppMaster.class;
private static final Class DEFAULT_APP_MASTER_CLASS = MRAppMaster.class;

  private static boolean replaceDefaultAppMaster() {
    return NEW_APP_MASTER_CLASS != DEFAULT_APP_MASTER_CLASS;
  }

 if (replaceDefaultAppMaster()) {
    // do something again with NEW_APP_MASTER_CLASS
    // this can NEVER be executed given the constants above
 } 
}
```

@michalkurka I suggest to delete the code above, except if we're still planning at providing our own MR App master.
Otherwise, we need to add the dependency mentioned above

**Comment by seb-h2o** [comment]
@michal-raska any simple way to compile a specific hadoop driver?

**Comment by michal-raska** [comment]
@seb-h2o thank you! Let me add the dependency and run tests.

If you want to build specific hadoop driver then do `export H2O_TARGET=cdh6.0` for example.

**Comment by pkozelka** [comment]
this was rebased and continues as part of PR #2938

**Pull request closed without merging**
