### PR TITLE
use data.table fread-fwrite for faster io, closes PUBDEV-2844

### PR DESCRIPTION
**Pull request by jangorecki**
This will fail in CI due to missing data.table, fix to CI is in #524
rebased to recent master

### CODE REVIEW

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by jangorecki** [comment]
@h2o-ops please test!

**Comment by jangorecki** [comment]
@h2o-ops please test!

**Comment by jangorecki** [comment]
@mattdowle Error was observed in `h2o.quantile` but was not reproducible, I added some extra checks.
`h2o.quantile` uses the following:
```
res <- .newExpr("quantile", x, .num.list(probs), .quote(combine_method), weights_column)
tr <- as.matrix(t(res))
```
Second line would use fread (when active) to read single row h2o frame.

**Comment by jangorecki** [comment]
@abal5 merging this now would fail CI, first we need either `_R_CHECK_FORCE_SUGGESTS_=FALSE` in our h2o pkg checks or merging PR #566.

**Comment by abal5** [comment]
@h2o-ops please test!

**Pull request merged**
