### PR TITLE
PUBDEV-4458: Move the rest of build_control args to top-level in R API

### PR DESCRIPTION
**Pull request by ledell**

### CODE REVIEW

**Comment by mmalohlava** [comment]
@ledell 98 files changed - there is something wrong...

**Comment by ledell** [comment]
@mmalohlava Yeah, I messed up by merging master into my branch.  I assume the best way to fix is to delete the branch, create a new one and copy/paste my changes, then create a new PR.

**Comment by mmalohlava** [comment]
Yup, or you can:
1. create a backup of branch:
  ```git checkout PUBDEV-4458
        git checkout -b PUBDEV-4458-BACKUP
  ```
2. reset state of branch to master:
   ```
   git checkout PUBDEV-4458
   git fetch origin && git reset --hard origin/master
  ```
3. and cherry pick relevant commit(s):
  ```
  git cherry-pick 	1e36929 deba33a 03d8338 # pls verify
  ```
4. update this PR by overriding remote branch origin/PUBDEV-4458
   ```
   git push -f
   ```

**Comment by ledell** [comment]
Followed @mmalohlava 's steps and created a new PR here: https://github.com/h2oai/h2o-3/pull/1176

**Pull request closed without merging**
