### PR TITLE
[PUBDEV-3909][PUBDEV-4274] Add XGBoost to H2O

### PR DESCRIPTION
**Pull request by jakubhava**
This is based on https://github.com/h2oai/h2o-3/pull/699

### CODE REVIEW

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
Retesting one more time, if it is ok, i will do merge.

**Comment by arnocandel** [comment]
👍

**Comment by mmalohlava** [comment]
Merging now, there are still failing tests, however, unrelated to xgboost (AutoML or wide data slow OOM).

**Pull request merged**
