### PR TITLE
PUBDEV-3346 - Citing H2O

### PR DESCRIPTION
**Pull request by angela0xdata**
Added information about citing H2O to the H2O readme in github.

---

This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/410)

### CODE REVIEW

**Comment by angela0xdata** [comment]
@h2o-ops please retest

**Comment by ledell** [comment]
@angela0xdata The content looks good.  Do you know why some of the checks are failing?

**Comment by angela0xdata** [comment]
No idea (details link not working), but then I also don't know much about the tests in general. When this first ran, about half of the tests failed. I asked to run this again, and no only the one is failing.

**Comment by angela0xdata** [comment]
@h2o-ops please test

**Pull request merged**
