### PR TITLE
[PUBDEV-4331][SW-311] Override default MapReduce type to H2O type

### PR DESCRIPTION
**Pull request by jakubhava**
Allows us to set custom application type. Based on `mm/jira/pubdev-4331`

### CODE REVIEW

**Comment by jakubhava** [comment]
@h2o-ops please test!

**Comment by jakubhava** [comment]
@mmalohlava do you have additional changes planned for this branch or do you think we can merge ?

**Comment by jakubhava** [comment]
@h2o-ops please test!

**Comment by mmalohlava** [comment]
@jakubhava yes, more changes needed since it does not work in current state (it does not compile for all versions of Hadoop we are providing)

**Comment by mmalohlava** [comment]
@h2o-ops please test!

**Pull request merged**
