### PR TITLE
PUBDEV-5258: Add cross_validation_metrics_summary to SE

### PR DESCRIPTION
**Pull request by tomasfryda**
https://h2oai.atlassian.net/browse/PUBDEV-5258

@sebhrusen proposed in the Jira to use metaprogramming to get attributes from metalearner when they are not present in the SE. I found some issues using that approach, e.g., `varimp` is not present in SE but it is in the metalearner and I think this could be confusing. 

What we could do is to use a list of attributes that would be delegated to the metalearner, this would be useful even for R client since the API there is basically having those attributes in a `list` (`se@model$attributeName`). For that implementation, I'd override `__getattribute__` and delegate from there, it's the best dynamic solution that I thought of for now with the constraints that are imposed: 
(1) `cross_validation_metrics_summary` and possibly all other relevant attributes are implemented in the parent class, 
(2) metalearner is lazy loaded.

In this PR, I have just the simplest possible implementation without metaprogramming since I haven't found other attributes that I think should be delegated to the metalearner yet.

### CODE REVIEW

**Comment by sebhrusen** [comment]
@tomasfryda if you plan to use metaprogramming at some point, please define `__getattr__`, not `__getattribute__`: it's very easy to get it wrong with the latter one.

**Comment by tomasfryda** [comment]
> @tomasfryda if you plan to use metaprogramming at some point, please define __getattr__, not __getattribute__: it's very easy to get it wrong with the latter one.

@sebhrusen I am aware of this, unfortunately, `__getattr__` gets called after going through all the ancestors (`__mro__`)  and not finding the attribute which makes it useless in this case since the attributes (e.g. `cross_validation_metrics_summary`) already defined in the some `super()` class.

**Comment by sebhrusen** [comment]
> which makes it useless in this case since the attributes (e.g. cross_validation_metrics_summary) already defined in the some super() class.

Oh, I see. Good point!

**Comment by tomasfryda** [comment]
Looking at this comment I think the only information that we want to expose in SE from the metalearner is the CV related metrics/summaries, which should be done already in this PR (I went through the attributes of a SE created by AutoML and didn't find any other attribute where it would make sense to me to use metalearner's attributes as SE's). 

https://github.com/h2oai/h2o-3/blob/4e37c4821581078ac4fa6883ee74667fb4431cc3/h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java#L325-L349

Metrics that are different in SE and metalearner for the aforementioned reason
-----------------
* F0point5
* F1
* F2
* accuracy
* aic
* mse
* null_degrees_of_freedom
* null_deviance
* precision
* r2
* recall
* residual_degrees_of_freedom
* residual_deviance
* rmse
* roc
* sensitivity
* specificity
* tnr
* tpr
* confusion_matrix
* error
* fnr
* gains_lift
* kolmogorov_smirnov
* logloss
* max_per_class_error
* mcc
* mean_per_class_error
* missrate
* model_performance
* training_model_metrics

Unavailable in SE but available in metalearner
--------------
* varimp



If I am correct than this PR is ready to be reviewed/merged. WDYT @ledell @sebhrusen ?

**Comment by michalkurka** [comment]
@tomasfryda isn't this something that should be done on the backend? 

otherwise we need to repeat the same thing in SW as well

**Comment by tomasfryda** [comment]
@michalkurka Very good point, thank you! I completely missed the broader picture by concentrating just on python metaprogramming 🤦‍♂️

**Comment by ledell** [comment]
@tomasfryda I tried this out on your branch but I think you still need to add the CV summary to this location:  `ensemble.cross_validation_metrics_summary()` instead of `ensemble.cross_validation_metrics_summary`.

```python
import h2o
from h2o.estimators.random_forest import H2ORandomForestEstimator
from h2o.estimators.gbm import H2OGradientBoostingEstimator
from h2o.estimators.stackedensemble import H2OStackedEnsembleEstimator

h2o.init()

train = h2o.import_file("https://s3.amazonaws.com/erin-data/higgs/higgs_train_10k.csv")
x = train.columns
y = "response"
x.remove(y)
train[y] = train[y].asfactor()
nfolds = 5

my_gbm = H2OGradientBoostingEstimator(distribution="bernoulli",
                                      nfolds=nfolds,
                                      keep_cross_validation_predictions=True,
                                      seed=1)
my_gbm.train(x=x, y=y, training_frame=train)

my_rf = H2ORandomForestEstimator(ntrees=50,
                                 nfolds=nfolds,
                                 keep_cross_validation_predictions=True,
                                 seed=1)
my_rf.train(x=x, y=y, training_frame=train)

ensemble = H2OStackedEnsembleEstimator(base_models=[my_gbm, my_rf])
ensemble.train(x=x, y=y, training_frame=train)
```

```python
In [4]: ensemble.cross_validation_metrics_summary()
No cross-validation metrics summary for this model
```
Note: This gives a standard model summary: `ensemble.cross_validation_metrics_summary`

In other models, the method returns a summary table like this:
```python
In [7]: my_rf.cross_validation_metrics_summary()
Out[7]:
Cross-Validation Metrics Summary:
                         mean      sd          cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
-----------------------  --------  ----------  ------------  ------------  ------------  ------------  ------------
accuracy                 0.6648    0.0117186   0.6725        0.669         0.644         0.6695        0.669
auc                      0.761771  0.00635164  0.767895      0.759037      0.751985      0.764674      0.765263
err                      0.3352    0.0117186   0.3275        0.331         0.356         0.3305        0.331
err_count                670.4     23.4371     655           662           712           661           662
f0point5                 0.668341  0.00935338  0.673882      0.672582      0.656944      0.678371      0.659929
f1                       0.74028   0.0081404   0.740388      0.75          0.737463      0.745083      0.728466
f2                       0.829747  0.0141141   0.82146       0.847559      0.840477      0.826347      0.812889
lift_top_group           1.77848   0.163896    1.80266       1.86916       1.66821       1.56827       1.98413
logloss                  0.583397  0.00470683  0.576402      0.583977      0.589635      0.58394       0.583033
max_per_class_error      0.604207  0.0558807   0.565539      0.629032      0.687296      0.592795      0.546371
mcc                      0.350469  0.0253559   0.362479      0.365513      0.308388      0.345384      0.37058
mean_per_class_accuracy  0.649203  0.0181545   0.660304      0.649503      0.619744      0.649175      0.667291
mean_per_class_error     0.350797  0.0181545   0.339696      0.350497      0.380256      0.350825      0.332709
mse                      0.199568  0.00197161  0.196876      0.199863      0.202404      0.199157      0.19954
pr_auc                   0.77801   0.00767388  0.785139      0.774624      0.781224      0.78286       0.766203
precision                0.627718  0.0112207   0.635807      0.629278      0.61237       0.640159      0.620979
r2                       0.19832   0.00902606  0.210194      0.196609      0.185299      0.19771       0.201789
recall                   0.902613  0.0229263   0.886148      0.928037      0.926784      0.891144      0.880952
rmse                     0.446726  0.00220619  0.443707      0.447061      0.449893      0.446271      0.446699
specificity              0.395793  0.0558807   0.434461      0.370968      0.312704      0.407205      0.453629
```

**Comment by tomasfryda** [comment]
@ledell I think the problem is that you didn't set the `metalearner_nfolds` to SE so it didn't use cross-validation hence we have no cross-validation summary.

**Comment by ledell** [comment]
Hey @tomasfryda I had a build error for R when I tried to build just now:

Execution failed for task ':h2o-r:buildPackageDocumentation'.

```
~/h2o-3/h2o-r/build/tmp $ cat h2o-r_buildPackageDocumentation.err
Loading required package: usethis
ℹ Updating h2o documentation
Updating roxygen version in /Users/me/h2oai/github/backup2_h2o-3/h2o-r/h2o-package/DESCRIPTION
ℹ Loading h2o
Error in add_classes_to_exports(ns = nsenv, package = package, exports = exports,  :
  in package ‘h2o’ classes H2OInfogram were specified for export but not defined
Calls: document ... <Anonymous> -> setup_ns_exports -> add_classes_to_exports
In addition: Warning messages:
1: roxygen2 requires Encoding: UTF-8
2: S3 method ‘plot.H2OInfogram’ was declared in NAMESPACE but not found
3: In setup_ns_exports(path, export_all, export_imports) :
  Objects listed as exports, but not present in namespace: H2OInfogram, h2o.get_admissible_attributes, h2o.infogram
Execution halted
```

Would you mind changing the base branch to rel-zorn, and then I will try to build again?  Thanks!

**Review by sebhrusen — APPROVED** [review]
oh yeah, much simpler this way! thx @tomasfryda

**Review by ledell — APPROVED** [review]
This looks good, thanks!

**Pull request merged**
