### PR TITLE
PUBDEV-7171 "Unlimited" log file size update

### PR DESCRIPTION
**Pull request by maurever**
Keep `RollingFileAppender`
Make size configurable
Add test

JIRA: https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-7171

### CODE REVIEW

**Comment by michalkurka** [comment]
@maurever can you please make this configurable?

**Comment by Pscheidl** [comment]
This is why we should use SLF4J with reasonable implementation !

**Comment by maurever** [comment]
Thank you @Pscheidl, for helping me with the test and for the review!

**Comment by maurever** [comment]
> @maurever can you please make this configurable?

Is it now ok @michalkurka ?

**Pull request merged**
