### PR TITLE
[PUBDEV-4125] - Automatic radius selection for Aggregator - add target_num_exemplars parameter, remove radius_scale

### PR DESCRIPTION
**Pull request by arnocandel**
added target_num_exemplars parameter (defaults to 5000), removed radius_scale

returns a frame with a number of exemplars that is within 50% of the target value (50%-150%).

takes about 1 min to aggregate 116M rows (airline) to 5000 exemplars on my laptop.

NOTE: we could make the 50% a parameter for more or less "picky" users, but maybe we don't need to do that just yet - ideas/thoughts?

### CODE REVIEW

**Comment by micahstubbs** [comment]
looking at this locally now 😄

**Comment by arnocandel** [comment]
@h2o-ops please test!

**Comment by micahstubbs** [comment]
seems to work as expected.  on the Grupo Bimbo test set, targeting `5000` rows produced an output frame with `3665` rows.  this should be sufficient for visualization use for now.  a parameter that allowed me to express to `h2o-3` that I'm willing to wait longer for an output frame that is closer to the target `5000` rows would be nice to have. 

screen shot 2017-03-14 at 12 01 10 pm

```
buildModel 'aggregator', {"model_id":"aggregator-0ee7f788-2278-4fb7-831f-1fbe83a6b72d","training_frame":"test.hex","ignored_columns":[],"ignore_const_cols":true,"target_num_exemplars":5000,"categorical_encoding":"AUTO","transform":"NORMALIZE"}
```

screen shot 2017-03-14 at 12 04 19 pm

screen shot 2017-03-14 at 12 01 25 pm

**Comment by arnocandel** [comment]
Try rel_tol_num_exemplars < 0.5, and it will be closer to what you want :)

**Comment by micahstubbs** [comment]
@arnocandel this `rel_tol_num_exemplars` parameter is just the thing 👌 

with `"target_num_exemplars":5000`, and `"rel_tol_num_exemplars":"0.2"`,  I get `4983` output rows, only a `0.34%` difference 😄 

```
buildModel 'aggregator', {"model_id":"aggregator-bec2637e-ed31-4e31-8c4d-ff2d42a5c578","training_frame":"test.hex","ignored_columns":[],"ignore_const_cols":true,"target_num_exemplars":5000,"rel_tol_num_exemplars":"0.2","categorical_encoding":"AUTO","transform":"NORMALIZE"}
```

screen shot 2017-03-14 at 1 03 06 pm

**Comment by micahstubbs** [comment]
👍

**Pull request merged**
