### PR TITLE
Found seed that will work for pyunit_imbalanced_gbm.py.

### PR DESCRIPTION
**Pull request by wendycwong**
Set the seed for pyunit_imbalanced_gbm.py to make it pass.

### CODE REVIEW

**Comment by arnocandel** [comment]
If the test passes - please merge.

**Comment by wendycwong** [comment]
Arno:  Thanks, will do.  Wendy

**Comment by st-pasha** [comment]
@arnocandel 
As a general rule, we should avoid hard-coding seeds into tests. Ideally, a test would choose a seed randomly, then report it to the log file (like here: https://github.com/h2oai/h2o-3/pull/831/commits/3b3f768f3b43cb3bd78ee49487794e26da144427), and then use that seed. If a test works for some seeds and not for others, then it's just a lousy test (which might be the case here). Now, a lousy test is better than no test at all; and it might be that the test is not really fixable (which might be the case here) -- however in general using fixed seeds should be avoided...

**Comment by wendycwong** [comment]
Yeah.  Merging now.

**Comment by vpatryshev** [comment]
If you do not hard-code a seed in a unittest, it's not a unittest, because
you can't reproduce.
On the other hand, there's a lot of advantage to run on random data. But
the seeds should be recorded in the logs, so if something fails, we would
be able to reproduce the error.

Thanks,
-Vlad

**Comment by arnocandel** [comment]
Yes - both approaches have merit and that's what we do. If we don't record the seed, it's a bug. This particular test's error cannot be reasonably absolutely bounded, so setting a seed is better than intermittent failures. It still tests something.

**Comment by mmalohlava** [comment]
I would say we need a strict separation between unit tests and brute force random tests. At least in the name of test.

**Pull request merged**
