### PR TITLE
PUBDEV-6294: Expose check_constant_response for DRF and GBM

### PR DESCRIPTION
**Pull request by navdeep-G**
* Expose `check_constant_response` for DRF and GBM
* This variable is set to `true` by default, which is behavior today, i.e., thrown an exception if response column is a constant value
* Added simple unit tests in R/Python client which basically ensures GBM and DRF respect this argument if set to `false`

### CODE REVIEW

**Comment by angela0xdata** [comment]
@navdeep-G Just an FYI that this needs to be changed in the docs and in Flow. I opened a Jira ticket for the docs (https://0xdata.atlassian.net/browse/PUBDEV-6287), and I can work on that when this is merged. Should the change in Flow be included in this PR or in a separate PR/Jira?

**Comment by navdeep-G** [comment]
@angela0xdata I think Flow should be another ticket. However, I thought these changes will be picked up Flow automatically? Right @michalkurka @michal-raska ?

**Comment by michal-raska** [comment]
@navdeep-G yes, it's there automatically in this case (because it's `boolean` and Flow knows how to handle this type). But for some more complex types (for example `KeyValue[]`) it might have to be added manually.

**Comment by angela0xdata** [comment]
@michal-raska @navdeep-G ahh, I didn't know that about Booleans in Flow. Thanks for the info!

**Comment by navdeep-G** [comment]
@michalkurka I think this PR is good to go. Agree?

**Pull request merged**
