### PR TITLE
two new time formats

### PR DESCRIPTION
**Pull request by cliffclick-neurensic**
mmmyy
yy-mmm
Not ambiguous with any prior time format

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/47)

### CODE REVIEW

**Comment by abal5** [comment]
Currently testing this PR please wait for response from the team.

**Comment by abal5** [comment]
Currently testing this PR please wait for response from the team.

**Comment by abal5** [comment]
Currently testing this PR please wait for response from the team.

**Comment by mmalohlava** [comment]
Hi Cliff,

I cherry picked your change into master manually and stacked it with other changes fixing failing tests.
Your commit is here: `912d757`

I would also recommend to reset your `cliffc_jenkins` branch to the latest master:
```
git fetch origin
git checkout cliffc_jenkins
git reset --hard origin/master
```
Thank you for the change!
michal

**Comment by cliffclick** [comment]
Thanks!

**Pull request closed without merging**
