### PR TITLE
[SW-481] MOJO for SVM

### PR DESCRIPTION
**Pull request by mdymczyk**
MOJO reader and model for (Spark) SVM. Still needs unit tests

### CODE REVIEW

**Comment by jakubhava** [comment]
Minor thing - this should have a JIRA from H2O project ( not SW ) which can reference [SW-481]

**Comment by tomkraljevic** [comment]
mateusz, please look at the mojoland repo, which has automated test cases for mojos.
ask @st-pasha if you have questions.

**Comment by mdymczyk** [comment]
@tomkraljevic ok will have a look. Should we also add there data for other models in that case? I don't see there any data for KMeans, GLM or Word2Vec.

**Comment by mdymczyk** [comment]
@jakubhava ok I can make another JIRA but is there any (technical) reason behind doing it like this? I don't see the point in having 2 JIRAs for the same issue otherwise.

**Comment by jakubhava** [comment]
@mdymczyk It's  better for tracking since right now you have JIRA in SW and you can't put there version of H2O in which it will be fixed. You can track progress only within a single project. 

And after all, it just make sense to me - PUBDEV in H2O, SW in Sparkling Water, better separation

**Comment by mdymczyk** [comment]
@jakubhava well we can always add an optional h2o version field to sw project in jira and mention a given task also touches h2o. Otherwise we'll be duplicating a lot of tasks in jira.

**Comment by jakubhava** [comment]
Jira is not perfect for multi project issues. This is easy one click solution. I will be always separating these since it just make sense but I don't want to enforce it on others. Do as what you think is the best.

**Comment by jakubhava** [comment]
This is actually PUBDEV-4692, SW-481 is the Sparkling Water side of the implementation

**Pull request merged**
