### PR TITLE
PUBDEV-6231 Deep Learning mojo predict bug

### PR DESCRIPTION
**Pull request by maurever**
In `GenModel.java` the `setCats()` ([L605](https://github.com/h2oai/h2o-3/blob/564de78fbae03187d9d123c44efc4af5544e66e6/h2o-genmodel/src/main/java/hex/genmodel/GenModel.java#L605)) method change the zero categorical level to -1 - in `DeepLearningModel.java` ([L504](https://github.com/h2oai/h2o-3/blob/564de78fbae03187d9d123c44efc4af5544e66e6/h2o-algos/src/main/java/hex/deeplearning/DeepLearningModel.java#L703) method setInput() in Neurons.java [L508](https://github.com/h2oai/h2o-3/blob/564de78fbae03187d9d123c44efc4af5544e66e6/h2o-algos/src/main/java/hex/deeplearning/Neurons.java#L508) and [L519](https://github.com/h2oai/h2o-3/blob/564de78fbae03187d9d123c44efc4af5544e66e6/h2o-algos/src/main/java/hex/deeplearning/Neurons.java#L519)) and POJO model keep the zero categorical level equals zero. 

JIRA: https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-6231

### CODE REVIEW

**Comment by michalkurka** [comment]
Note: Discussed in person - the bug seems to be on the backend implementation, not in the mojo.

**Comment by maurever** [comment]
I fixed the bug in DeepLearningModel and POJO instead of fixing the DeepLearningMojoModel.

Should I also include the [test (pyunit_pubdev_4628_pubdev_4950_deeplearning_mojo_pojo_NOPASS.py)](https://0xdata.atlassian.net/secure/attachment/41506/41506_pyunit_pubdev_4628_pubdev_4950_deeplearning_mojo_pojo_NOPASS.py) in large tests?

**Comment by michalkurka** [comment]
@maurever thank you; yes, please also re-enable the test and include it in a suitable test suite :)

**Comment by wendycwong** [comment]
Veronica:  So the problem is with the 0ne-hot-encoding of categoricals, ha.

**Pull request merged**
