### PR TITLE
Ld/new/pubdev 3885

### PR DESCRIPTION
**Pull request by laurendiperna**

### CODE REVIEW

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by ledell** [comment]
@laurendiperna Do you know why the tests are still failing?

**Comment by laurendiperna** [comment]
@ledell The first time it's because a script was missing, but jeff added them back in, now it seems like some aws credentials are missing from a machine. Tests keep getting overwritten so I can't see what happened on pyunit small J6. so I'll need to rerun again.

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Pull request merged**
