### PR TITLE
[PUBDEV-3484] AstMean upgrade

### PR DESCRIPTION
**Pull request by st-pasha**
As discussed in #api-updates; this PR changes the functionality of rapids `mean` function to return a frame instead of a ValRow (to facilitate reuse of these results in various expressions). Additionally, the function acquires new parameter `axis`, which can be used to switch from column-wise means to row-wise means.

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/359)

### CODE REVIEW

**Comment by st-pasha** [comment]
@h2o-ops please test

**Comment by st-pasha** [comment]
@h2o-ops please test

**Comment by h2o-ops** [comment]
Tests passed!

**Comment by mmalohlava** [comment]
@h2o-ops please test

**Pull request merged**
