### PR TITLE
PUBDEV 3369

### PR DESCRIPTION
**Pull request by angela0xdata**
- Added back in some changes from PUBDEV-2872 for some of these missing parameters (in DRF and GBM).
- Also added huber_alpha to list of deeplearning parameters.
- Fixes also resolve PUBDEV-3353
- Ignore .gz files created when books are tested.

---
This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/185)

### CODE REVIEW

**Comment by arnocandel** [comment]
Shouldn't the updated PDF booklets be part of this commit too?

**Comment by angela0xdata** [comment]
No, the PDFs don't get checked in. They are automatically generated from the .tex files as part of the build process. I did run ./gradlew h2o-docs:booklets locally, just to make sure that they build and that any new syntax didn't result in an error.

**Comment by arnocandel** [comment]
If the PDFs aren't checked in, then tweets like this will point to outdated booklets, no? https://twitter.com/KirkDBorne/status/774273100250775553

**Comment by arnocandel** [comment]
ok - http://docs.h2o.ai/ is the only source of truth :)

**Pull request merged**
