### PR TITLE
edit gbmTuning tutorial to be compatible with py2/py3

### PR DESCRIPTION
**Pull request by OmaymaS**
The suggested modifications is about the **GBM Tuning** [python example](https://github.com/h2oai/h2o-3/blob/master/h2o-docs/src/product/tutorials/gbm/gbmTuning.ipynb). The objective is to make the code compatible with both python 2 and 3.

**Main edits**
- `print x` changed to `print(x)` across the notebook.
- 'max_depth' : range(1,30,2) changed to 'max_depth' : list(range(1,30,2)).
- `iteritems()` changed to `items()`.

**Notes**
- I just used `[sudo] pip install h2o` and wrote a note about this in the first section.
- I didn't update FLOW screenshots to match the results.
- There are two sections that I haven't run because they threw errors, particularly in `setattr(gbm_best,key,params[key]['actual']) ` and `setattr(new_model,key,params[key]['actual'])`. *errors below*.

**Errors**

```
---------------------------------------------------------------------------
H2OTypeError                              Traceback (most recent call last)
<ipython-input-32-1a917569ea2c> in <module>
      8 for key in params.keys():
      9     if key in dir(gbm_best) and getattr(gbm_best,key) != params[key]['actual']:
---> 10         setattr(gbm_best,key,params[key]['actual'])

~\Anaconda3\lib\site-packages\h2o\estimators\gbm.py in training_frame(self, training_frame)
     64     @training_frame.setter
     65     def training_frame(self, training_frame):
---> 66         assert_is_type(training_frame, None, H2OFrame)
     67         self._parms["training_frame"] = training_frame
     68 

~\Anaconda3\lib\site-packages\h2o\utils\typechecks.py in assert_is_type(var, *types, **kwargs)
    455     vtn = _get_type_name(type(var))
    456     raise H2OTypeError(var_name=vname, var_value=var, var_type_name=vtn, exp_type_name=etn, message=message,
--> 457                        skip_frames=skip_frames)
    458 
    459 

H2OTypeError: Argument `training_frame` should be an ?H2OFrame, got H2OResponse {'__meta': {'schema_version': 3, 'schema_name': 'FrameKeyV3', 'schema_type': 'Key<Frame>'}, 'name': 'train.hex', 'type': 'Key<Frame>', 'URL': '/3/Frames/train.hex'}
```

**Session info**

```
import sinfo
sinfo.sinfo()
```

```
-----
h2o       	3.24.0.3
numpy     	1.16.2
pandas    	0.24.2
sklearn   	0.20.3
-----
IPython   	7.3.0
jupyter_client	5.2.4
jupyter_core	4.4.0
jupyterlab	0.35.3
notebook  	5.7.6
-----
Python 3.7.2 (default, Feb 21 2019, 17:35:59) [MSC v.1915 64 bit (AMD64)]
Windows-8.1-6.3.9600-SP0
8 logical CPU cores, Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
-----
Session information updated at 2019-05-18 00:49
```

### CODE REVIEW

**Comment by OmaymaS** [comment]
@michalkurka I made the modifications as per the discussion on Gitter. I assumed it was ok to compare with `master`.

**Comment by michalkurka** [comment]
@OmaymaS thank you, we appreciate your effort! we will review this shortly.

master as the target base is perfect

**Comment by michalkurka** [comment]
Mr. Jenkins, please test!

**Comment by michalkurka** [comment]
We will have to fix the errors to work on latest H2O.

**Pull request closed without merging**
