### PR TITLE
Question: how to get iteration of each individual model in h2o.automl

### PR DESCRIPTION
**Pull request by jmren168**
Hi there,

I'm new to h2o.automl, and would like to know how to get **the iteration of each individual model** when h2o.automl finished the training process. (ps. currently, I can get **the iteration of best model** when h2o.automl finished the training stage.) 

Any comments are highly appreciated.  
Tks.

### CODE REVIEW

**Comment by sebhrusen** [comment]
@hannah-tillman are you sure you pushed your changes to the correct PR? I don't see the relation between those and the question above.

**Comment by sebhrusen** [comment]
@hannah-tillman given the dates, it's not you: you pushed those commits before this PR was created.

@jmren168 please creating PR is not the right way to ask questions. We may enable the `Discussions` section to this GitHub repo soon for that purpose, but currently we monitor questions from the following sources:
- https://stackoverflow.com/  : tag your question with `h2o`, `h2oautoml`
- https://gitter.im/h2oai/h2o-3

**Comment by hannah-tillman** [comment]
> @hannah-tillman given the dates, it's not you: you pushed those commits before this PR was created.
> 
> @jmren168 please creating PR is not the right way to ask questions. We may enable the `Discussions` section to this GitHub repo soon for that purpose, but currently we monitor questions from the following sources:
> 
> * https://stackoverflow.com/  : tag your question with `h2o`, `h2oautoml`
> * https://gitter.im/h2oai/h2o-3

Thanks for figuring this out @sebhrusen! I haven't even made a PR yet for this branch so I was very confused by what was going on :/

**Comment by jmren168** [comment]
@sebhrusen thank you for your recommendations. I will ask questions at https://stackoverflow.com/ as well as https://gitter.im/h2oai/h2o-3 in the future.
@hannah-tillman sorry to make you confused, since I didn't find any discussion section on the h2o website.

**Comment by hannah-tillman** [comment]
@jmren168 I will be adding a section for that very reason right now :)

**Pull request closed without merging**
