### PR TITLE
PUBDEV-4639: use data.table.  Set use data.table to be true by defaul…

### PR DESCRIPTION
**Pull request by wendycwong**
If data.table package is available, the PR will set use data.table by default.

### CODE REVIEW

**Comment by ledell** [comment]
@wendycwong If **data.table** is installed, will it still be used if the user sets: `options("h2o.use.data.table"=FALSE)`, or will we honor the user's request to not use it?

**Comment by wendycwong** [comment]
Regarding your question, if the user sets it to false, then, it will not be used.
The change I make works like this:

- if the user has data.table and has never use options() regarding the data table, then, by default, the getOption("h2o.use.data.table", TRUE) will return TRUE. 
- if the user has data.table and use options() regarding data.table but set it to FALSE, then, the getOption("h2o.use.data.table", TRUE) will return FALSE.  And, hence, even if the user has data.table in this case, it will not be used.

Does this work?

**Comment by wendycwong** [comment]
Something is wrong.  Needs more fixing.  Many Jenkins tests failed....

**Comment by ledell** [comment]
@wendycwong If *PR_smoke_runit* fails, it will cause the others to fail.  It might be intermittent because the tests that failed are: runit_GLM_weights2.R, runit_GBM_weight_gamma.R, which seems unrelated.  I have restarted the test.

**Comment by wendycwong** [comment]
@erin:  Thanks.  I am keeping an eye on it too.

**Comment by wendycwong** [comment]
@erin:  tried 3 times and they still failed.  Not sure they are all intermittents.  If they are, the universe is out there to get me for some reason.  :-(

**Comment by ledell** [comment]
Here's some info about the failures (for debugging later).  Both have to do with using `as.data.frame(h2o.predict())`, so it might be a real bug (not with this PR) but with the **data.table** version of `as.data.frame()`` -- some edge case that was not checked, that we are seeing now that we turn it on everywhere.

[runit_GBM_weight_gamma.R](https://github.com/h2oai/h2o-3/blob/master/h2o-r/tests/testdir_algos/gbm/runit_GBM_weight_gamma.R)
```
[2017-07-28 12:58:21] [ERROR] : Error: Test failed: 'GBM weight Test: GBM w/ weight for gamma distribution'
* 3751.01 not equal to min(ph[, 1]).
Types not compatible: double vs character

* 15291 not equal to max(ph[, 1]).
Types not compatible: double vs character

* 8119 not equal to mean(ph[, 1]).
1/1 mismatches
[1] 8119 - NA == NA
```

[runit_GLM_weights2.R](https://github.com/h2oai/h2o-3/blob/master/h2o-r/tests/testdir_algos/glm/runit_GLM_weights2.R)

```
* `ph1` not equal to `ph2`.
```

**Comment by wendycwong** [comment]
@ledell 

Good call.  Will take a look at it or whine at Matt.

**Comment by mattdowle** [comment]
Can someone look at the test and see what's different now that data.table is on?  It looks like a `double` vs `character` issue but more information on that would be useful.

**Comment by ledell** [comment]
I have found that the failures occur when the **bit64** package is not installed.  In that case, `h2o::as.data.frame()` will convert numbers to strings when using the **data.table** backend.

In the  runit_GLM_weights2.R test, we have the following:
```
> ph1 <- as.data.frame(h2o.predict(object = hh1, newdata = val1))
> head(ph1)
               predict
1 -0.24735716115668827
2  -0.6849558489755788
3   0.8298050526306969
4      1.4533477607208
5  -0.4536486164991942
6   0.6481114138220089
> str(ph1)
'data.frame':	100 obs. of  1 variable:
 $ predict: chr  "-0.24735716115668827" "-0.6849558489755788" "0.8298050526306969" "1.4533477607208" ...
```
So we should check for **bit64** and fall back to native H2O for read/write instead of **data.table**, and display a warning that they should install the package to be able to take advantage of **data.table** read/write speed-ups.

Let's also add **bit64** to the "Suggested" packages list.

**Comment by wendycwong** [comment]
Added check for bit64 before enabling data.table.  Erin/Matt found this problem on our jenkin machines.

**Comment by wendycwong** [comment]
Per Erin:  Need bit64 and the version has to be >= 0.9.7

**Pull request merged**
