### PR TITLE
PUBDEV-4702-maxruntime-tests: completed pyunit and runit tests to set…

### PR DESCRIPTION
**Pull request by wendycwong**
Test and set max_runtime_secs for every algo to make sure that they work to some extend.

PUBDEV-4702: max_runtime_secs.  Added backend code to stop if max_runtime_secs is reached for algo word2vec, pca.
PUBDEV-4702: max_runtime_secs.  Changed iteration to iterations as is more commonly used in scoring_history.

### CODE REVIEW

**Comment by ledell** [comment]
@wendycwong Why are you changing the column name from "iteration" to "iterations" in all the scoring history tables?

**Comment by ledell** [comment]
@wendycwong Stacked Ensemble currently has no ability on the Java backend to deal with `max_runtime_secs` that I am aware of, so I don't think this is doing anything for Stacked Ensemble.  In order for this to work properly, we would need to pipe `max_runtime_secs` through to the GLM metalearner in Stacked Ensemble.  

@rpeck Does that sound correct to you?

**Comment by ledell** [comment]
@wendycwong There is a problem with how you are editing the R algorithm files, `stackedensemble.R` and `word2vec.R`.  The R (and Python) bindings are auto-generated, so you cannot edit the files directly, you must edit the `./h2o-bindings/bin/gen_R.py` file if you want to make changes to any of the algorithms in R.  If you check out this branch and run a `./gradlew build -x test` it will overwrite all of your manual changes to the files.

**Comment by wendycwong** [comment]
Erin:  

Regarding the iteration, it is part of the scoring_history and the majority of algos use iterations.  Hence, I made the change after discussing with Michal K to be consistent. 

The max_runtime_secs is defined everywhere in the backend but stack ensemable is not using it now.  Word2Vec is though since after I added it to py client, it is reducing the number of iterations it is allowed.  Basically the pipeline for using max_runtime_secs is established.  Just need to set up the pipeline to the clients and call the correct functions in Java.

Good call on the auto gen part.  I will write the functions in gen_R.py to complete the establish the client side pipeline for word2vec and stackensemble.  You can decide to use it later if you want.  

For non-iterative algos, I do not restrict the time to finish execution.  The code is there to test out the client side pipeline.

**Comment by wendycwong** [comment]
An Runit output:

[1] "*************  starting max_runtime_test for GBM"
  |======================================================================| 100%
  |======================================================================| 100%
  |======================================================================| 100%
[1] "max_runtime_secs:  0.813"
[1] "actual model runtime in sec:  0.839"
[1] "runtime overrun factor:  0.0319803198031981"
[1] "model iterations/epochs/trees without max_runtime_secs:  50"
[1] "model iterations/epochs/trees with max_runtime_secs:  29"
[1] "************* Test passed!"
[1] "*************  starting max_runtime_test for GLM"
  |======================================================================| 100%
  |======================================================================| 100%
[1] "max_runtime_secs:  0.3385"
[1] "actual model runtime in sec:  0.389"
[1] "runtime overrun factor:  0.149187592319055"
[1] "model iterations/epochs/trees without max_runtime_secs:  8"
[1] "model iterations/epochs/trees with max_runtime_secs:  3"
[1] "************* Test passed!"
[1] "*************  Skip testing Naive Bayes, not an iterative algo."
[1] "*************  starting max_runtime_test for Random Forest"
  |======================================================================| 100%
  |======================================================================| 100%
[1] "max_runtime_secs:  2.1755"
[1] "actual model runtime in sec:  2.187"
[1] "runtime overrun factor:  0.00528614111698453"
[1] "model iterations/epochs/trees without max_runtime_secs:  100"
[1] "model iterations/epochs/trees with max_runtime_secs:  48"
[1] "************* Test passed!"
[1] "*************  starting max_runtime_test for PCA"
  |======================================================================| 100%
  |======================================================================| 100%
  |======================================================================| 100%
[1] "max_runtime_secs:  0.0815"
[1] "actual model runtime in sec:  0.114"
[1] "runtime overrun factor:  0.398773006134969"
[1] "model iterations/epochs/trees without max_runtime_secs:  3613"
[1] "model iterations/epochs/trees with max_runtime_secs:  0"
[1] "************* Test passed!"
[1] "*************  starting max_runtime_test for kmeans"
  |======================================================================| 100%
  |======================================================================| 100%
  |======================================================================| 100%
[1] "max_runtime_secs:  0.01"
[1] "actual model runtime in sec:  0.011"
[1] "runtime overrun factor:  0.0999999999999999"
[1] "model iterations/epochs/trees without max_runtime_secs:  10"
[1] "model iterations/epochs/trees with max_runtime_secs:  0"
[1] "************* Test passed!"
[1] "*************  starting max_runtime_test for deeplearning"
  |======================================================================| 100%
  |======================================================================| 100%
  |======================================================================| 100%
[1] "max_runtime_secs:  0.068"
[1] "actual model runtime in sec:  0.055"
[1] "runtime overrun factor:  -0.191176470588235"
[1] "model iterations/epochs/trees without max_runtime_secs:  10"
[1] "model iterations/epochs/trees with max_runtime_secs:  1"
[1] "************* Test passed!"
[1] "Cannot build a Deep Water model - no backend found."
[1] "*************  deepwater is skipped.  Not availabe."
[1] "*************  starting max_runtime_test for GLRM"
  |======================================================================| 100%
  |======================================================================| 100%
  |======================================================================| 100%
[1] "max_runtime_secs:  0.1035"
[1] "actual model runtime in sec:  0.119"
[1] "runtime overrun factor:  0.14975845410628"
[1] "model iterations/epochs/trees without max_runtime_secs:  19"
[1] "model iterations/epochs/trees with max_runtime_secs:  1"
[1] "************* Test passed!"
[1] "*************  starting max_runtime_test for word2vec"
  |======================================================================| 100%
  |======================================================================| 100%
  |======================================================================| 100%
[1] "max_runtime_secs:  2.5125"
[1] "actual model runtime in sec:  3.23"
[1] "runtime overrun factor:  0.285572139303482"
[1] "model iterations/epochs/trees without max_runtime_secs:  4"
[1] "model iterations/epochs/trees with max_runtime_secs:  2"
[1] "************* Test passed!"
[1] "*************  Skip testing stak ensemble, not an iterative algo."
[2017-08-08 09:21:14] [WARN] : simpleWarning in doTryCatch(return(expr), name, parentenv, handler): _train: Dataset used may contain fewer number of rows due to removal of rows with NA/missing values.  If this is not desirable, set impute_missing argument in pca call to TRUE/True/true/... depending on the client language.

No traceback available 
[2017-08-08 09:21:14] [WARN] : simpleWarning in doTryCatch(return(expr), name, parentenv, handler): _train: PCA Power method failed to converge within TOLERANCE.  Increase max_iterations or reduce TOLERANCE to mitigate this problem.

No traceback available 
[2017-08-08 09:21:14] [WARN] : simpleWarning in doTryCatch(return(expr), name, parentenv, handler): _train: PCA Power method failed to converge within TOLERANCE.  Increase max_iterations or reduce TOLERANCE to mitigate this problem.

No traceback available 
[2017-08-08 09:21:14] [WARN] : simpleWarning in doTryCatch(return(expr), name, parentenv, handler): _train: Dataset used may contain fewer number of rows due to removal of rows with NA/missing values.  If this is not desirable, set impute_missing argument in pca call to TRUE/True/true/... depending on the client language.

No traceback available 

########     ###     ######   ###### 
##     ##   ## ##   ##    ## ##    ##
##     ##  ##   ##  ##       ##      
########  ##     ##  ######   ###### 
##        #########       ##       ##
##        ##     ## ##    ## ##    ##
##        ##     ##  ######   ######

**Comment by wendycwong** [comment]
PyUnit test output: 
Checking whether there is an H2O instance running at http://localhost:54321. connected.
--------------------------  ----------------------------------------
H2O cluster uptime:         11 mins 45 secs
H2O cluster version:        3.13.0.99999
H2O cluster version age:    13 minutes
H2O cluster name:           wendycwong
H2O cluster total nodes:    1
H2O cluster free memory:    1.833 Gb
H2O cluster total cores:    4
H2O cluster allowed cores:  4
H2O cluster status:         locked, healthy
H2O connection url:         http://localhost:54321
H2O connection proxy:
H2O internal security:      False
H2O API Extensions:         XGBoost, Algos, AutoML, Core V3, Core V4
Python version:             2.7.10 final
--------------------------  ----------------------------------------
Parse progress: |█████████████████████████████████████████████████████████| 100%
deeplearning Model Build progress: |██████████████████████████████████████| 100%
deeplearning Model Build progress: |██████████████████████████████████████| 100%
Model: deeplearning, 
Max_runtime_sec: 0.0275, 
Actual_model_runtime_sec: 0.024, 
Run time overrun: -0.127272727273
Number of epochs/iterations/trees without max_runtime_sec restriction: 10.0
Number of epochs/iterations/trees with max_runtime_sec restriction: 1.0
********** Test passed!.
******************** Skip testing stack ensemble.  Not an iterative algo.
Parse progress: |█████████████████████████████████████████████████████████| 100%
gbm Model Build progress: |███████████████████████████████████████████████| 100%
gbm Model Build progress: |███████████████████████████████████████████████| 100%
Model: gbm, 
Max_runtime_sec: 0.6225, 
Actual_model_runtime_sec: 0.653, 
Run time overrun: 0.0489959839357
Number of epochs/iterations/trees without max_runtime_sec restriction: 51
Number of epochs/iterations/trees with max_runtime_sec restriction: 20
********** Test passed!.
glm Model Build progress: |███████████████████████████████████████████████| 100%
glm Model Build progress: |███████████████████████████████████████████████| 100%
Model: glm, 
Max_runtime_sec: 0.1885, 
Actual_model_runtime_sec: 0.199, 
Run time overrun: 0.0557029177719
Number of epochs/iterations/trees without max_runtime_sec restriction: 9
Number of epochs/iterations/trees with max_runtime_sec restriction: 5
********** Test passed!.
******************** Skip testing Naives Bayes.  Not an iterative algo.
drf Model Build progress: |███████████████████████████████████████████████| 100%
drf Model Build progress: |███████████████████████████████████████████████| 100%
Model: drf, 
Max_runtime_sec: 1.5905, 
Actual_model_runtime_sec: 1.631, 
Run time overrun: 0.0254636906633
Number of epochs/iterations/trees without max_runtime_sec restriction: 101
Number of epochs/iterations/trees with max_runtime_sec restriction: 45
********** Test passed!.
Cannot build a Deep Water model - no backend found.
Parse progress: |█████████████████████████████████████████████████████████| 100%
glrm Model Build progress: |██████████████████████████████████████████████| 100%
glrm Model Build progress: |██████████████████████████████████████████████| 100%
Model: glrm, 
Max_runtime_sec: 0.082, 
Actual_model_runtime_sec: 0.072, 
Run time overrun: -0.121951219512
Number of epochs/iterations/trees without max_runtime_sec restriction: 27
Number of epochs/iterations/trees with max_runtime_sec restriction: 2
********** Test passed!.
Parse progress: |█████████████████████████████████████████████████████████| 100%
pca Model Build progress: |███████████████████████████████████████████████| 100%
../../h2o/job.py:69: UserWarning: _train: Dataset used may contain fewer number of rows due to removal of rows with NA/missing values.  If this is not desirable, set impute_missing argument in pca call to TRUE/True/true/... depending on the client language.
  warnings.warn(w)
pca Model Build progress: |███████████████████████████████████████████████| 100%
Model: pca, 
Max_runtime_sec: 0.0415, 
Actual_model_runtime_sec: 0.044, 
Run time overrun: 0.0602409638554
Number of epochs/iterations/trees without max_runtime_sec restriction: 2343
Number of epochs/iterations/trees with max_runtime_sec restriction: 0
********** Test passed!.
Parse progress: |█████████████████████████████████████████████████████████| 100%
kmeans Model Build progress: |████████████████████████████████████████████| 100%
kmeans Model Build progress: |████████████████████████████████████████████| 100%
Model: kmeans, 
Max_runtime_sec: 0.018, 
Actual_model_runtime_sec: 0.011, 
Run time overrun: -0.388888888889
Number of epochs/iterations/trees without max_runtime_sec restriction: 9
Number of epochs/iterations/trees with max_runtime_sec restriction: 8
********** Test passed!.
Parse progress: |█████████████████████████████████████████████████████████| 100%
word2vec Model Build progress: |██████████████████████████████████████████| 100%
word2vec Model Build progress: |██████████████████████████████████████████| 100%
Model: word2vec, 
Max_runtime_sec: 5.4225, 
Actual_model_runtime_sec: 6.474, 
Run time overrun: 0.193914246196
Number of epochs/iterations/trees without max_runtime_sec restriction: 4
Number of epochs/iterations/trees with max_runtime_sec restriction: 2
********** Test passed!.

**Comment by ledell** [comment]
This looks good to me.  I see you've removed `max_runtime_secs` from stacked ensemble, and I think it's good to keep it out of the API for now, thanks.

**Pull request merged**
