### PR TITLE
[PUBDEV-5111] Additional updates to Sparkling Water Booklet

### PR DESCRIPTION
**Pull request by jakubhava**

### CODE REVIEW

**Comment by angela0xdata** [comment]
@h2o-ops please test!

**Comment by angela0xdata** [comment]
Made additional minor edits to the new section and to the covers.

**Comment by jakubhava** [comment]
@angela0xdata did you push the change pls ? I still can't see it :)

**Comment by jakubhava** [comment]
oh, maybe I just understood in on a wrong way. The ^ was just comment.

@mmalohlava could you please have a quick look before we merge ?

**Comment by angela0xdata** [comment]
Whoops... didn't notice error when I first merged. Looks like my internet went down for a moment.

**Comment by angela0xdata** [comment]
@h2o-ops please test!

**Comment by jakubhava** [comment]
great, thanks for the updates!

**Comment by jakubhava** [comment]
@angela0xdata I think we are good to go and merge

**Pull request merged**
