### PR TITLE
Cliffc sortcrash

### PR DESCRIPTION
**Pull request by cliffclick**
Small file of plain integers.  When calling Frame.sort it triggers an assert in RadixSort

---

This change is [Reviewable](https://reviewable.io/reviews/h2oai/h2o-3/345)

### CODE REVIEW

**Comment by cliffclick** [comment]
Now includes potential fix.

**Comment by mmalohlava** [comment]
@h2o-ops please re-build

**Comment by h2o-ops** [comment]
Tests passed!

**Comment by ledell** [comment]
@mattdowle Can you review and merge if this is good?

**Comment by navdeep-G** [comment]
@h2o-ops please test!

**Pull request merged**
