### PR TITLE
PUBDEV-3884 - Documentation for Stacked Ensembles

### PR DESCRIPTION
**Pull request by angela0xdata**
Initial draft of Stacked Ensembles topic for the H2O User Guide.

### CODE REVIEW

**Comment by angela0xdata** [comment]
@h2o-ops please test!

**Comment by angela0xdata** [comment]
@h2o-ops please test!

**Comment by ledell** [comment]
Thanks @angela0xdata! I will make my edits and then merge the PR.

**Comment by angela0xdata** [comment]
@h2o-ops please test!

**Comment by ledell** [comment]
@h2o-ops please test!

**Pull request merged**
