### PR TITLE
PUBDEV-5492: remove deepwater java classes

### PR DESCRIPTION
**Pull request by pkozelka**
This tries to follow up on abandoned effort found in #2317 .

Here I am only removing java classes, because python and documentation are inter-related in ways that I currently do not understand.

Even so,  getting rid of these unused classes is useful. The rest can be done separately, by people with more expertise in our docs and python build details.

### CODE REVIEW

**Comment by pkozelka** [comment]
@michalkurka I tried but there were some mysterious errors during build - so I supposed it might be better to start with smaller part that passes the build, then do the rest

**Comment by pkozelka** [comment]
@michalkurka I know you wanted it all at once- but if you change your mind, consider approving or merging this :)

**Comment by michalkurka** [comment]
@pkozelka is this blocking some of your work? I am just asking to figure out the priority of the PR

**Comment by pkozelka** [comment]
no it's just dirt, currently not blocking me, or I am not aware of that, it has no priority and will probably never have. Just another bunch of a dead code bringing non-dead dependencies.

OTOH as I see it, there is also no risks and no effort attached, that's why I wanted it done, at least this part.

**Comment by michalkurka** [comment]
Shouldn't be merged right now, please ask for details

**Pull request closed without merging**
