### PR TITLE
Improved error message regarding the continuity of time

### PR DESCRIPTION
**Pull request by vpatryshev**
In DeepLearningCheckpointReporting:

1) run(hex.deeplearning.DeepLearningCheckpointReporting)
java.lang.AssertionError: Duration must be smooth

### CODE REVIEW

**Comment by abal5** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Comment by vpatryshev** [comment]
@h2o-ops please test!

**Pull request merged**
