### PR TITLE
Add XGBoost (proper) to H2O PUBDEV-3909

### PR DESCRIPTION
**Pull request by arnocandel**

### CODE REVIEW

**Comment by arnocandel** [comment]
This is blocked until we get to work on how we ship/package the native library.

**Comment by arnocandel** [comment]
https://github.com/h2oai/h2oai-prototypes/blob/master/xgboost-gpu/GPUXGBoost.ipynb

**Comment by arnocandel** [comment]
Preview build for Linux (including CPU and GPU): https://slack-files.com/T0329MHH6-F4R8FM3J9-756a11ae80

**Comment by arnocandel** [comment]
Preview build for Linux (including CPU and GPU): https://slack-files.com/T0329MHH6-F4QG3MW5N-a538a51619

**Comment by jakubhava** [comment]
@arnocandel @mmalohlava should we close this PR and work on https://github.com/h2oai/h2o-3/pull/1211 ? It contains the changes from Arno but the conflicts are resolved.

**Comment by mmalohlava** [comment]
Closing, there is updated version in #1211 .

**Pull request closed without merging**
