### PR TITLE
[PUBDEV-5350] - Fix incorrect path used for saving and exporting

### PR DESCRIPTION
**Pull request by terrytangyuan**

### CODE REVIEW

**Comment by terrytangyuan** [comment]
@michalkurka I am not sure if I am following, this is a pretty common thing to do in R packages. Existing functionalities should not break, e.g. local, s3, hdfs. 

The result is just not intuitive to me since "~" wasn't interpreted correctly:
```
> h2o:::h2o.saveModel(model, path = "~/workRepos/mmrecipe/model_metadata/h2o-3")
[1] "/Users/terrytangyuan/~/workRepos/mmrecipe/model_metadata/h2o-3/PCA_model_R_1519664634107_1"
``

This change only normalizes the path and then same thing gets sent to the REST API.

**Comment by terrytangyuan** [comment]
@michalkurka But feel free to close this if you think this is done incorrectly. I am not familiar with H2O-3's internals yet.

**Comment by michalkurka** [comment]
@terrytangyuan The problem is that it normalizes the path on the client. It turns a relative path into an absolute one. The relative path can look very different on the local machine on the server where H2O is running.

    > normalizePath("~/")
    [1] "/Users/mkurka"

It converts a relative path to absolute and that is an issue IMHO.

**Comment by terrytangyuan** [comment]
@michalkurka Okay, I am closing this. I do think this issue needs to be fixed though since it's not intuitive and users would expect relative path starting with `~/` to just work.

**Pull request closed without merging**
