### PR TITLE
[PUBDEV-9075] Add h2o-3 label to jenkins pipelines

### PR DESCRIPTION
**Pull request by mn-mikke**

### CODE REVIEW

**Review by hasithjp — APPROVED** [review]
LGTM! THANKS

**Review by wendycwong — APPROVED** [review]
Thank you!

**Comment by hasithjp** [comment]
> LGTM! THANKS Please don't merge until we add the new label to nodes

Nodel labels are added now @mn-mikke you can proceed with merging

**Review by valenad1 — APPROVED** [review]
🥇

**Pull request merged**
