### PR TITLE
updating gbm reproducibility document

### PR DESCRIPTION
**Pull request by meganjkurka**

### CODE REVIEW

**Comment by angela0xdata** [comment]
I just pushed a couple of changes. Here's what that FAQ looks like when built. Let me know if you think this is okay.

screen shot 2019-01-29 at 1 37 24 pm

**Comment by meganjkurka** [comment]
Thank you @angela0xdata that looks great to me! Would it be possible to update the docs website with this change once it's approved or would we need to wait until a new release?

**Comment by angela0xdata** [comment]
@meganjkurka I'm not able to build h2o-3 docs. They're tied to a release. But after the merge, it will be available in the docs that are built for each nightly build release. 
Can you also cherry-pick into rel-xu?

**Comment by maurever** [comment]
I like the changes; it is more clear for me now.

**Pull request merged**
