### PR TITLE
PUBDEV-4381: changed default number of features shown in the variable…

### PR DESCRIPTION
**Pull request by laurendiperna**
… importance plot from all to 10, or all if there are less than 10 features

### CODE REVIEW

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by laurendiperna** [comment]
@h2o-ops please test!

**Comment by navdeep-G** [comment]
LGTM

**Pull request merged**
